### ISSUE TITLE
No maneuver on step

### ISSUE THREAD

**Issue by FalmaJeus** [vivet/GoogleApi#100]
Hello.
I can see 'maneuver' of step in google directions api response.
https://developers.google.com/maps/documentation/directions/intro#Steps
But within this plugin, it doesn't exist.
GoogleApi.Entities.Maps.Directions.Response.Step

Is there any work round to get maneuver of step?
Or Can you let me know when you are going to implement it?

**Comment by vivet** [comment]
Hi
I can see Google recently added new properties in their response.
I will update accordingly, hopefully today or latest Wednesday.

Meanwhile you can use the RawJson property, which contains the raw response returned by Google. From that you can extract the missing part.

**Comment by vivet** [comment]
I have fixed the issue and published a new NuGet Package.
Please star the project if you like it :-)

**Comment by FalmaJeus** [comment]
Wow.. It works perfectly.
Thanks very much.
