### ISSUE TITLE
Add result_type parameter to Reverse Geocoding API Request

### ISSUE THREAD

**Issue by FalmaJeus** [vivet/GoogleApi#102]
Hello.
I want to get the street address of any coordinates.
Here is document about ReverseGeocoding.
https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding
As you can see, there are important parameters result_type and location_type.
With result_type specified for 'street_address', I think I can get exact street name.
I want you to add this parameter on request class.

Thanks in advance.
Best Regards.
Falma.

**Comment by vivet** [comment]
Hi

Just checked, and it seems to be missing as you said.
Will fix it

**Comment by vivet** [comment]
Off course. Will write here.
Expect it tomorrow or Friday 😃

**Comment by vivet** [comment]
Hi 
Short Update.
I have implemented a fix, and basically split the geocoding api into three separate methods: Address, Place and Location (reverse), to make the request less confusing, when setting either a string address, a location or a place id.

I am still missing to implement tests, and verifying the changes work. 
The former geocoding implementation is still available.

I still hope to  deploy today, but might be delayed to sometime during the weekend.

**Comment by vivet** [comment]
The issue is fixed, and new NuGet package published.

I don't have a premium key at the moment, so i couldn't fully test the feature. I get an error from google complaining that i don't have the premium key. I would expect to get different error if the request format was wrong, so I expect it to work.

Also, you need to use the new implementation of geocode, for example as shown below
```csharp
LocationGeocodeRequest request = new LocationGeocodeRequest();
GeocodeResponse response = await GoogleMaps.Geocode.Location.QueryAsync<LocationGeocodeRequest , LocationGeocodeRequest>(request);
```

Let me know if you have any issues.

**Comment by FalmaJeus** [comment]
Hello.
I have checked and thanks for your effort.
But it's always returning empty result.
raw json {
            "results" : [],
            "status" : "ZERO_RESULTS"
}
I have tried tests enough time with below code with many different locations.
            LocationGeocodeRequest request = new LocationGeocodeRequest();
            request.Key = ApiKey;
            request.Location = location;

            IList<PlaceLocationType> resultTypes = new List<PlaceLocationType>();
            resultTypes.Add(PlaceLocationType.Street_Address);
            resultTypes.Add(PlaceLocationType.Route);
            request.ResultTypes = resultTypes;

            IList<GeometryLocationType> locationTypes = new List<GeometryLocationType>();
            locationTypes.Add(GeometryLocationType.Range_Interpolated);
            request.LocationTypes = locationTypes;

            cts.Token.ThrowIfCancellationRequested();
            GeocodeResponse response = await GoogleMaps.LocationGeocode.QueryAsync(request);
            cts.Token.ThrowIfCancellationRequested();
I am sure that there is location information available for my place, because when I tried before with GeocodingRequest(3.4.2), it returned many results including Route(result type) and others.

Hope your response soon.
Thanks.

**Comment by vivet** [comment]
Hi

I have looked into the issue. Getting a ZERO_RESULTS response is a valid response, and I would suppose the location you are requesting gets filtered by the types you have specified. Trying without the types, will probably yield the result you expect. Try that. Furthermore, since I don't have a premium key at the moment, i cannot test this in detail myself. 

I checked the code, and noticed wrong casing for the result- and location-types, which i have now corrected in a new branch. Try that branch, and see if it works. Also if you can give me the rest of the request as well (it's missing the location your are requesting).

Let me know how it goes.

**Comment by vivet** [comment]
And by the way, if you want to do some live testing together, to get things working fast, then i am avialble all day today. Just write here and i will see.

**Comment by vivet** [comment]
Hi 

I did a bit more testing, and the implementation should be as expected by Google.

I get an error related to premium key: ```This functionality is only available if an API key or a client ID is provided: result_type```. If the request was malformed, i would get a 400 bad request.

I am not sure how else i can be of assistance, but let me know if I can do anything to make it work for you.

**Comment by vivet** [comment]
...also a new update is on the way to public NuGet Gallery.
So just update to latest, which will be 3.5

**Comment by FalmaJeus** [comment]
I have checked again if it really needs premium key.
But it doesn't.
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "277",
               "short_name" : "277",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Bedford Avenue",
               "short_name" : "Bedford Ave",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Williamsburg",
               "short_name" : "Williamsburg",
               "types" : [ "neighborhood", "political" ]
            },
            {
               "long_name" : "Brooklyn",
               "short_name" : "Brooklyn",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
            {
               "long_name" : "Kings County",
               "short_name" : "Kings County",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "New York",
               "short_name" : "NY",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "United States",
               "short_name" : "US",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "11211",
               "short_name" : "11211",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "277 Bedford Ave, Brooklyn, NY 11211, USA",
         "geometry" : {
            "location" : {
               "lat" : 40.7142205,
               "lng" : -73.9612903
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 40.71556948029149,
                  "lng" : -73.95994131970849
               },
               "southwest" : {
                  "lat" : 40.7128715197085,
                  "lng" : -73.9626392802915
               }
            }
         },
         "place_id" : "ChIJd8BlQ2BZwokRAFUEcm_qrcA",
         "types" : [ "street_address" ]
      }
   ],
   "status" : "OK"
}
This is what I got with request to '40.714224,-73.961452'.

**Comment by FalmaJeus** [comment]
As you can see it filtered the response.
for "types" : [ "street_address" ]

**Comment by vivet** [comment]
Thats the response you are showing, which includes types no matter the request.

...And yes it requires key and ClientId, read here
https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding

**Comment by vivet** [comment]
It says:

result_type — A filter of one or more address types, separated by a pipe (|). If the parameter contains multiple address types, the API returns all addresses that match any of the types. A note about processing: The result_type parameter does not restrict the search to the specified address type(s). Rather, the result_type acts as a post-search filter: the API fetches all results for the specified latlng, then discards those results that do not match the specified address type(s). **Note: This parameter is available only for requests that include an API key or a client ID.**

**Comment by vivet** [comment]
Ups...
I can actually see i was wrong, it says "or". Sorry about that.
I will update tests and fix if something isn't working still.

**Comment by vivet** [comment]
I have updated tests to include the api-key in tests, and I no longer get the exception about missing key. I also confirmed the functionality working, both types. 

I am not sure why it doesn't work as expected.

**Comment by vivet** [comment]
I think this line ```locationTypes.Add(GeometryLocationType.Range_Interpolated);``` is why you don't get any results. Change to rooftop or consider removing.

I have used geocoding many types, and never specified the types. Consider removing it altogether, as you might get unexpected results.
