### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by nothingmn** [vivet/GoogleApi#11]
I dont see a method to specificy, either globally or individually the google API key to use for each service.

Thanks.

**Comment by vivet** [comment]
Hi

There should be a property "Key" to set on the different requests.

Depending on the Google service and also on the subscription you have with
Google, this property is either used to hold the signed or unsigned key.
For signed requests the ClientId must be filled as well.

If you look at some of the test implementations they show this in detail.

Hope it solves you question.
