### ISSUE TITLE
Session Tokens

### ISSUE THREAD

**Issue by HornetBlack** [vivet/GoogleApi#110]
With the changes to billing coming up on July 16. Api's like Autocomplete have a "Session Token" https://developers.google.com/places/web-service/autocomplete#session_tokens

Currently I can extend `PlacesAutoCompleteRequest` to add a SessionToken property. 

So this would be the usage (very loosely based on my current usage).

```csharp
private string _apiKey;
// Google recommends a Type 4 uuid. 
private string _sessionToken = Guid.NewGuid().ToString();

public List<string> AutoComplete(string q) {
     var result = GooglePlaces.AutoComplete.Query(new PlacesAutoCompleteRequest {
        Key = _apiKey,
        SessionToken = _sessionToken.ToString();
        Input = q
    });
    // etc
}

public PlacesDetailsResponse Details(string placeId) {
    var result = GooglePlaces.Details.Query(new PlacesDetailsRequest {
        Key = _apiKey,
        SessionToken = _sessionToken.ToString();
        PlaceId = placeId;
    };
    // Reusing session Id's will cause billing to charge for the autocomplete requests.
    _sessionId = Guid.NewGuid().ToString();
}
```

Currently we're well below usage limits so it isn't urgent for my use case. Not sure about other users of this library though.

I'll make a PR if I get time, or if this becomes urgent.

**Comment by vivet** [comment]
Hi
I will implement it within a day or two

**Comment by vivet** [comment]
It's fixed.
I will publish NuGet package in a few hours.

**Comment by vivet** [comment]
I published to my private feed by accident, but the package should be available in 10 min from now

**Comment by vivet** [comment]
Hi
I consider the issue done and will close it.
Feel free to re-open should you experience any issues
