### ISSUE TITLE
SessionToken in Place Details Request

### ISSUE THREAD

**Issue by W3bCorp** [vivet/GoogleApi#120]
Hello,

Like ticket #110 , it is possible to specify the "sessiontoken" parameter on the Place Details request that follows the AutoComplete queries : 

https://developers.google.com/places/web-service/details

Can you add this parameter?

Thank you

**Comment by vivet** [comment]
It's implemented, and new NuGet Package has been published (v3.6.5).
Let me know if you have any issues.

Please star my library, if you like it.

**Comment by W3bCorp** [comment]
Ok, I will test as soon as possible. 

Thanks

**Comment by vivet** [comment]
Will close the issue. 
Just re-open if you experience issues.
