### ISSUE TITLE
Fields parameters in Place Request Details

### ISSUE THREAD

**Issue by W3bCorp** [vivet/GoogleApi#125]
Hello,

Thank you for your API which is really good.

For Place Details queries, is it possible to add the "fields" parameter (https://developers.google.com/places/web-service/details#fields) ?

I just realized that on billing my Google Cloud account, there were queries "Places API Contact Data" and "Places API Atmosphere Data". This is because when the "fields" parameter is not specified, Google returns all available data and the contacts and atmosphere data are billed additionally : 

> _Warning: If you do not specify at least one field with a request, or if you omit the fields parameter from a request, ALL possible fields will be returned, and you will be billed accordingly. This applies only to Place Details requests._

For my part, I need only the level "basic" and thus specify in the fields parameter values "address_component", "geometry", ....

Thank you

**Comment by vivet** [comment]
Hi
Just wanted to let you know that I am working on the implementation. It proved a bit more tricky, in order to make usage as seamless as possible. The update will contain the possibility to specify Basic, Contact or Atmosphere, as well as each individual top-level components. I chose not to add support for nested components for now, as I doubt it will be used. If you need that I will add it following this update.

I expect a NuGet update is ready tomorrow

**Comment by vivet** [comment]
Hi

Yes I made support for that. Basically you can now specify Basic, Contact and/or Atmosphere. Additionally you can specify each individual field as well, and any combination of any of them. The implementation uses a Flags Enum (https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Places/Details/Request/Enums/FieldTypes.cs)

The commit for the change is here: https://github.com/vivet/GoogleApi/commit/07ed8ebb79459d6ab7824324ea69507d31e31208

**Comment by vivet** [comment]
I will publish a new NuGet package later today

**Comment by vivet** [comment]
I published the package update

**Comment by W3bCorp** [comment]
Ok, thanks, i will test at end of the day.

**Comment by W3bCorp** [comment]
Hi,

Ok, for me, I will check my next bill and reopen if necessary.

Thanks !
