### ISSUE TITLE
PlacesTextSearchRequest doesn't implement IRequestQueryString

### ISSUE THREAD

**Issue by Swiftless** [vivet/GoogleApi#129]
Hi,

I'm not sure if this is correct or not, but I noticed PlacesTextSearchRequest is performing POST requests. 

This API is valid through a GET request (as verified via browser request) and implementing IRequestQueryString appears to switch this from the POST to a GET request. with no ill effects.

Thanks

**Comment by vivet** [comment]
Hi
It is in fact missing, I guess POST works as well for those enpoints. I will change to GET and deploy package update sometime later today

**Comment by vivet** [comment]
Will publish package when we resolve the other issue you created, unless it proves more difficult. So no later than tomorrow
