### ISSUE TITLE
Can't use RankBy.Distance

### ISSUE THREAD

**Issue by alowdon** [vivet/GoogleApi#13]
If you try to use `RankBy.Distance` when making a nearby places search, you are told that the radius must be specified. This goes against the Google documentation at https://developers.google.com/places/web-service/search, which states that radius should *not* be specified if the RankBy is changed. If you do set a radius, you get an `InvalidRequest` returned, presumably because the library is specifying both parameters.

**Comment by vivet** [comment]
Fixed but untested. 
I am a bit bust at the moment, so i wont be able to test it before within a few weeks.
Feel free to try the latest changes and let me know if you still have issues.

**Comment by vivet** [comment]
will build new nuget when i have confirmed it working.

**Comment by vivet** [comment]
Tested now

**Comment by vivet** [comment]
Did you try out the latest source?

**Comment by alowdon** [comment]
Hi @vivet, thanks for looking into this - unfortunately I haven't had chance to try the latest version as I have moved onto other work. If I have chance I will try to review it soon.

**Comment by vivet** [comment]
OK will close the issue and soon build a new nuget package.
