### ISSUE TITLE
DirectionsRequest bug in the TransitMode

### ISSUE THREAD

**Issue by joaofernandes95** [vivet/GoogleApi#130]
Hi there,
The API works really great but during my tests i've found that the transit mode is not correct during a request. For example, when i was building the request parameters i defined the TransitMode to `TransitMode.Subway | TransitMode.Bus`, expecting that i would get results for subway and bus.  I got results only for subway . I've tried your `ToEnumString` method to debug and i've conclued that it completly ignores the bus transit mode. I've attached an image to show the problem.

Can you please check the problem?
Thanks

![image](https://user-images.githubusercontent.com/15145044/45160735-12be8080-b1e2-11e8-9432-c673fa6cde1a.PNG)

**Comment by vivet** [comment]
Hi
It's nit the Extension method, but the enum value for Bus that is invalid.
I have fixed it and will deploy NuGet update. Should be ready in 15-20 min.

Please give my library a star if you like it :-)

**Comment by joaofernandes95** [comment]
Thank you very much!! 👍
