### ISSUE TITLE
Arrival time not working 

### ISSUE THREAD

**Issue by ikpl** [vivet/GoogleApi#132]
Hello, I'm testing out your api and have had some issues with the arrival time field for public Transit.  The arrival time for my request ends up being at 11:44 pm  when i entered an arrival time of 7:00 am
I've attached some code snippets.

Thanks!

![image](https://user-images.githubusercontent.com/44299737/47231220-2f250f80-d381-11e8-8832-156ff08a5ec1.png)

![image](https://user-images.githubusercontent.com/44299737/47231296-5da2ea80-d381-11e8-9c16-cbc81d4135ad.png)

**Comment by ikpl** [comment]
Oh it takes in time as a universal timestamp.

**Comment by vivet** [comment]
Hi
Have you tried checking the Google documentation?, cause it's a bit complex how this works. If I remember correctly, Google might or might not obey those parameters.

If you still have issues, paste the request as text, then I can reproduce it.

**Comment by vivet** [comment]
You do that need to worry about the timestamp, the api will take care of it

**Comment by ikpl** [comment]
Hi Michael thank you for getting back to me so quickly. I think it might
have something to do with converting between UTC and PST. When I passed the
time in as a UTC it gave the correct time.

-Isaiah

**Comment by vivet** [comment]
Hi
Yes, notice the property is of type datetime, meaning no timezone.
Did it fix your issue?

**Comment by vivet** [comment]
Ok good.
I updated the triple slash to more clearly indicate the UTC.

Please star my library if you like it.
