### ISSUE TITLE
Sample on ASP MVC

### ISSUE THREAD

**Issue by weedkiller** [vivet/GoogleApi#134]
Can you add a sample for best practises

**Comment by weedkiller** [comment]
I was asking if you provide a working ASP MVC web application sample with the views - UI. so it shows how the API are being consumed.

**Comment by vivet** [comment]
Hi
It's not really the purpose of the library.
Creating a ASP MVC web application, would just create another layer on top of Google's web application (the different api's), with no real benefit. 

What you need to do is create your own web application, and incorporate GoogleApi whenever you need to query for Google data. 

So lets say you have a controller action and you want to geocode a place based in lat/lng input to your action method. Simply do as follow:

```csharp
GeocodeResponse response = await GoogleApi.GoogleMaps.LocationGeocode
    .QueryAsync(new LocationGeocodeRequest 
    {
        // fill out request here.
    })

// do whatever you need with the response.
```

Hope it makes sense.

**Comment by vivet** [comment]
Hi
Did you figure out what you needed?
