### ISSUE TITLE
Regarding Google Place Search Example

### ISSUE THREAD

**Issue by jitendriyag2** [vivet/GoogleApi#138]
Hi Michael,

Could you please suggest how to use Google Place API in an search box as autocomplete option. It will be better if you give me some example code for the same.

Thanks in advance it is a nice thing you created all the google services are available at one place but won't be able to use though there is no example

**Comment by vivet** [comment]
Well the library isn't a web implementation.
But you need to use either autocomplete or query autocomplete API. So if you are building a web app yourself, you need to make and endpoint for you form submit having the code using the API I question.

**Comment by jitendriyag2** [comment]
No i need a sample xamarin form app which contain the map and place search example in Xamarin.Form Platform

**Comment by vivet** [comment]
Hi
I am not sure how to help with that, or at least not the xamarin part. But look at some of my test implementations, to see sample code. When someone enters a search input in you textbox you will need to invoke a function containing similar code as my tests.

https://github.com/vivet/GoogleApi/blob/master/.tests/GoogleApi.Test/Places/AutoComplete/AutoCompleteTests.cs

Make sense?

**Comment by vivet** [comment]
Hi

Will close the issue.
