### ISSUE TITLE
Paths add extra | at the end

### ISSUE THREAD

**Issue by CaseyBlackburn** [vivet/GoogleApi#139]
Paths (at least in my current usage of it in in Static Maps) add an extra | at the end that prevents the paths from being drawn. I'm assuming the API is expecting another location to be after it that causes it to error and not draw any of the paths.

**Comment by vivet** [comment]
Hi
Seems right, will fix soon.

**Comment by CaseyBlackburn** [comment]
In _GoogleApi\Entities\Maps\StaticMaps\Request\StaticMapsRequest.cs_ I added this line:

`LINE 186: points = points.Substring(0, points.Length-1);`

Seems to be a quick fix.

**Comment by vivet** [comment]
Yes, all the issues you created is easy fixes.
I expect an updated NuGet within a few days.

**Comment by vivet** [comment]
I have published update NuGet.
Will close the issue
