### ISSUE TITLE
MapColors end up capitalized

### ISSUE THREAD

**Issue by CaseyBlackburn** [vivet/GoogleApi#140]
MapColors return a color name that is capitalized (for example Purple) which does not get recognized by the api call. Needs to be all lower case. Would also like to use hex colors.

**Comment by vivet** [comment]
Will fix, and look into support for hex color values

**Comment by CaseyBlackburn** [comment]
In GoogleApi\Entities\Maps\StaticMaps\Request\StaticMapsRequest.cs I changed line 216 
from:
`var color = marker.Color.HasValue ? $"color:{marker.Color.ToString()|" : string.Empty;`
to:
`var color = marker.Color.HasValue ? $"color:{marker.Color.ToString().ToLower()}|" : string.Empty;`

Seems to be a quick fix.

**Comment by vivet** [comment]
I have published update NuGet.
Will close the issue
