### ISSUE TITLE
Markers not sending label

### ISSUE THREAD

**Issue by CaseyBlackburn** [vivet/GoogleApi#141]
The label setting for markers does not get sent in the request call, at least not in StaticMaps.

**Comment by vivet** [comment]
Will fix

**Comment by CaseyBlackburn** [comment]
In _GoogleApi\Entities\Maps\StaticMaps\Request\StaticMapsRequest.cs_ I changed line 213
from:
`var isLabel = string.IsNullOrEmpty(marker.Label) && !(marker.Size == MarkerSize.Tiny || marker.Size == MarkerSize.Small);`
to:
`var isLabel = !string.IsNullOrEmpty(marker.Label) && !(marker.Size == MarkerSize.Tiny || marker.Size == MarkerSize.Small);`

Seems to correct it.

**Comment by vivet** [comment]
I have published update NuGet.
Will close the issue
