### ISSUE TITLE
FEATURE REQUEST: User settable BaseURL for API calls

### ISSUE THREAD

**Issue by CaseyBlackburn** [vivet/GoogleApi#142]
I'd be interested if you could make the change to allow a user settable BaseURL for the different APIs. The reason I'm interested in this is I want to have requests sent to one of my web servers for caching to reduce duplicate API requests over time.

Thanks, really liking this project.

**Comment by vivet** [comment]
Hi

I am not sure i completely understand what you are trying to accomplish, (and I would to before adding the feature).

So basically you have a "mirror" of the Google service, and you want to try that before actually requesting at Google? If that's the case then I am pretty sure you would violate the terms of service of Google. It depends a bit on what kind of data you are caching, as it's different for each api. Here are some info: 
* https://cloud.google.com/maps-platform/terms/
* https://cloud.google.com/maps-platform/terms/maps-service-terms/

**Comment by vivet** [comment]
Hey I hope you figured out how to override the request class to accomplish your use case.

Let me know if you still need something from me.
Will close the issue.
