### ISSUE TITLE
Enum Value Incorrect

### ISSUE THREAD

**Issue by jamsoft** [vivet/GoogleApi#143]
[EnumMember(Value = "transit_station")] TrainStation,

This should serialise to "train_station"

Transit Station is a different type as per the documentation

https://developers.google.com/places/web-service/supported_types

**Comment by vivet** [comment]
Hi
Seems right, I will change.

**Comment by jamsoft** [comment]
Ahhhhh, I didn't expect that fix.

Why did you not keep transit_station? As an option?

If you are going to force the use of an enum you have to include all the possible options or the implementation is sort of broken.

Well done on the response time btw, nice work.

**Comment by vivet** [comment]
Hi
Hi
Sorry, didn't check that transit_ststion was actually missing, but just fixed the wrong enum member value. 
Will add the missing transit_station.

**Comment by jamsoft** [comment]
I just tested the TrainStation enum for type and all is working as expected.

**Comment by vivet** [comment]
Hi
The "Transit Station" has been added properly now.
Let me know if you have further issues.

**Comment by jamsoft** [comment]
Checked and it all looks good. Thank you.
