### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by jamsoft** [vivet/GoogleApi#146]
It seems there is some missing data in the NearbyResult class.

Things like Phone numbers, not sure if there are others missing at the moment.

**Comment by vivet** [comment]
Hi :-)
Could you be more specific. I don't see phone number in Google's documentation, but sometimes could omits stuff, so if its something you have seen in a response, paste the response here, and i will add.

**Comment by vivet** [comment]
Is the issue still relevant?
