### ISSUE TITLE
Inject HttpMessageHandler/HttpClient

### ISSUE THREAD

**Issue by jimborogers** [vivet/GoogleApi#147]
Hi there,

Do you have any plans to make it possible to inject the HttpMessageHandler/HttpClient?

I would like to use this library as part of a Blazor app, which currently requires the use of BrowserHttpMessageHandler in any HttpClient instances.

Thanks.

**Comment by vivet** [comment]
Hi
I could add it, just need to make sure to understand what you need.
You would like to control the instance of ```HttpClient``` and be able to inject that into the GoogleApi facade?

**Comment by vivet** [comment]
I will look at it, but i am not 100% sure its possible.
The problem is that the Facade implementation uses static instances of ```HttpEngine```, which prevents the normal constructor injection. This is done in order to optimize usages of ```HttpClient```, and avoid creating a new client on every request.  So i am not sure it's the best approach.

It confuses me a bit that you are required to inject the ```HttpClient```. Do you have a link or something documenting this, cause I can't find it.

**Comment by jimborogers** [comment]
Here is an intro to HttpClient and Blazor: https://visualstudiomagazine.com/articles/2018/09/07/blazor-apis.aspx

Although I've realised that, as Blazor runs clientside and Google Places API does not support CORS, it's not actually possible to make Google Places API requests from a Blazor app without using some kind of proxy.

It's still worth exposing the HttpClient instance to be injected, but given the effort required due to the current architecture, I understand if you consider this feature request low priority.

**Comment by vivet** [comment]
Hi 
This library is server side library, and you would need to make you own endpoint using the library to further query Google. If you just need to use Google raw then use their JavaScript api's. Using the serverside is meant for the use cases where you want to apply your own business logic after invoking Google, or combine several calls.

I have previous thought about and also looked into having the HttpClient being injected. As you mentioned yourself, it's not that easy. The reason for the current architecture is to avoid the nasty issue HttpClient has, if using the normal disposable pattern. Also, I have previous failed to find a use case where the caller actually need to do anything with the HttpClient that GoogleApi uses.

**Comment by vivet** [comment]
I will see what I can do. Maybe I see a way. It might take a week or two.

Please star my library if you like it 😃

**Comment by jimborogers** [comment]
Thanks. I've already got the project starred. :)

**Comment by vivet** [comment]
Cool thanks.
I will post when I have an update

**Comment by vivet** [comment]
Hi

I have considered implementing this, but came to the conclusion that leveraging access to the HttpClient, would be dangerous. You should be able to inject the GoogleApi directly instead of HttpClient.
