### ISSUE TITLE
Persistent error

### ISSUE THREAD

**Issue by ikpl** [vivet/GoogleApi#148]
Hello!

I keep getting an exception thrown on some of my transit requests.  The requests are being run in parallel, and there can be up to ~80 requests running at a time. What puzzles me most is that the exceptions seems be getting thrown when assigning an arrival time to the directions request. Any advice or assistance you have would be greatly appreciated.

Thanks, 
-IK

GoogleApi.Exceptions.GoogleApiException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GoogleApi.HttpEngine`2.ProcessRequest(TRequest request)
   at GoogleApi.HttpEngine`2.Query(TRequest request)
   --- End of inner exception stack trace ---
   at GoogleApi.HttpEngine`2.Query(TRequest request)
   at Individualized_Trip_Plan_Tool.GoogleApiTest.transit_time(String origin, String destination, DateTime arrival_time_local) in C:\Users\...\GoogleApiTest.cs:line 183

arrival_time_local = 3/6/2019 6:30:00 AM

174        public int transit_time(string origin, string destination, DateTime arrival_time_local)
175        {
176            try
177            {
178                DirectionsRequest request = new DirectionsRequest();
179               request.Key = apiKey;
180                request.Origin = new Location(origin);
181                request.Destination = new Location(destination);
182                request.TravelMode = TravelMode.Transit;
183                request.ArrivalTime = arrival_time_local;

**Comment by vivet** [comment]
Somehow you application isn't handling the threads correctly.
Notice that the HttpClient is a Singleton.
Are you running this in a test suite?

**Comment by vivet** [comment]
Could be if you are using the same request in the parallel calls.

**Comment by ikpl** [comment]
Hi Michael,

I think I am creating a new request for each thread since I create the
thread before creating a new directionrequest object. That said, I don't
entirely understand how a singleton httpclient works.

Thanks!
Isaiah

**Comment by vivet** [comment]
Try reading more about thread safety, and also read about the rest runner if it's in test it happens.
I suspect the error happens at random threads, aka iterations / executions?

**Comment by vivet** [comment]
It doesn't seem like an issue with this library at least
