### ISSUE TITLE
Geocode PostalCode doesn't resolve to "postal_code" when requesting

### ISSUE THREAD

**Issue by dotnetshadow** [vivet/GoogleApi#149]
Hi there,

I noticed an issue when trying to GeodeRequest with component restriction:

```c#
// Request
            var request = new AddressGeocodeRequest
            {
                Key = GoogleApiKey,
                Address = address.Replace(",", string.Empty),
                Components = new[]
                {                    
                    new KeyValuePair<Component, string>(Component.Locality, 3000),
                    new KeyValuePair<Component, string>(Component.PostalCode, "Melbourne"),                    
                }
            };

var result = await GoogleMaps.AddressGeocode.QueryAsync(request);
```

When I look at the request url it comes out as
`
https://maps.google.com/maps/api/geocode/json?key=<key>&address=<enter some address>5&components=postalcode:3055|locality:Melbourne
`

Notice the parameter **postalcode** it should be **postal_code**
The results vary greatly if it's not correct

Is there also a way of modify the Url before the request is sent out?

**Comment by vivet** [comment]
Hi
I will make a fix today.
The only way to change the URL is by creating your own request implementation.

**Comment by vivet** [comment]
Its fixed, and updated NuGet package should be available in 5-10 min.

**Comment by dotnetshadow** [comment]
Thank you so much for your prompt response, I will test this out on the weekend. Much appreciated

**Comment by vivet** [comment]
Will close the issue.
Let me know if you are having issues with the change.
