### ISSUE TITLE
Error in DirectionsResponse serialization

### ISSUE THREAD

**Issue by RebelionTheGrey** [vivet/GoogleApi#153]
Hello. I use ASP.NET Core 2.2.2 + Newtonsoft.Json in my backend.
So, when I tried to serialize DirectionsResponse class via this code, 

            var directionRequest = new DirectionsRequest()
            {
                Key = ".................................................................................",
                TravelMode = TravelMode.Driving,
                Avoid = AvoidWay.Tolls,
                Units = Units.Metric,
                Alternatives = false,
                Language = GoogleApi.Entities.Common.Enums.Language.Russian,
                Origin = model.Points.FirstOrDefault(), //originLocation,
                Destination = model.Points.LastOrDefault(), //destinationLocation,
                Waypoints = model.Points.Skip(1).Take(model.Points.Count - 2).ToArray(),
                DepartureTime = DateTime.Now,
            };

            var result = await GoogleMaps.Directions.QueryAsync(directionRequest);
            return Ok(result);

I'd got an error like this:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLKVTI0UPNMB", Request id "0HLKVTI0UPNMB:00000029": An unh
andled exception was thrown by the application.
Newtonsoft.Json.JsonSerializationException: A member with the name 'points' alre
ady exists on 'GoogleApi.Entities.Maps.Directions.Response.OverviewPolyline'. Us
e the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonPrope
rty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Typ
e type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract
(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type
objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Fu
nc`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculateProper
tyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonPr
operty member, JsonProperty property, JsonContract& memberContract, Object& memb
erValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject
(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty memb
er, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(J
sonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty m
ember, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject
(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty memb
er, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(J
sonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty m
ember, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject
(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty memb
er, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(J
sonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty m
ember, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject
(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty memb
er, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonW
riter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Ob
ject value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object val
ue)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteRes
ponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(
IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFi
lterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExec
utedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter
,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilter
s()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResource
Filter()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceEx
ecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next,
Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipeli
neAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpCon
text)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext
httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Proces

**Comment by vivet** [comment]
Hi
I will fix it, probably tomorrow

**Comment by RebelionTheGrey** [comment]
Thank you much!

**Comment by vivet** [comment]
Hi
I have fixed the issue. Package should be ready shortly.
Please give my library a star, if you like it.

Have a nice day.

**Comment by RebelionTheGrey** [comment]
Yes, I've already starred it! Great project, thanks a lot!! 

Nice day too!))

**Comment by vivet** [comment]
Ok thanks.
Can I close the issue?

**Comment by RebelionTheGrey** [comment]
Yes, sure, thank you!! Sorry for my late answer.
