### ISSUE TITLE
global handling of API key

### ISSUE THREAD

**Issue by black-snake** [vivet/GoogleApi#155]
Hey,

first of all, great job there and thanks for sharing the library with the public.

I'm currently looking into it and I was wondering if or how I can globally handle the `key` property, meaning that I don't have to specify the property in every request.

So far, my approach was to have a little helper function that dispatches every request (see below).
```cs
public class GoogleMaps
{
        private readonly string _apiKey = string.Empty;

        private async Task<TResponse> IssueRequestAsync<TRequest, TResponse>(
            TRequest request,
            HttpEngine<TRequest, TResponse> httpEngine,
            CancellationToken cancellationToken = default(CancellationToken))
            where TRequest : IRequest, new()
            where TResponse : IResponse, new()
        {
            request.Key = _apiKey;

            var response = await httpEngine.QueryAsync(request, cancellationToken);

            // TODO: handle next page token!

            return response;
        }
}
```

But is there some other (simpler) approach to it?

At first I thought about sub-classing `HttpEngine` or `HttpEngine<,>`, respectively. But since these classes are sealed, I couldn't do so.

**Comment by vivet** [comment]
Hi
Glad you like the library :-)

There are several possible ways you can archive this. 
Simplest i can think of, is making a generic method returning the request with the global properties set. Everytime you need a request you can call that, followed by adding the non-global properties to request.

Though, it's not something I think the GoogleApi should be responsible for, so it's outside the scope of this project.

**Comment by black-snake** [comment]
Of course, you're right. Sometimes one complicates things although there is a simple solution. I ended up with a simple factory:

```cs
using GoogleApi.Entities.Interfaces;

internal static class RequestFactory
{
    private const string _apiKey = string.Empty;

    internal static T GetRequestObject<T>() where T : IRequest, new()
    {
        var obj = new T
        {
            Key = _apiKey
        };

        return obj;
    }
}
```
