### ISSUE TITLE
Find place search bounding box coordinates reversed

### ISSUE THREAD

**Issue by skahigh** [vivet/GoogleApi#156]
Thank you for this project, it's very useful!  Having never raised an issue on an open-source project before I apologise if I approach this incorrectly.

I have found an issue I believe with the find places request format.

According to the google api docs a location bias rectangle option for this request should take the format 'rectangle:south,west|north,east'.

https://developers.google.com/places/web-service/search

> Rectangular: A string specifying two lat/lng pairs in decimal degrees, representing the south/west and north/east points of a rectangle. Use the following format:
rectangle:south,west|north,east. Note that east/west values are wrapped to the range -180, 180, and north/south values are clamped to the range -90, 90.

Line 103 of the request class for this api appears to have the coordinate values the wrong way round:

https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Places/Search/Find/Request/PlacesFindSearchRequest.cs

`parameters.Add("locationbias", $"rectangle:{this.Bounds.NorthEast}|{this.Bounds.SouthWest}");`

**Comment by vivet** [comment]
Hi
Your report is excellent, better than most 😃
I will fix, tomorrow

**Comment by vivet** [comment]
Sorry had a very busy day, so I didn't get to fix the issue. Will fix in the weekend.

**Comment by vivet** [comment]
I have fixed the issue and published a new NuGet pacakge.
Please star my library if you like it :-)

...and let me know if you have further issues.

**Comment by skahigh** [comment]
Thanks very much! :)
