### ISSUE TITLE
GoogleApi.Entities.Common.Location protected default constructor

### ISSUE THREAD

**Issue by RebelionTheGrey** [vivet/GoogleApi#158]
Hello.

I use your library in my WebAPI. So, for mapping views in API Controllers I need to have public default constructor of each class I pass through the API method call for correct automatic model binding. 
Also, It's hard to use classes like this with Automapper, because it also needs to have public default constructor in simpliest case instead of "ConstructUsing" usage.
Why did you protect default constructor here? Is is possible to make it public for Location (and, maybe, other base classes here)? 

Thank you!

**Comment by vivet** [comment]
Hi 
I will add a public parameterless constructor to Location. I will check if there are other missing default constructors.

**Comment by vivet** [comment]
It's resolved, and NuGet published.
Please star my library if you like it :-)
Let me know if you have other issues.

**Comment by vivet** [comment]
Hey, did you try the update?

**Comment by RebelionTheGrey** [comment]
Hello!!

Sorry, was busy in this vacations.((( Sure I've done. ))) It works fine!!
And I've already starred and followed your cool project!))) Thank you!
Issue could be closed!

**Comment by vivet** [comment]
Ok cool
