### ISSUE TITLE
Is it cross platform

### ISSUE THREAD

**Issue by franva** [vivet/GoogleApi#160]
Just wonder whether this can be used in .Net Core 2.2?

On it's GitHub, it says for .NET Core, BUT when I try to install it from the NuGet Package Manager, I saw it has dependency on .NetFramework v4.5. 

![image](https://user-images.githubusercontent.com/5151146/56146323-5e8f9e80-5fe9-11e9-8f85-c5a8a7f59fc0.png)

As .NetFramework isn't cross platform ,does it mean this NuGet Package won't be running properly on Linux ?

**Comment by vivet** [comment]
Yes I can be used with net core.
The package supports either the old .net framework OR net standard 1.1, which is the library .net specification and equvelence net core 1.0 or higher.

Microsoft has a page where you can see the comparison.
Makes sense?

**Comment by franva** [comment]
thanks, it makes sense :) can be closed.
