### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by 0Neji** [vivet/GoogleApi#164]
Hi,

We're looking to move our autocomplete from being called client side to server side. We're currently using the Autocomplete API with sessions and looking at this library as an option.

I just wanted to check whether the session stuff has been tested and is working for billing purposes and the SDK doesn't actually end up using requests rather than sessions. I've seen that sessions are supported in the code but I wasn't clear if this has been 100% tested and confirmed that sessions are being sent.

Could you confirm for me one way or the other whether this is the case or not?

Thanks,

Ben

**Comment by CaseyBlackburn** [comment]
I personally have not had any issues with billing, it reports the session
info.

**Comment by vivet** [comment]
Hi 
I haven't used it myself, but it should work. Someone tested a while back.
Try it out and let me know if you have any issues, and I will fix them

**Comment by vivet** [comment]
Can this issue be closed?

**Comment by 0Neji** [comment]
Thanks for responses both, we're currently making a decision whether to move forward with this so will close for now. Appreciate the quick replies!

**Comment by vivet** [comment]
Cool

Please star my library if you like it 😃
