### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by HaiyanDu7** [vivet/GoogleApi#168]
Can you update your .net core sdk to latest version? I got this compile issue.

The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

![image](https://user-images.githubusercontent.com/3611550/63546670-53e59880-c4f8-11e9-9ef4-7d43118ca7bc.png)

**Comment by vivet** [comment]
Hi
I am not entirely sure what you want me to do. The sdk is net core 2.2 for the test projects. So it's seems you are missing that on your machine, or maybe I misunderstood something. All 3 projects build fine on my machine

**Comment by vivet** [comment]
Download from here: https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by vivet** [comment]
Were you able to make it work?
