### ISSUE TITLE
Unsupported field name 'alt_id'

### ISSUE THREAD

**Issue by facu-larocca-zenfolio** [vivet/GoogleApi#169]
Since today, I am getting an error response from GoogleApi using the latest 3.9.1.
The error states: 

> Error while parsing 'fields' parameter: Unsupported field name 'alt_id'. 

This is the code:
```
public async Task<PlaceDetailsDto> GetPlaceDetailsAsync(string placeId)
{
    PlaceDetailsDto result = null;
    try
    {
        var request = new PlacesDetailsRequest
        {
            Key = <<-- API KEY -->>,
            PlaceId = placeId
        };
        PlacesDetailsResponse response = await GooglePlaces.Details.QueryAsync(request);
        
        // mapping code here
    }
    catch (GoogleApiException ex)
    {
        // Exception here
    }
    return result;
}
```

Apparently, the default request is asking for `alt_id` field that is not supported any more.
Indeed, I fixed it removing that field from the field list:
```
request.Fields &= FieldTypes.Alt_Id
```

**Comment by vivet** [comment]
Seems google removed that as well 'Scope'. I will remove them. 

Have you noticed anything different in the response. I am thinking if those fields matching those types, are now omitted in the response as well?

**Comment by vivet** [comment]
Its fixed. You can check out the PR, and let me know. I can publish afterwards.

**Comment by facu-larocca-zenfolio** [comment]
Yes, seems to be correct.
Thanks @vivet !!!

**Comment by vivet** [comment]
The PR is merged, and NuGet published.
Please give my library a star if you like. 

Have a nice day.

**Comment by vivet** [comment]
Will close the issue. 
Let me know if you have any other issues.
