### ISSUE TITLE
PlacesDetailsRequest 

### ISSUE THREAD

**Issue by NickStavrou-Net** [vivet/GoogleApi#171]
I have a question about using Enum.Fields
I am making this request:
```
var detailsResponse = await GooglePlaces.Details.QueryAsync(new PlacesDetailsRequest
            {
                Key = GoogleApiKey,
                PlaceId = placeId,
                  //Fields = [FieldTypes.Formatted_Address, FieldTypes.International_Phone_Number, FieldTypes.Website],
            });
```

I am trying to access these fields but they return null for a reason i understand that the Fields are set to:
`public virtual FieldTypes Fields { get; set; } = FieldTypes.Basic;`
is it possible to change the FieldType?

when i make the call by doing this:
```
var detailsResult = detailsResponse.Result; 
airportDetail.PhoneNumber = detailsResult.InternationalPhoneNumber;
airportDetail.Website = detailsResult.Website;
```
these are null.
how can i access them by the way i comment them in the detailsResponse above?

**Comment by vivet** [comment]
Yes you can change the default på assigning the property.
There can many reasons why the properties are null, for example it depends on the places api pricing level (if I remember correctly), and whether google has the data.

Try check the response.RawJson to see the raw data returned by google.

I suggest using one of the fieldtype "categories", and try consult the places api developer docs

**Comment by NickStavrou-Net** [comment]
with the call i make the response.RawJson doesn't include any of the values i want
 only if by explicit adding them with Fields but it accept only one FieldType.
In places api documentation code goes like this:
```
var request = {
          placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
          fields: ['name', 'formatted_address', 'place_id', 'geometry']
        };
```
i will try to change the property value to
FieldTypes.Contact as you said

**Comment by vivet** [comment]
You can specify more than one fieldtype. Use bitwise or

**Comment by NickStavrou-Net** [comment]
> You can specify more than one fieldtype. Use bitwise or

bitwise or???
never done anything like that.
i will do a research about it.

**Comment by vivet** [comment]
Use | between each if the values in the enum you want

**Comment by NickStavrou-Net** [comment]
> Use | between each if the values in the enum you want

Thank you a million times...It worked

**Comment by vivet** [comment]
You are welcome.

Please give the library a star if you like it 😃

**Comment by josephbales** [comment]
> Use | between each if the values in the enum you want

Might be worth adding this to the readme as it may not be obvious to the average user.
