### ISSUE TITLE
distance calculation based on placeid

### ISSUE THREAD

**Issue by flopez2904** [vivet/GoogleApi#172]
Is it possible to calculate distances based on placeid?
            
           var request = new DistanceMatrixRequest
            {
                Key = this.ApiKey,
                Origins = new[] { new Location(<PLACEID_ORIGIN>) },
                Destinations = new[] { new Location(<PLACEID_DESTINATION>) }
            };
            var response = GoogleMaps.DistanceMatrix.Query(request);

**Comment by vivet** [comment]
OriginsRaw and DestinationsRaw should support that. That is if the google API actually supports it, which it does as far as I recall.

**Comment by flopez2904** [comment]
I try this:

            var request = new DistanceMatrixRequest
            {
                Key = this.ApiKey,   
                OriginsRaw = "placeId:" + placeIdO,
                DestinationsRaw = "placeId:" + placeIdD,
                Language = GoogleApi.Entities.Common.Enums.Language.Spanish,
                TravelMode = GoogleApi.Entities.Maps.Common.Enums.TravelMode.Driving,
                Units = GoogleApi.Entities.Maps.Common.Enums.Units.Metric
            };

            var response = await GoogleMaps.DistanceMatrix.QueryAsync(request);

But dont work.

any ideas?

**Comment by vivet** [comment]
Are you following the google docs? Maybe it's not possible

**Comment by vivet** [comment]
Did you manage to figure it out?

**Comment by xferra** [comment]
@flopez2904 Just use proper prefix (**place_id**):

```csharp
        var request = new DistanceMatrixRequest
        {
            Key = this.ApiKey,   
            OriginsRaw = "place_id:" + placeIdO,
            DestinationsRaw = "place_id:" + placeIdD,
            Language = GoogleApi.Entities.Common.Enums.Language.Spanish,
            TravelMode = GoogleApi.Entities.Maps.Common.Enums.TravelMode.Driving,
            Units = GoogleApi.Entities.Maps.Common.Enums.Units.Metric
        };
```
