### ISSUE TITLE
May you awnser me please.

### ISSUE THREAD

**Issue by Kunanonn** [vivet/GoogleApi#174]
TResponse response = await {Api}.{Action}.QueryAsync<TRequest, TResponse>(request);
I don't understand what {Action} is it.
I code this statment
`DistanceMatrixResponse response = await GoogleMaps.DistanceMatrix.QueryAsync<DistanceMatrixRequest, DistanceMatrixResponse>(req);`
and have Error The non-generic method.
Thank you.

**Comment by vivet** [comment]
Do you have the fill the exception

**Comment by vivet** [comment]
Or is it compile time error?

**Comment by Kunanonn** [comment]
This is full exception

The non-generic method 'HttpEngine<DistanceMatrixRequest, DistanceMatrixResponse>.QueryAsync(DistanceMatrixRequest, CancellationToken)' cannot be used with type arguments

**Comment by vivet** [comment]
I see. The readme is wrong. Sorry
Just do
`var response = await GoogleMaps.DistanceMatrix.QueryAsync(request);`

**Comment by Kunanonn** [comment]
Thank you so much.

**Comment by vivet** [comment]
Np
Please star my library if you like it.
