### ISSUE TITLE
Avoiding Google limitations for Directions/DistanceMatrix/etc. 

### ISSUE THREAD

**Issue by GoNextGroup** [vivet/GoogleApi#182]
Hello.

Google has limitations of API usage for points count: 10 waypoints for Directions API, 100 elements for DistanceMatrix API (10 x 10 waypoints). 
So, if I want to get request more that 100 elements for waypoints, I need to divide elements for 10x10 waypoints submatrices and call it independently. But there is no clear mechanism to concatenate submatrices in DistanceMatrixResponse, for example. 
So, could you add this mechanism for all types of responses or realize it internally?
Thank you.

**Comment by vivet** [comment]
I am currently on vacation, back on the 27th of Jan.
Though what you want doesn't seem like something I would implement, as I would have to do more requests under the hood, than the caller would know, leading to additional costs.

**Comment by GoNextGroup** [comment]
Ah, sure, nevermind. I'll write my own extension which will divide each request.
