### ISSUE TITLE
Missing Search Types for Places NearbySearch 

### ISSUE THREAD

**Issue by Richard014** [vivet/GoogleApi#186]
The types of table 2 and table 3 are missing. 
Examples: locality, administrative_area_level_1, ...

And some types of table 1 are missing:
secondary_school, primary_school, ...

https://developers.google.com/places/web-service/supported_types

**Comment by vivet** [comment]
The types that you can search for and the types returned with details are different. Basically, it's not all types you can specify in the request for nearby. Are you aware of that?

**Comment by Richard014** [comment]
Yes, sorry. You are right. The types of table 2 and 3 are just for autocomplete.
But the types secondary_school and primary_school should be added. 

(offtopic: i am just trying to get the nearest city, but i think thats not possible)

**Comment by vivet** [comment]
I will add those 2 missing types

**Comment by vivet** [comment]
I have added them and published updated NuGet Package.
Please star my library if you like it :-)

**Comment by Richard014** [comment]
Thanks, i did ;)
