### ISSUE TITLE
Using proxy for web requests

### ISSUE THREAD

**Issue by AmadKowal** [vivet/GoogleApi#188]
Is there any possibility to configure HttpEngine to use proxy while sending requests to Google API?
If no, could it be added to code or i need to get code of this project and implement it by myself?

**Comment by vivet** [comment]
Hi
I guess could make it possible, by adding a static IWebProxy property to the HttpEngine class, and by setting that before invoking Google methods, it could work. Though I am a bit busy at the moment, so if you could make a PR, which I could use, at least for inspiration.

**Comment by AmadKowal** [comment]
Hello,
I was kinda busy at the weekend as well.
I'm just created pull request: https://github.com/vivet/GoogleApi/pull/189
It looks like pretty simple change. Please check if i didn't miss anything.

**Comment by vivet** [comment]
Looks similar to what I would have done. Have you confirmed it working as expected?

**Comment by AmadKowal** [comment]
Yes, it is working as expected with that change.

**Comment by vivet** [comment]
Okay, will merge one of the coming days

**Comment by vivet** [comment]
Its merged, and NuGet published

**Comment by AmadKowal** [comment]
Thanks!
