### ISSUE TITLE
Make AddressGeocodeRequest.Address value optional

### ISSUE THREAD

**Issue by misiek-it** [vivet/GoogleApi#191]
Hello Michael,
Currently validation does not allow to issue request if the Address value is missing (GoogleApiException: Address is required). But according to [google documentation](https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering) Address parameter should not be provided when is's been already provided in components collection (i.e. as locality value). I would like put the search value in component.locality value only as it will make the search disregard matching company names and such (focusing on city and street names).

Excerpt from documentation:
`https://maps.googleapis.com/maps/api/geocode/json?components=locality:santa+cruz|country:ES
&key=YOUR_API_KEY`

Please relax the validation or adjust it accordingly.
BR

**Comment by vivet** [comment]
I will take a look at it

**Comment by vivet** [comment]
I have fixed the issue 
https://github.com/vivet/GoogleApi/pull/192

Take a look, and I will merge and deploy new Nuget later today (or tomorrow).

**Comment by vivet** [comment]
I have merged the PR. Let me know if you have any issues now.
Please give my library a star if you like it.

**Comment by misiek-it** [comment]
Sorry for late feedback. Thank you for addressing the issue, it works now as expected. Although I haven't yet noticed any improvements in search results with this "components collection only" approach. Oh well, just google things I guess.
