### ISSUE TITLE
google.maps.places.PlaceSearchRequest Bounds property

### ISSUE THREAD

**Issue by newslacker** [vivet/GoogleApi#193]
Any plans to add this property for the places nearby search?

bounds: LatLngBounds|LatLngBoundsLiteral 

https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceSearchRequest

**Comment by vivet** [comment]
Hi
You are pointing to the JavaScript docs.

**Comment by newslacker** [comment]
I see they don't have feature parity. Switched to TextSearch from NearBySearh and it works a little better. Thank you.
