### ISSUE TITLE
permanently_closed has been deprecated

### ISSUE THREAD

**Issue by r-barron** [vivet/GoogleApi#195]
Looks like Google has deprecated the _permanently_closed_ field from their Google Places API:

https://developers.google.com/places/web-service/place-data-fields

In a recent email Google stated that within a year the inclusion of it in requests will trigger an error:

> As a result, starting on May 26, 2021, the Places API and the Places Library, Maps Javascript API will **stop accepting** the permanently_closed property in the fields parameter in Place Details and Find Place, and **stop returning it in the response** to Place Details, Find Place, Nearby Search and Text Search requests.

> **Instead, developers will receive the ‘Unsupported field name’ error** when using this property in the fields parameter in Place Details and Find Place of the Places API and Places Library, Maps Javascript API, and the value `undefined` when reading this property from the PlaceResult object returned by Place Details, Find Place, Nearby Search and Text Search requests of the Places Library, Maps Javascript API.

In its place there is a new _business_status_ field:

> The property has been replaced by the property business_status with values {OPERATIONAL, CLOSED_TEMPORARILY,CLOSED_PERMANENTLY}, which is returned in response to Place Details, Find Place, Nearby Search and Text Search requests.

Is there a plan in place to remove this and replace it with business_status?

**Comment by vivet** [comment]
Yes I noticed. I will update.

**Comment by vivet** [comment]
I have published updated NuGet package.
Please star the library if you like it.

**Comment by r-barron** [comment]
Seems to work great.  Thanks for the quick response!
