### ISSUE TITLE
Search Distance Matrix API by postcode/place name

### ISSUE THREAD

**Issue by Blundell89** [vivet/GoogleApi#2]
Hi,

We're looking to use the Distance Matrix API and come across your wrapper (which looks really useful, thanks!).

The `DistanceMatrixRequest` has the `Origins` and `Destinations` properties that both take an `IEnumerable<Location>`. The `Location` class currently has one constructor that takes a lat and long. Would it be possible to take a second constructor where we can pass an address string instead? The documentation indicates that this is an acceptable request.

If you're happy for the change to be implemented I could clone and PR it?

Thanks,

Lee & @dingwall

**Comment by vivet** [comment]
Hi

Feel free to make a PR and i will merge it.

On Sat, Apr 16, 2016 at 5:34 PM, Lee Blundell <notifications@github.com>
wrote:

> Hi,
>
> We're looking to use the Distance Matrix API and come across your wrapper
> (which looks really useful, thanks!).
>
> The DistanceMatrixRequest has the Origins and Destinations properties
> that both take an IEnumerable<Location>. The Location class currently has
> one constructor that takes a lat and long. Would it be possible to take a
> second constructor where we can pass an address string instead? The
> documentation indicates that this is an acceptable request.
>
> If you're happy for the change to be implemented I could clone and PR it?
>
> Thanks,
>
> Lee & @dingwall <https://github.com/dingwall>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vivet/GoogleApi/issues/2>
>



-- 

MICHAEL VIVET
VP Product & Development

Mobile: +45 30 86 45 25
Email: mv@drivr.com
Address: Jagtvej 111, DK-2200 København N

*https://*drivr.com <http://www.drivr.com/>
*https://*facebook.com/drivrhq
*https://twitter.com/drivr <https://twitter.com/drivr>*

**Comment by vivet** [comment]
I have merged and uploaded new nuget package

**Comment by Blundell89** [comment]
That's great, thanks! :smile:
