### ISSUE TITLE
Guide to getting started

### ISSUE THREAD

**Issue by lukehold** [vivet/GoogleApi#203]
Hi,

Is there a way to get location address back by providing coordinates? The geolocation feature seems geared towards mobile data, rather than coordinates.

Thanks,
Luke

**Comment by vivet** [comment]
You need to use reverse geocoding. Maps api

**Comment by lukehold** [comment]
Is there a list somewhere of all the request and response objects in the package? I've looked for geocode, or reverse, and can't find anything similar.

**Comment by vivet** [comment]
This one
https://github.com/vivet/GoogleApi/blob/master/GoogleApi/GoogleMaps.cs#L62

**Comment by vivet** [comment]
Here is a test that shows a full example
https://github.com/vivet/GoogleApi/blob/master/.tests/GoogleApi.Test/Maps/Geocoding/Location/LocationGeocodeTests.cs#L17

**Comment by lukehold** [comment]
Thanks, that's enough to get me going. Cheers.

**Comment by frozenprakash** [comment]
but this has a 100 search / day limit,
how to bypass that or any free way to achieve google search ?

**Comment by CaseyBlackburn** [comment]
@frozenprakash That is beyond the scope of this project.
