### ISSUE TITLE
RequestDenied: You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

### ISSUE THREAD

**Issue by Bardo-Konrad** [vivet/GoogleApi#206]
Don't use it. Use osm, which has a free api instead.

**Comment by vivet** [comment]
Well someone is mad at Google I see.
No reason to embarrass you send with such post.

**Comment by Bardo-Konrad** [comment]
You are right. it is actually embarrassing to not mention that right from the start.
