### ISSUE TITLE
Async calls don't work if running under asp.net

### ISSUE THREAD

**Issue by sbrink75** [vivet/GoogleApi#207]
I'm getting deadlocks when running a service hosted in IIS when making several GetAsync calls in multiple threads.  [This](https://stackoverflow.com/questions/10343632/httpclient-getasync-never-returns-when-using-await-async/10351400#10351400) stackoverflow answer explains why and the solution for it.  Each await call should have a ConfigureAwait(false)

**Comment by vivet** [comment]
Hi
I took a brief look at it, and your are right.
The post you linked is somewhat old, but seems it still applies. I found a blog post, which explains things a bit more detailed.  https://devblogs.microsoft.com/dotnet/configureawait-faq/

I will take a look tomorrow at your PR, and release an update.
Thanks for reporting the issue.

**Comment by sbrink75** [comment]
Hi,

                Thanks for taking a look at it, we were using a really old version of the API (3.2.10) and when I upgraded to the latest this started happening.

Regards,

                Sean

**Comment by vivet** [comment]
Hi
I have merged your PR, and published an updated NuGet package, v3.1.15

**Comment by vivet** [comment]
Will close the issue.
Let me know if you have further issues
