### ISSUE TITLE
region parameter not available in Distance matrix API 

### ISSUE THREAD

**Issue by miguelcrpinto** [vivet/GoogleApi#209]
According to the [documentation of the distance matrix API](https://developers.google.com/maps/documentation/distance-matrix/overview#optional-parameters), there's an optional region parameter which is not available in the DistanceMatrixRequest.

Is there a reason for not having left this parameter in the DistanceMatrixRequest model?

**Comment by vivet** [comment]
Hi
The reason I haven't added it, is because I don't keep up with all changes. I suppose it has been added by Google recently. Normally, someone creates an issue, like you have, and I implement within a few days.

Will merge the PR tomorrow.

**Comment by miguelcrpinto** [comment]
I don't know when it was added. I started using your library today and noticed it was missing and would be handy for me.

Glad I could help.

**Comment by vivet** [comment]
Hi
I have merged your PR, and published an updated NuGet package, v3.1.15

**Comment by miguelcrpinto** [comment]
great! thanks

**Comment by vivet** [comment]
Will close the issue.
Let me know if you have further issues.
