### ISSUE TITLE
Misssing via_waypoint array in route's leg in response from Google Directions API

### ISSUE THREAD

**Issue by Prologh** [vivet/GoogleApi#212]
Hi

I'm using your library to integrate with Google Directions API and I've noticed there is missing `via_waypoint` field in route's leg:

[Leg class source code](https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Maps/Directions/Response/Leg.cs)

That field is an array of objects with following structure:

```JSON
"via_waypoint":[
   {
      "location":{
         "lat":51.1012783,
         "lng":17.0461892
      },
      "step_index":3,
      "step_interpolation":0.1964846925124263
   }
]
```

Sadly there is no mention about it in [Google Documentation](https://developers.google.com/maps/documentation/directions/overview#Legs).

Sample query with `via_waypoint` field in response (be sure to add your own key!):

> https://maps.googleapis.com/maps/api/directions/json?sensor=false&key=YOUR_API_KEY&origin=51.0994417%2C17.02892&destination=51.103288,17.0916053&waypoints=via:51.101274,17.046209&mode=driving

Is there a possibility to add this field?

**Comment by vivet** [comment]
Hi
Will take a look, and expose the waypoints in the response.
Nice catch 😃

**Comment by Prologh** [comment]
Great to hear, thanks!

**Comment by vivet** [comment]
I took a brief look.
First, I can see that i skipped a bit over the waypoints part, when I initially created the repository. So I will implement all four possible types of waypoints (location, address, placeId and polyline). Second, i will implement 'via' option for waypoints in the request, even though that I made a note, that Google had deprecated this in 2017. That seems wrong. Last, I will update response to include the via_waypoints.

**Comment by Prologh** [comment]
Deprecated in 2017, but still being returned in 2020. Indeed, wrong. Thanks for the update, looking forward for more.

**Comment by vivet** [comment]
I have added the 'via_waypoints' to the directions response.
I have also refactored way-points in the the request, making it possible to specify all types of way-points.

Let me know if you have further issues.
Please star my library if you like it.

/Michael

**Comment by Prologh** [comment]
Thanks a lot, I certainly will check out the changes and come back with confirmation that's everything's ok.

**Comment by Prologh** [comment]
I updated to the last version, everything looks fine, thanks for such quick fix for this, really appreciate it!
