### ISSUE TITLE
open_now being deprecated

### ISSUE THREAD

**Issue by r-barron** [vivet/GoogleApi#216]
Looks like Google is at work again deprecating some fields from the Google API.  I see that the source for GoogleApi still references open_now in OpeningHours:

https://github.com/vivet/GoogleApi/blob/8c889a75598bd453a7547e7aea4fc3e9af5ba238/GoogleApi/Entities/Places/Common/OpeningHours.cs#L15

Any plans to remove this?

From Google:
-----------------------------------------------------------------------------

We are writing to remind you that on November 20, 2019, the PlaceResult.opening_hours.open_now and PlaceResult.utc_offset properties in the Places Library, Maps JavaScript API have been deprecated and replaced by new properties and methods. You are receiving this email because your projects may be reading these properties from PlaceResult objects returned in response to Place Details, Find Place, Nearby Search and Text Search requests. 

Places API request | Deprecated | Replacement
-- | -- | --
Place Details | utc_offset | utc_offset_minutes
Place Details | opening_hours.open_now property | opening_hours.isOpen()   method
Find Place, Nearby   Search, Text Search | opening_hours.open_now property | No replacement*

*For Find Place, Nearby Search and Text Search requests, we provide alternative solutions for determining whether a place is open.

As a result, starting February 20, 2021, the Places Library, Maps JavaScript API will stop accepting utc_offset and the nested field opening_hours.open_now in the fields parameter and stop returning them in the PlaceResult objects in the response. Instead, you will receive the ‘Unsupported field name’ error when using these properties in the fields parameter and the value ‘undefined’ when reading these properties from the PlaceResult object in the response.

**Comment by vivet** [comment]
Will take a look at it. Thought I already changed it actually.

**Comment by vivet** [comment]
I looked into the issue, and it seems only to concern JavaScript service.
https://developers.google.com/maps/documentation/javascript/places
https://developers.google.com/places/web-service/search

**Comment by r-barron** [comment]
I think I agree with your reading of it.  But I'm a bit surprised that they seem to be removing it from Javascript but not elsewhere.  I did find a sentence on [a page](https://developers.google.com/maps/documentation/javascript/place_field_js_migration), which seems to confirm it explicitly.  Bold highlighting is mine:

These fields are deprecated **ONLY** in the Places Library, Maps JavaScript API.

So this appears to be a false alarm.  Thanks for checking into it.

**Comment by vivet** [comment]
It's not that strange, cause in JS Google are able to add a function, whereas in the other they can't do that, why they need to expose the open_now.

Hope it clarifies it a bit.
