### ISSUE TITLE
Google.API.Search and GwebSearchClient not recognized after installing GoogleApi v 3.10.3 in my C# .NET Core project

### ISSUE THREAD

**Issue by bclayshannon** [vivet/GoogleApi#219]
I installed GoogleApi v. 3.10.3 in my C# .NET Core project in Visual Studio 2019.

I see it in the Packages of my app (GoogleAPI (3.10.3)...Compile Time Assemblies...GoogleApi.dll)

I added this to my usings:

using Google.API.Search;

...but it is not recognized. Intellisense claims "Using directive is unnecessary"

The following code, which I adapted from [here](https://csharp.hotexamples.com/examples/Google.API.Search/GwebSearchClient/Search/php-gwebsearchclient-search-method-examples.html)  and [here](https://stackoverflow.com/questions/18389714/search-keywords-in-google-through-c-sharp-window-application)

```
var client = new GwebSearchClient("http://www.google.com"); 
var results = client.Search("google api for .NET", 100);
foreach (var webResult in results)
{
    //Console.WriteLine("{0}, {1}, {2}", webResult.Title, webResult.Url, webResult.Content);
    hits.Add(webResult.ToString());
}
```

...won't compile ("The type or namespace name 'GwebSearchClient' could not be found (are you missing a using directive or an assembly reference?)")

Am I confused about which package I should have, or what's going on here?

**Comment by vivet** [comment]
The types you are referring to doesn't exist in the package. The references is not for this project. Read the readme, to understand how to use it.
