### ISSUE TITLE
Create support for channels for every request

### ISSUE THREAD

**Issue by VoroninDA** [vivet/GoogleApi#223]
Can we please expose the ability to set a channel on the request body of Google payloads?

See the documentation below. Thank you. I see that we are allowed to set a Client ID, but that is not necessary for my use case.

[Channel Documentation](https://developers.google.com/maps/premium/reports/usage-reports#channels)

Maps Static and Street View Static APIs

Include this channel parameter in the request URL:

https://maps.googleapis.com/maps/api/staticmap
?center=15.800513,-47.91378
&zoom=11
&size=300x300
&client=gme-yourclientid
&channel=your_channel
&signature=your_signature

Web services

Include this channel parameter in the request URL:

https://maps.googleapis.com/maps/api/geocode/json
?address=101+Main+St
&client=gme-yourclientid
&channel=your_channel
&signature=your_signature

**Comment by vivet** [comment]
Hi
I will take a look at it.

**Comment by vivet** [comment]
The issue is fixed, and updated NuGet is published.

**Comment by VoroninDA** [comment]
Can we please add it to the base request since the channel field is for every request made to google?

Which APIs support channels?
Channel reporting is available for applications using the Maps JavaScript API, the Maps Static API, Street View Static API, and the Google Maps Platform web services. Channels are not available for the Geolocation API, Places API, Roads API, and Maps Mobile SDKs.

How do I set up channels for my application's requests?
Make sure the channel value in your requests meets the following requirements:

Must be an ASCII alphanumeric string.
Can include an underscore (_) and hyphen (-) character.
Is case-insensitive: Upper-case and mixed-case channel parameters are merged into their lower-case equivalent. For example, usage on the CUSTOMER channel will be combined with the usage of the customer channel.
Must be a static and assigned per application instance (it can't be generated dynamically). For example, you can't use channel values to track individual users.

**Comment by vivet** [comment]
It should be on all the above mentioned api's
Which ones do you believe doesn't have the channel parameter?

**Comment by vivet** [comment]
I will close the issue, as I haven't heard back from you.
Feel free to reopen the issue, if needed.

**Comment by VoroninDA** [comment]
PlacesFindSearchRequest is missing the Channels Parameter on version 3.10.5

**Comment by vivet** [comment]
The documentation says it's not supported for places api. Can you link where you saw this?

**Comment by VoroninDA** [comment]
This can be closed. Thank you.
