### ISSUE TITLE
Channels should be an int with a range from 0-999

### ISSUE THREAD

**Issue by VoroninDA** [vivet/GoogleApi#225]
https://developers.google.com/maps/reporting/gmp-reporting#usage-tracking-per-channel

> Usage tracking per channel
> You can now start tracking your usage via numeric channels. This is another way to categorize the source of your usage in addition to the product. To start doing this you need to add the 'channel' parameter to your requests. The only acceptable channel values are numbers from 0-999. Here are a few examples:
> 
> Geocoding Web Service API
> 
> https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY&channel=1
> 
> Maps JavaScript API
> 
> <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&channel=2&callback=initMap"
> async defer></script>
> 
> Note: Currently, channel data is not available for these SKUs:
> 
> Autocomplete without Places Details – Per Session
> Autocomplete (included with Places Details) – Per Session
> Geolocation

**Comment by vivet** [comment]
Will add some validation for this

**Comment by vivet** [comment]
It seems that it should be an Alphanumeric string. If you use channel 0-999 it does something in console reporting. Never tried it.

Point being, there should be no validation.
