### ISSUE TITLE
AddressComponentType field returns number instead of string in PlacesDetailsResponse

### ISSUE THREAD

**Issue by only1sham** [vivet/GoogleApi#226]
Hi,

I'm using v3.10.5 and invoking GoogleApi.GooglePlaces.Details.QueryAsync API to get PlacesDetailsResponse. However, the AddressComponentType values returned are numbers instead of string. Can you please let me know how to get string values back in the response for AddressComponentType?

**Comment by vivet** [comment]
If i remember correctly then it's a enum type. How you get numbers I'm not sure. Can you post the sample of what you are doing?

**Comment by only1sham** [comment]
@vivet , I'm actually trying to create a reusable Address Search module using GoogleApi. For this, I'm using .Net Standard library project. When I return the {PlacesDetailsResponse obj}.Result, to the client, the enums are actually becoming numeric. In the Types array, it shows numeric values instead of names like Street_Address, Postal_Code, etc.

This is what I'm using inside the class library method. Return type of Task<object> also gives same behavior. Any help on how to handle this would be appreciated.

        public async Task<PlacesDetailsResponse> GetAddressDetails(string placeId, string key)
        {
            PlacesDetailsRequest placesDetailsRequest = new PlacesDetailsRequest
            {
                Key = key, 
                PlaceId = placeId
            };

            PlacesDetailsResponse response = await GoogleApi.GooglePlaces.Details.QueryAsync(placesDetailsRequest);

            return response;
        }

**Comment by only1sham** [comment]
Figured out the issue. The changes I made to return PlacesDetailsResponse instead of object were not reflecting correctly in the client application for some reasons. Once this class library reference versioning was sorted out, I could get the expected results. This can be marked as closed.
