### ISSUE TITLE
Directions API Route Issue

### ISSUE THREAD

**Issue by pk-mallik** [vivet/GoogleApi#229]
The Directions API is only returning the polyline co-ordinates between the fist and last points and ignoring the intermediate way points, not sure what I'm doing wrong, code is attached
 

[GetDirections.zip](https://github.com/vivet/GoogleApi/files/5672942/GetDirections.zip)

Have tried variations with 'via' set to both true and false

**Comment by vivet** [comment]
Hi
Did you figure it out?

**Comment by pk-mallik** [comment]
Hi,

 

Yes I checked it out in more detail, while the problem was in the calling routine which was sending an empty string in the Address attribute of the Waypoint item, this may also be a bug in the component as the following code for new waypoint definition works:

                for (int i = 1; i < planLocations.Length - 1; i++)

                {

                    tempWayPoints.Add(new WayPoint(new GoogleApi.Entities.Common.Location()

                    {

                        Latitude = planLocations[i].latitude,

                        Longitude = planLocations[i].longitude

                    }));

                }

The following does not:

                for (int i = 1; i < planLocations.Length - 1; i++)

                {

                    tempWayPoints.Add(new WayPoint(new GoogleApi.Entities.Common.Location()

                    {

                        Address = "",

                        Latitude = planLocations[i].latitude,

                        Longitude = planLocations[i].longitude

                    }));

                }

However adding a value to the Address attribute also works:

                for (int i = 1; i < planLocations.Length - 1; i++)

                {

                    tempWayPoints.Add(new WayPoint(new GoogleApi.Entities.Common.Location()

                    {

                        Address = planLocations[i].locationAddress,

                        Latitude = planLocations[i].latitude,

                        Longitude = planLocations[i].longitude

                    }));

                }

 

 

The logic in the procedure seems to be to use the Lat-Long only if the Address attribute is null and even if it is an empty string it still tries to use the Address instead of the Lat-Long. I would suggest that it should use the Lat-Long by default and use the Address only if the Lat-Long is not defined or invalid

 

 

Regards,

 

P K Mallik

**Comment by vivet** [comment]
Yes, if i remember correctly you are correct that adress is used even when string.empty. That is cause its a valid string, null should be used.

**Comment by pk-mallik** [comment]
Thanks for the update, I would suggest you put a small note in the documentation and/or the test example
