### ISSUE TITLE
Is this a typo? AddressComponentType.Ukown

### ISSUE THREAD

**Issue by idreeshaddad** [vivet/GoogleApi#232]
https://github.com/vivet/GoogleApi/blob/bed8a7988feba69bb9037afd597dc08b0a42195e/GoogleApi/Entities/Common/Enums/AddressComponentType.cs#L14

![uknown](https://user-images.githubusercontent.com/2285974/108400245-aace4a00-7223-11eb-97c6-a613d54fdb47.png)

**Comment by vivet** [comment]
Will fix the spelling mistake, next time i release an update.
