### ISSUE TITLE
Michael, this question is not related to GoogleApi, but could you shed some light into it?

### ISSUE THREAD

**Issue by idreeshaddad** [vivet/GoogleApi#233]
Michael I'm sorry, I know this is not related to GoogleApi, but I'm stuck. If possible, could you please shed some light into this?

https://github.com/abpframework/abp/issues/7776#issue-811356218

**Comment by vivet** [comment]
Don't know that framework. But it seems it has a serializer not obeying the json attributes

**Comment by idreeshaddad** [comment]
Seems like it, waiting for an answer from their side.
Thanks for the prompt response.
