### ISSUE TITLE
incorrect enum to string for TransitRoutingPreference.LessWalking

### ISSUE THREAD

**Issue by Herostwist** [vivet/GoogleApi#234]
specifying transit routing prefs results in querystring of transit_routing_preference=lesswalking
but should be transit_routing_preference= less_walking (snake case)
resulting in google retuning a 400 error.

**Comment by vivet** [comment]
Hi

I will take a look at it, tomorrow.

**Comment by vivet** [comment]
Hi
Sorry for the delay, I have been a bit busy.
I am currently working on a solution, and just need to implement unit-tests for the fix.
I expect to publish an updated NuGet during the coming weekend

**Comment by vivet** [comment]
Its fixed and updated NuGet has been published.

**Comment by Herostwist** [comment]
Amazing. Thank you.
