### ISSUE TITLE
PlacesDetailsRequest should use GoogleApi.Entities.Search.Common.Enums.Language instead of GoogleApi.Entities.Common.Enums.Language

### ISSUE THREAD

**Issue by treisska** [vivet/GoogleApi#236]
Hello,

I'm not sure why there is 2 different Enum for Language, but the Place Details API support all of these languages: https://developers.google.com/maps/faq#languagesupport 
but the PlacesDetailsRequest use an Enum with way less choices.
Maybe it should use  GoogleApi.Entities.Search.Common.Enums.Language instead?
Or update GoogleApi.Entities.Common.Enums.Language?

**Comment by vivet** [comment]
Hi

There is a difference between the 2 language enums, so it shouldn't be the same, but if new languages are now supported, the Common one should be updated. Notice, that I have looked into this before, and Google's docs can be a little bit confusing. 
Before starting to implement a PR, paste the languages here, and I will check as well. If you prefer I can check it and fix it sometime during the coming weekend.

**Comment by treisska** [comment]
Hi again,

I've compared the languages from google maps documentation and what's in the Common Enum.
Here are the missing languages:

- Afrikaans
- Albanian
- Amharic
- Armenian
- Azerbaijani
- Belarusian
- Bosnian
- Burmese
- Chinese
- Chinese (Hong   Kong)
- Chinese   (Traditional)
- Estonian
- French   (Canada)
- Georgian
- Icelandic
- Kazakh
- Khmer
- Kyrgyz
- Lao
- Macedonian
- Malay
- Mongolian
- Nepali
- Punjabi
- Sinhalese
- Spanish (Latin   America)
- Swahili
- Urdu
- Uzbek
- Zulu

The docs for the Details API directly links to https://developers.google.com/maps/faq#languagesupport, so I think this is the list actually used.
Also the comment for German is wrong in the Enum, it says Dutch instead of German.

**Comment by vivet** [comment]
I checked it as well, and you're right. Finally it seems Google aligned the language support for their different api's. Before I implement it, I will need to go through all the api's and possibly just use one language enum. So it will take a little longer before I have an update.

**Comment by vivet** [comment]
I have updated the languages and published an updated NuGet package.

**Comment by treisska** [comment]
Hello,

Thank you for the quick fix! And thank you for the library as a whole 😊!
