### ISSUE TITLE
How to resolve GoogleApi.Entities.Common.Enums.Language from a language code

### ISSUE THREAD

**Issue by meriturva** [vivet/GoogleApi#240]
Actually, there is only a ToCode method here:

https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Common/Enums/Extensions/LanguageExtension.cs

What I miss is a fromCode method.

How could i get a correct language enum from an accept language header?

Thanks!

**Comment by vivet** [comment]
The library is not fot that.
There are facade implementations creating the requests and serializing responses. 

I think you misunderstood how to use the library. Try paste the code you have written.

**Comment by vivet** [comment]
I see.
It's a good idea, but also a bit out of scope for the library,
If you implement the method, I will be happy to extend the library for this convenience though.

**Comment by vivet** [comment]
Nice!
I will change it into a string extension and add tests for it, then I will publish and updated NuGet package

**Comment by vivet** [comment]
I converted it to string extension and added tests.
NuGet should be there in 10-15 min

**Comment by meriturva** [comment]
So thanks!
