### ISSUE TITLE
Choose more than one field type for return on place details request

### ISSUE THREAD

**Issue by tree-sphere** [vivet/GoogleApi#243]
Sorry if I'm just missing something, but I can't figure out how to list more than one field type I want returned, with the following request:

```
var request = new PlacesDetailsRequest {
  Key = _googleSettings.GooglePlacesKey,
  PlaceId = placeId,
  Fields = GoogleApi.Entities.Places.Details.Request.Enums.FieldTypes.Contact
};

var response = await GoogleApi.GooglePlaces.Details.QueryAsync(request);
```

Fields is an enum. I see instructions saying "Fields (optional). Defaults to 'Basic'. One or more fields, specifying the types of place data to return, separated by a comma." 
Not sure if I'm missing something, but I can't figure out how to do more than one. I would like to have the Basic and Contact fields returned. And if possible, I'd actually like more fine grain control. Thanks!

**Comment by vivet** [comment]
Hi
It's a flags enum, you can make any combination using "|" between values

**Comment by tree-sphere** [comment]
Oh. Perfect. Thanks for the quick reply. Hadn't seen that functionality before. Might be helpful to mention that in the intellisense comment. It mentions comma separated, so I wasn't even thinking in that direction.  Really appreciate the repo, it's a great help! Thanks again.

**Comment by vivet** [comment]
I should be obvious (not to sound cocky), but its a standard c# feature. Doesn't the intellisense show the flag attribute?

**Comment by tree-sphere** [comment]
________________________________

**Comment by tree-sphere** [comment]
I don't see it on the intellisense.  But now that I know what to look for, I do see it after clicking (twice) into the code a bit deeper.
