### ISSUE TITLE
About Delivery schedule map

### ISSUE THREAD

**Issue by pranilkadam** [vivet/GoogleApi#245]
Hi,
I have requirement like need to generate delivery schedule for 100 destinations.
**Source 1**  -> Destination 1
                       -> Destination 2
                       -> Destination 3
                       -> Destination 4
                       -> Destination 5

Now let’s say using google api we know that **Destination 2** is near from Source 1 then we need to find next near destination.
**Source 2**(ie Destination 2)  -> Destination 3
                                                  -> Destination 4
                                                 -> Destination 5

Likewise, if say 100 destinations then multiple iterations.
Could you please help or suggest way to implement above requirement.
We are using google apis for getting actual distance.

**Comment by vivet** [comment]
You need to use Hungarian algorithm i think. That will give you optimal assignments between x drivers and y destinations. Check the implementation i have on my profile

**Comment by pranilkadam** [comment]
Single source but multiple destination.

**Comment by vivet** [comment]
Well, you can still use Hungarian algorithm. But otherwise use directions api with optimize waypoints, though you are limited to like 24 waypoints if i remember correctly

**Comment by vivet** [comment]
Will close this issue
