### ISSUE TITLE
Missing 'Heading' in Location model

### ISSUE THREAD

**Issue by codechoked** [vivet/GoogleApi#246]
Hi!

Is there a way to incorporate Heading in Location (GoogleApi.Entities.Common) model so we could use it as mentioned [here](https://developers.google.com/maps/documentation/directions/get-directions#specify-that-routes-should-have-a-particular-heading)?

When there is no heading provided a route returned by google can lead in an opposite direction (obviously) than intended if only google thinks of it as a better way . 
If suppose google defaults it to 0 but not everyone is travelling north :)

**Comment by vivet** [comment]
I am working on a fix. Was a bit complicated cause the Location implementation isn't the most flexible. Hope to have fix tonight or tomorrow.

**Comment by codechoked** [comment]
Fantastic! 😃

**Comment by vivet** [comment]
I have added the heading to both Directions and Distance Matrix. I also added a side_of_road option. Waypoints supports that you can create them with a string, so here you need to manually add the heading to the string. That could need some refactoring, but I don't have to much time at the moment, so I will be in the future. Also in general the whole Location could use some refactoring too - it got a bit messy, but I will also do that in the future, when I have some more time.

https://github.com/vivet/GoogleApi/pull/247

I will merge tonight.

**Comment by vivet** [comment]
It's merged

**Comment by codechoked** [comment]
Thanks a lot!
