### ISSUE TITLE
Display a list of places and trail

### ISSUE THREAD

**Issue by weedkiller** [vivet/GoogleApi#248]
Hello, I am trying to use your lib,

Can share how to display a list of places and then some fading trails.

For e.g. `list of places bikers/joggers  can stop for water on map`.
The `trail of the jogger/biker` from hot to cold/currently (red) and fading as he was jogging to green. Like a fading trail to ensure the the map is not clogged/chaotic.

**Comment by vivet** [comment]
Hi
I am not entirely sure how you can accomplish that. Try take a look at places Find, or one of the other places lookup endpoints. Otherwise try consult Google places api documentation.

**Comment by weedkiller** [comment]
I was hoping to display multiple locations from my server side and then, append the CSS to them. 

Can you share how to display & access the css for multiple markers at the sametime, if it works I can PR the sample
