### ISSUE TITLE
Translation doesn't support es-MX/es-419

### ISSUE THREAD

**Issue by EBusch** [vivet/GoogleApi#249]
If you attempt to translate using `es-MX` or `es-419` it translates to `en` instead.

**Comment by vivet** [comment]
Hi
I will add the languages

**Comment by vivet** [comment]
When I look at the supported languages for Google translate endpoint, those two are not included. Could you share where you saw that they are?

**Comment by vivet** [comment]
... And also how did you manage to specify those languages, when the source and destination language is an enum?

**Comment by EBusch** [comment]
My bad, I didn't realize that it wasn't supported by Google! I'll do a workaround and double up on "es"
