### ISSUE TITLE
Getting Null Reference Error in DistanceMatrix.QueryAsync

### ISSUE THREAD

**Issue by buist-sharris** [vivet/GoogleApi#250]
Hello,

With the latest version 3.10.9, my app has broken.  I am now getting a null reference error when executing GoogleMaps.DistanceMatrix.QueryAsync.  The error is "parameter 'source' cannot be null.".

` var date = DateTime.Now.AddDays(1);
            date = new DateTime(date.Year, date.Month, date.Day, 2, 0, 0);

            var request = new DistanceMatrixRequest
            {
                Key = "MY KEY",
                OriginsRaw = $"place_id: MY PLACE ID",
                Destinations = new[] { new Location("1421 Kalamazoo Street, South Haven, MI 49090") },
                Units = Units.Imperial,
                TrafficModel = TrafficModel.Optimistic,
                DepartureTime = date
            };

            var response = await GoogleMaps.DistanceMatrix.QueryAsync(request).ConfigureAwait(false);`
            
This is occurring in DistanceMatrixRequest.GetQueryStringParameters() and it's due to "Origins" not being set (as I'm using OriginsRaw so I can use a place ID.

`this.Origins.Aggregate(string.Empty, (current, location) => current + $"{location.ToStringHeading()}|");` 

fails because Origins is null.

However, it shouldn't be required.  As this check at the beginning of the method requires an either  or...Origins or OriginsRaw

 `if (string.IsNullOrEmpty(this.OriginsRaw) && (this.Origins == null || !this.Origins.Any()))
                throw new ArgumentException("Origins is required");`

**Comment by vivet** [comment]
Hi
Thanks for reporting. It seems that I introduced an issue with the introduction of heading. Will fix it

**Comment by vivet** [comment]
... Though you can use placeId with Origins (if I don't remember wrong). Will check that as well.

**Comment by buist-sharris** [comment]
Yes, using Origins works.

  `var request = new DistanceMatrixRequest
        {
            Key = "MY KEY",
            Origins = new [] { new Location("place_id: MY PLACE ID") },
            Destinations = new[] { new Location("1421 Kalamazoo Street, South Haven, MI 49090") },
            Units = Units.Imperial,
            TrafficModel = TrafficModel.Optimistic,
            DepartureTime = date
        };`

**Comment by vivet** [comment]
Okay. I will still fix the Raw, hope tomorrow, but i am down with covid-19, so depends on how i am feeling.

Also i have plans to make a better Origins and Destinations implementation, to better support the different variations of location types.

**Comment by vivet** [comment]
I fixed the issue. 
Let me know if you have further issues.
