### ISSUE TITLE
WayPoints serialization problem

### ISSUE THREAD

**Issue by GoNextGroup** [vivet/GoogleApi#252]
Hello. I've updated library version from 3.9.1x to latest and caught this error:

`Unable to find a constructor to use for type GoogleApi.Entities.Maps.Directions.Request.WayPoint. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'WayPoints.$values[0].$type', line 31, position 16.`

Also libraries have enough of ambiguous code - for example, `Location` is located in Maps and Common both namespaces.

**Comment by vivet** [comment]
Hi

Not sure why you are getting that error. The WayPoint is never serialized inside the library, as it's used by the request and not the response. Can you paste some code, then I will try to reproduce it.

Regarding Location, then they are not ambiguous, they are different. How a Location is supported by Google depends on the endpoint. Though, when that is said, I am actually working on improving the naming this is version 4.

**Comment by GoNextGroup** [comment]
Hi.

I use DirectionRequest as a DTO in my microservices. Of cource, in reduced form (with only Start/Finish points and intermediate points). So, should I rewrite my code not to use Requests directly in microservices?

**Comment by vivet** [comment]
Hi
Its never a good idea to use classes from external libraries directly like that, so i would suggest making your own. Gives you more control. Then implement a mapper method, or use automapper
