### ISSUE TITLE
Application restrictions Xamarin

### ISSUE THREAD

**Issue by angelru** [vivet/GoogleApi#254]
Hello,

First of all thanks for this library, I am using it in Xamarin for autocompletion and it works great, but I need to restrict the KEY API, and when I put it to only android applications I get this message:

Google Places API: “This IP, site, or mobile application is not authorized to use this API key”.

As I understand it, your library makes REST calls to the Google api, so it makes sense since it is a mobile client and not a web client. is there any way to pass headers? or how I could fix it to not create a backend in .net core. since I use the services in the google cloud.

**Comment by vivet** [comment]
Hi
I haven't worked with xamarin, so i am not familiar with the problem. If you dont want to use api-key how do you intend to authenticate towards Google.

**Comment by angelru** [comment]
If I want to use Api key, how do I restrict the use in the google console? because if I put for my application I get the message that I put above.

**Comment by vivet** [comment]
That i don't know. I have only used the library from backend web. I don't know (but don't think) that you can use other authentication method, but api-key. 
Most importantly is that the key isnt exposed in the Android app, and that you cycle it regularly.

**Comment by angelru** [comment]
sure, and in the registry console it restricts the key to an IP (the backend) but I don't have a backend in .net. the problem is that the apikey has to go inside the android application, in the code. I have to find some other alternative.
