### ISSUE TITLE
Forced latlng query parameter even for string address in geocoding

### ISSUE THREAD

**Issue by Prologh** [vivet/GoogleApi#255]
Hi
It seems that logic that adds query parameters for `Location` always add `latlng` parameter, forcing reversed geocoding even if string address was provided.

For example, if I pass location:

```C#
var location = new Location(address: "Sydney");
```

I'll get a request URL having `latlng=Sydney` which is incorrect. It should discover that I specified string address instead of coordinates and return `address=Sydney` as specified in [documentation](https://developers.google.com/maps/documentation/geocoding/overview#GeocodingRequests). 

Only if address is null, `latlng` parameter should be returned, meaning a reversed geocoding is desired. Refer to [documentation](https://developers.google.com/maps/documentation/geocoding/overview#ReverseGeocoding) for names.

Looking at `Location` entity, [`ToString()`](https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Common/Location.cs#L64) method already bears resemblance to this awareness.

I think a fix for the issue would be to simply check if location address is null and based on that add a parameter with the corresponding name. `GetQueryStringParameters()` method in `LocationGeocodeRequest` needs to be updated, as currently it always adds `latlng` parameter. See [source file](https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Maps/Geocoding/Location/Request/LocationGeocodeRequest.cs#L53).

**Comment by vivet** [comment]
Hi
Yes I noticed that while working on version 4. It will be fixed in that version, cause major refactoring around the Location is class is already done. I expected v4 to be out in July, but I got delayed, so I expect end of August.

**Comment by Prologh** [comment]
All right, happy to hear it's already fixed. Looking forward to the new version.

**Comment by vivet** [comment]
You can check the branch. All the ways a location can be specified will be possible, and yve different api's will use an implementation specific for them.

**Comment by vivet** [comment]
Hi
Version 4.0 has been released. 
Looking forward to hearing your opinion about the new "Location" implementation.
And feel free to report any issues.

**Comment by vivet** [comment]
I will close the issue, please reopen if you have any questions and further issues

**Comment by Prologh** [comment]
Apologizes for delay, just got back from vacation. I gave it a try with a request for standard and reverse geocoding, and it works well. Nice job and thanks!
