### ISSUE TITLE
GooglePlaces.TextSearch.QueryAsync(request) freezes

### ISSUE THREAD

**Issue by GuerrillaCoder** [vivet/GoogleApi#257]
When I am looping over pages like so:

```
request.PageToken = response.NextPageToken;
response = await GoogleApi.GooglePlaces.TextSearch.QueryAsync(request); //if too quick locks forever
```

The thread locks waiting for `QueryAsync` to finish.

I saw the tooltip about page token not being ready immediately and added a delay and then it worked.

The problem is I have to set a long enough delay so it is never the case as it will totally lock so this isn't efficient.

I looked at HttpEngine.cs and can see an "InvalidRequest" exception gets triggered there but the exception doesn't bubble up to my calling code, it just sits there forever waiting for task to complete.

I am not sure why my calling code doesn't get the exception

**Comment by vivet** [comment]
Hi
I have done some testing, and I cannot reproduce the issue. I get the exception
Maybe if you can paste some more of the code you are using, I can be of help.

**Comment by GuerrillaCoder** [comment]
OK, next time I need to process the data I will try making a standalone repro.
