### ISSUE TITLE
Cannot use the channel parameter

### ISSUE THREAD

**Issue by eisbear77** [vivet/GoogleApi#26]
I need to pass the channel parameter to all Google Places API requests, but I cannot find it in PlacesAutoCompleteRequest or PlacesDetailsRequest. How can I do it?

Regards,
Stefan

**Comment by vivet** [comment]
I will add the channel parameter, though according to this https://developers.google.com/maps/premium/reports/usage-reports its not supported excepts for maps requests.

_Which APIs support channels?
Channel reporting is available for applications using the Maps JavaScript API, the Static Maps API, Street View Image API, and the Google Maps APIs web services. Channels are not available for the Geolocation API, Places API, Roads API, and Maps Mobile SDKs._

**Comment by vivet** [comment]
I have added Channel parameter to Maps Directions, Distance Matrix, Elevation, Geocoding and TimeZone.
Let me know if you understand the documentation differently.

**Comment by vivet** [comment]
Also will update Nuget package soon, just need to run some tests first.

**Comment by eisbear77** [comment]
Thank you Michael. Could you please create a strong named dll? The new dlls are not signed (...public key token")

**Comment by vivet** [comment]
Sorry, will look into that. Actually forgot about that.
I created a new issue here: https://github.com/vivet/GoogleApi/issues/29

**Comment by vivet** [comment]
I have pushed strongly typed assemblies for both .netstandard13 and .net45. 
Will publish Nuget package later today.

**Comment by eisbear77** [comment]
Thank you, Michael.

**Comment by vivet** [comment]
No problem.
Let me know if you have more issues, or issues with the latest fixes
(channel param, etc)


-- 

MICHAEL VIVET
VP Product & Development

Mobile: +45 30 86 45 25
Email: mv@drivr.com
Address: Jagtvej 111, DK-2200 København N

*https://*drivr.com <http://www.drivr.com/>
*https://*facebook.com/drivrhq
*https://twitter.com/drivr <https://twitter.com/drivr>*
