### ISSUE TITLE
[QUESTION] Administrative_Area_Level_2

### ISSUE THREAD

**Issue by angelru** [vivet/GoogleApi#262]
I'm using GooglePlaces, is there a more direct way to get `GoogleApi.Entities.Common.Enums.AddressComponentType.Administrative_Area_Level_2 `??

I get for example:
```
28320 Pinto, Madrid, Spain
Playa Muchavista, 03560 Campello, Alicante, Spain
```

I want to get Madrid and Alicante

**Comment by vivet** [comment]
You need to look at the different components returned.

**Comment by angelru** [comment]
Administrative_Area_Level_2

may it not return Madrid or Alicante?

**Comment by vivet** [comment]
Don't know.
Not even sure what you mean. 
Please, explain properly what you expect, and include the request you use and the the response you get and what you expect.

**Comment by angelru** [comment]
I hardly know English.
I meant that if Administrative_Area_Level_2 always returns Madrid when the place belongs to Madrid.
Because I need to save the Administrative_Area_Level in the database.

**Comment by vivet** [comment]
If you hardly know English it's hard to help.
Google returns a set of components, and the values can differ depending on the request.
Don't think I can help much more.

**Comment by angelru** [comment]
Thanks a lot!
