### ISSUE TITLE
converting from JS DirectionsService response

### ISSUE THREAD

**Issue by EpiniX** [vivet/GoogleApi#263]
Hi @vivet, thanks for that useful library.
I'm trying to push an array of DirectionsService response to my server (through a web api) so my function is expecting a HttpPost with a body of type GoogleApi.Entities.Maps.Directions.Response.DirectionsResponse[]

Unfortunately i got those error when it tries to deserialize
$type: "Microsoft.AspNetCore.Mvc.NewtonsoftJson.ValidationProblemDetailsConverter+AnnotatedValidationProblemDetails, Microsoft.AspNetCore.Mvc.NewtonsoftJson"
errors: {,…}
status: 400
title: "One or more validation errors occurred."
traceId: "|49f2b82f-478b44ac7ea989bf."
type: "https://tools.ietf.org/html/rfc7231#section-6.5.1"

The two errors inside errors property :
* directions_responses[0].routes[0].bounds: ["The input was not valid."]
* "Error converting value \"ejifHdlaZ{Cy@{@Wo@[_@QeAg@w@c@sA{@mBsAa@S?xAD~BCX@x@BbEItAQpAUz@Yx@KXYb@MNI@ACCCIEE@A@MY[{AQe@k@_BYc@S[a@}@FW?c@M_@WIK@QNELo@_@{B}AcAu@kAm@eBq@eCkA}B{@qAe@_@GY@IHg@fAe@h@g@\\_@VaAj@wAl@e@HIKGECSCQSm@YsBkBkI_AwE_@yCc@aEw@iIsAkOCeA?_@Js@JSVQl@]LANF@DDHPRNHP?NETSJW@KT[b@_@Rq@@?@ABE@G?C\\}Aj@wCb@_BnBoJDCFO?SpBaGZcBXwBN{D@qAGc@Pu@LcBPeCJqA?qBIeEC_BF{CNoCd@mERyBCg@GU@G@GAIJQNi@Nu@Bk@Jo@\\iB\\kA`@kAhAwCdByCl@y@x@}@^]xBmB@?@DJDHEDK?O?Ed@[vAiAfCkB`CcBtC}BfMoJ|GeFbCgB~@q@\\[t@}@^w@Vw@ReANcB?UM[Wg@L_@LAFGJW?]GwBAUEg@AeE?IKsBIuB?o@?_@D}DA_BQoFScII{E?sCFeCL}B^gILwERuIHe@Nc@r@qALo@\\{@BCFGHU@[E[Ds@?_@FaCN{A^qCd@yBn@qCdAqGX{BRyBFYDo@J{ALwBFu@FwA?_AG}HCcAMaDMmAEoAGuAUmGSuDYsEQeICiB?wADiGB_@Lu@OyB?o@?kBAwAMkGQuMBcDH_CPkDHsADGDQ@SEc@EKCE@m@LwAb@mCf@gCNoAJaABu@@sACoBMcDEsAI{BKmC?oDBqFIyBY_Co@oCe@qA[s@g@qASs@Os@ScBEkA?e@JqBZcBbAkEnAsFXu@V_@Ti@|@{AxAiCP]|@eBbA}B`@w@h@uBT}@ZgCJeB?iA?wA@iACo@?wEBeCDeAFoARyAd@mBPc@v@wBRw@`@gBP{AJ_BLmCLuDNsFCqAIiAGmAGyA@eDH}DFqCBy@HcA@q@J}@VwA~@uCjAiCDI\" to type 'GoogleApi.Entities.Maps.Directions.Response.OverviewPolyline'. Path 'directions_responses[0].routes[0].overview_polyline', line 1, position 514643."

I don't understand well the second error, but the first is about Viewport class which expect :
public virtual Coordinate SouthWest { get; }
public virtual Coordinate NorthEast { get; }

but Google Maps API answers with 4 properties : 
"bounds":{"south":47.99349,"west":-4.43851,"north":48.45105,"east":-3.9362200000000005}
[sample DirectionsService Response.txt](https://github.com/vivet/GoogleApi/files/7296498/sample.DirectionsService.Response.txt)

**Comment by vivet** [comment]
Yes you should create your own classes
