### ISSUE TITLE
Wrong key used in HttpEngine.SignUri

### ISSUE THREAD

**Issue by eisbear77** [vivet/GoogleApi#27]
var privateKey = this.FromBase64UrlString(request.Key);

But request.Key is the API Key, not the private crypto key for Client ID

You will get an System.FormatException.

**Comment by vivet** [comment]
The request.Key works for both types of requests.
I am not sure why you get a System.FormatException. Maybe if you supply for information I will be able to see what happens in your case.

**Comment by vivet** [comment]
Basically if you provide a ClientId the the request.Api must be the premium key, and otherwise the free api key.
