### ISSUE TITLE
Providing the HttpClient

### ISSUE THREAD

**Issue by robert-stratecglobal** [vivet/GoogleApi#273]
In a backend api server environment, it's common to refer to an `IHttpClientFactory `to build and manage the life instance of the `HttpClient`

Instead of relying on a static instance of an `internal static`, instead provide a 

```
HttpEngine {

  internal static Func<HttpClient> { get; public set; } =
  {
      // current implementation logic
  }
}
```

By providing the current behavior it would not break the current implementation

**Comment by vivet** [comment]
Hi
I have considered that a few times, but I don't want the consumer to handle it, as that would require knowledge about the HttpClient needed for invoking a request towards Google.

**Comment by bobbyangers** [comment]
Hi @vivet,
While keeping the API as is we and keep the static version property fields...

However this does not play well in a .NET web hosted instance.   The web uses dependency injection and manages the lifetime of the HttpClient in a web "friendly" fashion ensure that threading and port exhaustion is managed properly.

So to ensure proper functioning, we would need to create classes that accept an supplied in the constructor.  In the case the default constructor is used, then fallback on the global "static".

This way the current API would be maintained, but more advanced user scenarios would be covered.

Let me give it a try.

**Comment by vivet** [comment]
Thanks for the PR.
I will have a deeper look into it, but it will be in a while. I hope sometime in February

**Comment by bobbyangers** [comment]
@vivet, you are welcome.
I respect that you are busy.  let me know;  in the meantime, I'll publish my fork in a private asset/nuget and use that.

**Comment by vivet** [comment]
Hi
I haven't forgotten you, just been crazy busy.
I will take a look soon, but be aware that I cannot merge your PR directly, cause you changed too many cosmetic issues. So I will take a look at your implementation, and implement just the ```IHttpClientFactory```.

**Comment by bobbyangers** [comment]
Ok, if you need my input, let me know.

I can also rework my PR if it can help.

Just give some clear instructions.

**Comment by vivet** [comment]
Hi
It could be nice if you can rework the PR to contain only the changes required for the feature, and not cosmetic improvements. Then i will merge it, and possibly to slight refactoring before releasing.

Feel free to submit another PR for the cosmetics, if you like

**Comment by bobbyangers** [comment]
can you please tell me what you mean by cosmetic?  Can you elaborate ?

I mean, i kept the same api, but created classes and instances to be compatible with the Dependency Injection....

HttClient should be mananged by the Runtime, not a single static instance... 

As a reference, the runtime, periodically recycles the instances to avoid leakage and resource management.

**Comment by vivet** [comment]
Sure.
It's not the core implementation of the IHttpClientFactory itself, but when looking at the PR i see many changed files, most where just trailing spaces or similar has been removed.

Make sense?

**Comment by vivet** [comment]
Also gitignore for example

**Comment by vivet** [comment]
I am almost done with the change, and expect to publish and updated NuGet within the next week

**Comment by bobbyangers** [comment]
Ok I’ll take another look and fix those elements.

I’ll make sure I disable the format on save in VS2022 to avoid that from happenning.

If you have others

--Robert Angers
m:514-557-8074

Sent from my iPhone

On Apr 25, 2022, at 15:17, Michael Vivet ***@***.***> wrote:

﻿

Also gitignore for example
