### ISSUE TITLE
Disposing and static HttpClient

### ISSUE THREAD

**Issue by robert-stratecglobal** [vivet/GoogleApi#274]
In the `HttpEngine`, why are we disposing the static HttpClient, which is shared amongs all instances of the `HttpEngine` ?

this should only be disposed if the "last" instance.... and there is no real way of telling....

```
    /// <summary>
    /// Disposes of the <see cref="P:GoogleApi.HttpEngine.HttpClient" />, if <paramref name="disposing" /> is true.
    /// </summary>
    /// <param name="disposing">Whether to dispose resources or not.</param>
    protected virtual void Dispose(bool disposing)
    {
      if (!disposing)
        return;
      HttpEngine.HttpClient?.Dispose();
      HttpEngine.httpClient = (HttpClient) null;
    }
  }
```

that is why it would be better to let the user of the classes provide the http client
See: #273

**Comment by vivet** [comment]
Hi
It's a bit of old code. The dispose is never really invoked. Let me just consider to remove it all together.

**Comment by vivet** [comment]
I will remove it, alongside looking into your other PR

**Comment by vivet** [comment]
I have removed the IDisposable interface.
I will close the issue, the change will be released when I am through all the issues you have created :-)
