### ISSUE TITLE
Support for .NET standard prior to 2.1

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#275]
In accordance to this:
[.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
and
[.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

We should consider dropping the support for .NET for anything prior to 2.1;  
.NET core 3.1 EOL Dec 2022
.NET 5  EOL May 2022

And anything prior has all have fallen out of support.  .NET standard 2.0 matches with .NET 4.6.1;  everything else are for prior versions.

Anyone still needing any of these can continue to use this version and prior

**Comment by vivet** [comment]
Hi
Yeah you are right. I have considered it the past six months.

**Comment by vivet** [comment]
I removed netstandard 1.1 and 1.4, and added net6.0
I will leave netstandard 2.0 for now, and cleanup after net5.0 is EOL

**Comment by bobbyangers** [comment]
FYI: .NET5 is NETstandard 2.1.
