### ISSUE TITLE
Nuget Key Should be moved to Secret

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#278]
It would be recommended to move the secrets to ensure it doesn't get hacked.
- `NUGET_HOST`
- `NUGET_APIKEY`

`appveyor.yml`
```
env: 
   NUGET_APIKEY:  ${{ secrets.NUGET_APIKEY }}   
```

[Set up Secrets in GitHub Action workflows](https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md)

**Comment by vivet** [comment]
Hi
It's already encrypted through AppVeyor

**Comment by bobbyangers** [comment]
@vivet but it appears in clear text in the file ???

Do you mean what we see the file, is an encrypted value that you imported from **appveyor** ?

**Comment by vivet** [comment]
Hi
It's not plain text. the NuGet key is encrypted on AppVeyor.
So you would need to have access to my AppVeyor account in order to start the build. The encrypted key is useless otherwise. Your fork doesn't have have the webhook required to start the build.

I don't see how you would be able to at least.

**Comment by vivet** [comment]
Can you link to the file and line, where you believe the key is plain text.
Just to make sure I am not wrong :-)

**Comment by bobbyangers** [comment]
> Can you link to the file and line, where you believe the key is plain text.
> 
> Just to make sure I am not wrong :-)

It's in the appveyor.yml

**Comment by vivet** [comment]
Well that is encrypted, and can only be decrypted through my account, so it should be fine as is.

**Comment by bobbyangers** [comment]
Maybe; you are right, but the downside is that people wanting to fork cannot "build".
It would be nice to be able to introduce the key from the secrets, and also in the publish target.
