### ISSUE TITLE
Add Tourist_attraction in GoogleApi.Entities.Places.Search.Common.Enums.SearchPlaceType

### ISSUE THREAD

**Issue by lucie1605** [vivet/GoogleApi#281]
Hi,
Would it be possible to add Tourist_attraction in GoogleApi.Entities.Places.Search.Common.Enums.SearchPlaceType ?
In order to add it in the **Type** of **PlacesNearBySearchRequest**.

I can see that it is available in Places API, and we already have it in the response (in the array **Types** of type GoogleApi.Entities.Common.Enums.PlaceLocationType)

Thanks a lot,

Best regards
Lucie

**Comment by vivet** [comment]
Its possible 😀
Can you link to the documentation

**Comment by lucie1605** [comment]
Great :) 
Yes sorry I forgot : https://developers.google.com/maps/documentation/places/web-service/supported_types?hl=fr
Table 1

**Comment by lucie1605** [comment]
that is so quick! thanks a lot ! and it is working :)
