### ISSUE TITLE
Should not throw General Exception like NullReferenceException

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#286]
Throwing such general exceptions as Exception, `SystemException`, `ApplicationException`, `IndexOutOfRangeException`, `NullReferenceException`, `OutOfMemoryException` and `ExecutionEngineException` prevents calling methods from handling true, system-generated exceptions differently than application-generated errors.

Ref: https://rules.sonarsource.com/csharp/RSPEC-112

Should throw `ArgumentNullException` or `GoogleApiException` instead

**Comment by vivet** [comment]
Hi 

I have merged your PR, and published new Nuget package.
