### ISSUE TITLE
Question to using a proxy

### ISSUE THREAD

**Issue by AlexHasel** [vivet/GoogleApi#288]
Hi,
in the last GoogleApi-Version I used 
    GoogleApi.HttpEngine.Proxy = new WebProxy("1.1.1.1", 8080)  { UseDefaultCredentials = true };

How have I to modify my code, that I can use a Proxy with the new version?
Alex.

**Comment by ParsePortAdmin** [comment]
Hi
I am not using the Proxy part myself, but you should be able to set the HttpClientFactory.Proxy, before you call AddGoogleApis in startup or use the facade.

Let me know if that doesn't work
