### ISSUE TITLE
NETCOREAPP3_1_OR_GREATER conditional compile flag is not set

### ISSUE THREAD

**Issue by SykesJohn** [vivet/GoogleApi#290]
In Visual Studio:

1. Go to the project Properties > Build > General
2. Under Conditional compilation symbols, click the settings gear.
3. Change it to "Vary value by target framework".
4. Add ";NETCOREAPP3_1_OR_GREATER" to netcoreapp 3.1 and net6.0
5. Rebuild

**Comment by SykesJohn** [comment]
Note: you may need to remove the TRACE macro as it is already defined in $(DefineConstants).

Alternatively replace "NETCOREAPP3_1_OR_GREATER" with "NETCOREAPP3_1 || NETCOREAPP"

**Comment by vivet** [comment]
Will check it out

**Comment by vivet** [comment]
I will remove all the conditional compile flags, and publish a new NuGet

**Comment by vivet** [comment]
Updated NuGet on the way
