### ISSUE TITLE
Library cannot be used in Blazor client side apps.

### ISSUE THREAD

**Issue by SykesJohn** [vivet/GoogleApi#291]
It looks like Net.Http.HttpClientHandler has some methods that are not supported when running in the browser.

It may be possible to refactor the library to use HttpClient or some other way to call the API that is supported. Other tools and libraries are able to make Google API calls from a web browser (e.g. Blazor web assembly).

Side note: HttpClient has many extension methods that could simplify the code.

**Comment by vivet** [comment]
I am not sure what the specific problem is, but if you can send the failing code example or create a PR that fixes it, i will take a look

**Comment by vivet** [comment]
Did you see my last comment, or maybe you figured out why your code didnt work?

**Comment by SykesJohn** [comment]
The root problem seems to be that the library is based on HttpClientHandler instead of HttpClient, or something like that. The former is not supported on the client side (e.g. Blazor web assembly). I will try to build a project to demonstrate. For now, I am using the library in a server side implementation.

**Comment by vivet** [comment]
I am not sure a demo project will help me much, as I am not proficient in Blazor. 
You mention that the root problem is HttpClientHandler or something.... What exactly is the problem? Do you get a platformNotSupportedException ? If that's the case, then we must wait until it's supported, and you should use the server-side part for GoogleApi.

Let me know if you figure something out

**Comment by SykesJohn** [comment]
If you are interested, I have created a demonstration project where you can observe the issue:
SykesJohn/GoogleApiDemo: Shows how GoogleApi does not work in client side Blazor. Replace "<put your key here>" with your key, (github.com)<https://github.com/SykesJohn/GoogleApiDemo>
We may not need to wait for HttpClientHandler to be changed if HttpClient will do everything you need.

**Comment by vivet** [comment]
Okay, will take a look at it

**Comment by bobbyangers** [comment]
Hi @SykesJohn,

One thing you can try is to simply create your custom implementation of this class ( [ServiceCollectionExtensions](https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Extensions/ServiceCollectionExtensions.cs) ) and provide your own implementation of `HttpClient` that don't rely on the `HttpClientFactory.ConfigureDefaultHttpClient` and `HttpClientFactory.GetDefaultHttpClientHandler`

```
private static IServiceCollection AddApi<TClient>(this IServiceCollection services)
        where TClient : class
    {
        services
            .AddHttpClient<TClient>(HttpClientFactory.ConfigureDefaultHttpClient)
            .ConfigurePrimaryHttpMessageHandler(() => HttpClientFactory.GetDefaultHttpClientHandler())
            .SetHandlerLifetime(TimeSpan.FromMinutes(5));

        return services;
    }
```

Since it's only really a few lines ( ie one small extensions class `ServiceCollectionExtensions` with two methods ), I think you can easily create a class in your project to mimic this one and configure your `HttpClient` just the way you want.

This said the class provided with the library is configured this way to enable compressions
```
httpClientHandler.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
```


As an example:

```

...
        services
            .AddApi<GoogleSearch.WebSearchApi>()
...

private static IServiceCollection AddApi<TClient>(this IServiceCollection services)
        where TClient : class
    {
        services.AddHttpClient<TClient>()
            .SetHandlerLifetime(TimeSpan.FromMinutes(5));

        return services;
    }
```

Have a great weekend.

cc: @vivet

**Comment by vivet** [comment]
Hi

I tried you demo project and it works for me.

**Comment by SykesJohn** [comment]
Did you get both projects to work?

**Comment by vivet** [comment]
I haven't had the time to look at it yet.
It will be sone time before i get to it. I suggest you follow @bobbyangers suggestion, as you can customize as you like. It will be similar implementation i will do.

**Comment by vivet** [comment]
Try and build this branch: https://github.com/vivet/GoogleApi/tree/VERSION_424

...and then use this when registering Google api's.
```csharp
services
    AddGoogleApiClientsNoHandler()
```

if it works for you I will merge the branch and release and updated NuGet

**Comment by vivet** [comment]
Seems your application is running with the nuget and not the lical build

**Comment by SykesJohn** [comment]
I am using the local, but I forgot to switch to the new branch before the build. Now I am trying to flush the NuGet cache…

**Comment by SykesJohn** [comment]
I got it building and recognizing the new service (builder.Services.AddGoogleApiClientsNoHandler();), but I still see this in the console logs:
System.PlatformNotSupportedException: Operation is not supported on this platform.

**Comment by vivet** [comment]
Hi

Not sure I can do much more.
You can try experiment wirh code base, and see if can figure it out.

**Comment by vivet** [comment]
you are injecting the api's and not using the facede, right?

**Comment by SykesJohn** [comment]
The only change I made to my GoogleApiDemoWASM project was to add

builder.Services.AddGoogleApiClientsNoHandler();

To Program.cs and update the NuGet. Were any other changes required?

Did you get the project to run?

**Comment by vivet** [comment]
You need to inject the api you want to use

**Comment by vivet** [comment]
If you are doing: GoogleMaps.Directions.Query(...), then it's wrong for what you are trying to accomplish

**Comment by SykesJohn** [comment]
I tried injecting the API like this in the AutoComplete.razor.cs:

      [Inject]
      public GoogleApi.GooglePlaces.AutoCompleteApi? autoComplete { get; set; }

and calling like this:

var list = await autoComplete.QueryAsync(req);

but the page won’t even render.

**Comment by vivet** [comment]
QueryAsync 😀

**Comment by SykesJohn** [comment]
I don’t see how this helps.

**Comment by SykesJohn** [comment]
Do you have a version of the Blazor project that works?

**Comment by vivet** [comment]
I didn't try.
Try add .ConfugureAwait(false)

**Comment by vivet** [comment]
Hi again
I took a look at your project. 

Let me start from the beginning.
GoogleApi can be used in two different ways. First, you can use the static facade implementation, to invoke request. Like this:
```csharp
GoogleApi.GooglePlaces.AutoComplete.QueryAsync(req);
```
When using the facade, you are invoking the default constructor in the ```HttpEngine```, and will use the default ```HttpClient```, that initializes the ```HttpClientHandler```. That seems to cause problems for you, so don't use this method. I can see in your demo project, that you are using GoogleApi this way (https://github.com/SykesJohn/GoogleApiDemo/blob/master/GoogleApiDemo/Pages/AutoComplete.razor.cs#L33). Maybe you didn't push your last changes, cause your messages indicates that you changed the implementation to using GoogleApi with dependency injection?

Anyhow, you need to use dependency injection, like this:
In the startup
```csharp
services
    AddGoogleApiClientsNoHandler();
```
Then in your constructor you inject the api you want to use. In your case it's ``GooglePlaces.AutoComplete```.
```csharp
public class MyClass
{
    private GooglePlaces.AutoComplete autoComplete;
    public MyClass(GooglePlaces.AutoComplete autoComplete)
    { 
        this.autoComplete  = autoComplete
    }
}
```
Last, in your logic you use the ```autoComplete```.
```csharp
this.autoComplete.QueryAsync(request).ConfigureAwait(false);
```
You need to add the ```.ConfigureAwait(false)```, otherwise your UI will block (as far as I know), as it seems was your recent problem.

If it still doesn't work, I am out of ideas. Note, that I never work with frontends, so my knowledge here is limited.
Hope it helps.

**Comment by SykesJohn** [comment]
I have made the changes you recommended, except that Blazor classes must have parameter-less constructors. I used the @inject directive to get the API.

I have pushed the changes for you to see.

**Comment by vivet** [comment]
Okay, and it works?

**Comment by SykesJohn** [comment]
No. It does not work for me. Did it work for you?

**Comment by vivet** [comment]
I haven't tried your demo project, just looked at the code, and then made the implementation without the ```HttpClientHandler``` as requested. 
I am sorry, but I can't spent more time on this. Feel free to make a pull-request if you can figure out why it doesn't work for you.

**Comment by pm64** [comment]
Hi @vivet, I came here from https://github.com/vivet/GoogleApi/issues/345 (please accept my apologies for not noticing the duplication sooner). I'm trying to give this approach a shot, but it looks like AddGoogleApiClientsNoHandler() was never merged into the main branch, and the link to the branch you reference above is now broken. Or maybe process for achieving this has changed since 7/2022? Any guidance you're able to provide would be appreciated.

**Comment by vivet** [comment]
Okay so you made it work?
I did try to include the configuration for not using HttpClientHandler. Check out this branch: https://github.com/vivet/GoogleApi/tree/ISSUE_291

Let me know if that works for you, and that you don't need to create your own HttpClient.

**Comment by vivet** [comment]
You should be able to use this now: ```services.AddGoogleApiClients(false)```

**Comment by pm64** [comment]
Hey @vivet I should have been more specific.. I was able to resolve my issue using info from this thread, by calling `builder.Services.AddHttpClient<GoogleSearch.WebSearchApi>()`, then injecting. Before that I had been using the static facade implementation.

Having said that, I just updated to v5.0.0 via NuGet, but I'm not seeing an overload for AddGoogleApiClients() that takes any parameter. Is this method in a namespace other than `GoogleApi.Extensions`?

**Comment by vivet** [comment]
Hi
It's not in the v5.0.0 NuGet. It's in the branch: https://github.com/vivet/GoogleApi/tree/ISSUE_291
If you build that branch and use the dll instead of NuGet you should the new ServiceCollection extension method.

**Comment by pm64** [comment]
Ah, I see, got it thank you.

**Comment by vivet** [comment]
Did it work for you?

**Comment by SykesJohn** [comment]
I switched to using GoogleApi on the server side and calling it via API calls instead. So, I gave up trying to get it working on the client side.
