### ISSUE TITLE
Regarding the issue that in StaticMapsApi, the url request generated by paths may exceed the limit

### ISSUE THREAD

**Issue by WooHao** [vivet/GoogleApi#294]
About class [MapPath] ToString Method

```
	/// <summary>
	/// Returns a string representation of a <see cref="T:GoogleApi.Entities.Maps.StaticMaps.Request.MapPath" />.
	/// </summary>
	/// <returns>The string representation.</returns>
	public override string ToString()
	{
		string text = $"weight:{Weight}";
		string text2 = "geodesic:" + Geodesic.ToString().ToLower();
		string text3 = ((Color != null) ? ("color:" + Color) : null);
		string text4 = ((FillColor != null) ? ("fillcolor:" + FillColor) : null);
		IEnumerable<string> values = new string[4] { text, text2, text3, text4 }.Where((string x) => x != null);
		string text5 = string.Join("|", Points.Select((Location x) => x.ToString()));
		return string.Join("|", values) + "|" + text5;
	}
```

If there is a lot of location data, the resulting length may exceed the limit.

Google officially gave a solution:
https://developers.google.com/maps/documentation/maps-static/start?hl=zh-cn#EncodedPolylines

Looking forward to adding this feature.

**Comment by vivet** [comment]
I will take a look at changing to use polylines when there is a lot of locations. I am not sure when i will get the time, but i hope soon

**Comment by WooHao** [comment]
> I will take a look at changing to use polylines when there is a lot of locations. I am not sure when i will get the time, but i hope soon

Thank you for such a quick reply, don't worry, I temporarily use other methods to achieve it.

**Comment by vivet** [comment]
I published an updated NuGet
