### ISSUE TITLE
Exception on Newtonsoft. 

### ISSUE THREAD

**Issue by yaggii** [vivet/GoogleApi#296]
Hi!

While using the Nuget Package (4.2.2) for the following origin - Destination: -13.68744,34.91742   |    -16.06818,34.86724

I get in the API the following error: 
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll

The return is valid and all though.

**Comment by vivet** [comment]
Hi

Which api are using?

**Comment by vivet** [comment]
Hi

I tried reproducing the issue, both with Directions and DistanceMatrix api. The serialization worked for me.
Could you provide the entire request?

**Comment by yaggii** [comment]
Hi,

I'll post the details still today.
Calling the API works but is giving this internal exception that I wanted to make visible for you!

Thanks,
Sérgio

**Comment by vivet** [comment]
Hi

As I haven't heard from you, I will close the issue.
I can't reproduce the issue either.

I am in the works of switching newtonsoft with System.Text.Json. Let's see if that will solve it for you.
