### ISSUE TITLE
Suggestion MinVer

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#297]
Hi @vivet 

Have you ever considered using [MinVer](https://github.com/adamralph/minver) to simplify your life with versioning your package ?

This tool will use the the latest recognizable (that match the pattern) tag in the git history to set the version on your assembly.

Checkout the README.md  it's pretty easy to follow.

**Comment by vivet** [comment]
Hi

For now i am fine doing it manually. I need to crete release notes anymore, but thanks for the info.
