### ISSUE TITLE
Suggestion => NetStandard 2.0

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#299]
Since all the versions of .NET you want to support are included in `netstandard2.0`,
![image](https://user-images.githubusercontent.com/1752811/185802107-48541424-8dd4-4274-8994-27cbfcbfa09e.png)

to simplify your packages supported framework,  the main dll `GoogleApi` should only target `netstandard2.0`;

This said, your tests can still target
`net461;net48;netcoreapp3.1;net6.0`

But the minimum 
`net461;net6.0`

**Comment by vivet** [comment]
I prefer ysing specific targets.
Then the most recent / suitable framework will be used.
