### ISSUE TITLE
GoogleFunctions.EncodePolyLine with DistanceMatrixRequest 

### ISSUE THREAD

**Issue by sirfilipef** [vivet/GoogleApi#30]
Hello,
I want to use the GoogleFunctions.EncodePolyLine with DistanceMatrixRequest how can I achieve this?
Thanks

**Comment by vivet** [comment]
Hi

I am not sure exactly what you are trying to accomplish, but the
EncodePolyline function converts a collection of coordinates into a strung,
and the DecodePolyline conversation it back into coordinates.

I am not sure how you want to use that with DistanceMatrixRequest.
Hope it clarifies things, otherwise let me know if I can be of further
assistance.

**Comment by sirfilipef** [comment]
Thanks for the response.

Check this link:
https://developers.google.com/maps/documentation/distance-matrix/intro#Introduction

"_Alternatively, you can supply an encoded set of coordinates using the Encoded Polyline Algorithm. This is particularly useful if you have a large number of origin points, because the URL is significantly shorter when using an encoded polyline. 
Encoded polylines must be prefixed with enc: and followed by a colon (:).For example: origins=enc:gfo}EtohhU: 
You can also include multiple encoded polylines, separated by the pipe character (|). For example: origins=enc:wc~oAwquwMdlTxiKtqLyiK:|enc:c~vnAamswMvlTor@tjGi}L:|enc:udymA{~bxM:_ " and you can send more points with this method.

This means that your DistanceMatrixRequest could implement the GoogleFunctions.EncodePolyLine, and giving the option to send the coordinates as is, or sending the encoded string as described above.

**Comment by vivet** [comment]
Hi

I will check up on that, cause I can't remember​if my request includes the
possibility of passing encoded coordinates. If not I will add it soon, and
the EncodePolyline function should then work as expected.

**Comment by vivet** [comment]
I will look into this today

**Comment by vivet** [comment]
https://github.com/vivet/GoogleApi/pull/32

**Comment by vivet** [comment]
Added Raw strings for origins and destinations. 
You should be able to format the strings yourself and pass them with the request.

Let me know if you have issues, will close the issue. 
Nuget package will be published a little later.

**Comment by vivet** [comment]
The Nuget is public now.
Let me know if you have issues using the new properties.
