### ISSUE TITLE
Translate code and keep structure

### ISSUE THREAD

**Issue by fasteddys** [vivet/GoogleApi#301]
Hello can we get some help/sample on tranlating code and keep the code structure,

When I try it, the translated doc formatting is lost,  for e.g. new spaces show up  `.`  from `objects.attribute carObject.Drive()` become spaced/tabbed with `objects 
 . attributes -- carObject     .     Drive()`
 
 Also, how can we feed a sub/folder recursively full of files

**Comment by vivet** [comment]
Not sure i understand your issue. Can you post some code?

**Comment by fasteddys** [comment]
Issue 1) I want to translate multiple/bulk files in one go, how can I achieve that?
Issue 2) besides that the issues is that after translation I am loosing formatting in the code and it gets 10X compiler errors because of the space's in the resulting code after & before every period, since it thinks its formatting  and does understand the text is actually code.

![image](https://user-images.githubusercontent.com/96149622/187248563-4576b80a-46a4-47fe-b409-59f0397e045d.png)


I tried several items using google, including other nuggets etc

```
var mySourceCsharpClassInChinese =  System.IO.File.ReadAllText(@"C:\Users\Public\TestFolder\AuthorizeController.cs"); // 
string targetLanguage = "en";
string sourceLanguage = null; // "zh" automatically detected
var client = Google.Cloud.Translation.V2.TranslationClient.Create();
var myResultCsharpClassInENglish = client.TranslateHtml(message, targetLanguage, sourceLanguage);
Console.WriteLine(response.TranslatedText);
```
____________

The issue is that the - result `.cs` file after `parsing/translating` is malformed with spaces and looses the formatting. and structure..
So I tried [this ](https://stackoverflow.com/a/11817023/6085193)before parsing the file from StackOverflow

________
```
private static readonly Regex cjkCharRegex = new Regex(@"\p{IsCJKUnifiedIdeographs}");
public static bool IsChinese(this char c)
{
    return cjkCharRegex.IsMatch(c.ToString());
}
```
```

if (sometext.Any(z=>z.IsChinese()))
     DoSomething();
```

**Comment by vivet** [comment]
Hi

You are mixing things up. You have made an issue for the project GoogleApi, but in the code you are using different package.
Remove the ```Google.Cloud.Translation.V2```, and install GoogleApi NuGet. 
Then use translate as shown below

```csharp
var request = new TranslateRequest
        {
            Key = "your-key",
            Source = Language.English,
            Target = Language.Danish,
            Qs = new[] { "Hello World" }
        };
var result = GoogleTranslate.Translate.Query(request);
```
Hope it helps.

**Comment by vivet** [comment]
I will close the issue
