### ISSUE TITLE
Language Support updates

### ISSUE THREAD

**Issue by dlboutwe** [vivet/GoogleApi#302]
When running tests for the Translate services, I ran into an issue with the code missing the Mizo language ('lus') and thus failing to parse the response. I forked the repo, made some changes, and tested successfully, so I am opening this issue to start the chain of submitting a PR for the fixes in the main code.

**Comment by vivet** [comment]
I will take a look at it

**Comment by vivet** [comment]
I will take a look at the PR, and merge it

**Comment by vivet** [comment]
It's merged, and I published updated version. Should be on NuGet in 5-10 min
