### ISSUE TITLE
AddressGeocodeRequest

### ISSUE THREAD

**Issue by robertovaldesperez** [vivet/GoogleApi#308]
Hi @wormerr @tmpreston @mfeingol @vineus  I am doing a search by address to this address: MADRID, 12, Teulada, Alacant/Alicante, España

`var response = GoogleMaps.Geocode.AddressGeocode.Query(new GoogleApi.Entities.Maps.Geocoding.Address.Request.AddressGeocodeRequest()
                {
                    Address = MADRID, 12, Teulada, Alacant/Alicante, España,
                    Key = Settings.AppSettings.GoogleAPIKey,
                    Components = components,
                    Bounds = new GoogleApi.Entities.Common.ViewPort(new GoogleApi.Entities.Common.Coordinate(38.693202745000065, 0.079237274000036), new GoogleApi.Entities.Common.Coordinate(38.749154471000054, 0.13939934100005758))
                });`

but google is returning another address outside the viewport

![image](https://user-images.githubusercontent.com/15571467/200956151-cc662aac-0dc5-49c7-a621-12ff3f1936fc.png)

Can you help me? Thanks a lot.

**Comment by vivet** [comment]
If I remember correctly, that can happen from Google 's side.
Anyway, this is more a question for Google and not something this library can do anything about.

Will close the issue.
