### ISSUE TITLE
Interface for dependency injection and mocking

### ISSUE THREAD

**Issue by robosheep95** [vivet/GoogleApi#309]
Hi, I am trying to write unit tests for my application. When using dependency injection, it seems like I have to use the concrete type `GooglePlaces.DetailsApi`. As I don't actually want to call google when running unit tests, could an interface be created for dependency injection and mocking.

Thanks!

**Comment by vivet** [comment]
I can look into adding that, though I won't be right away. 
I am quite busy at the moment.

Feel free to submit a pull-request. You can just implement it for one api and I can duplicate it fast.
Otherwise create a wrapper class for now, that you can mock.

**Comment by vivet** [comment]
I got a bit of extra time, and decided to implement the interfaces :-)
You should now be able to easier mock the Query methods
