### ISSUE TITLE
Missing NR radio type enum

### ISSUE THREAD

**Issue by MaxwellDAssistek** [vivet/GoogleApi#311]
The enum `GoogleApi.Entities.Maps.Geolocation.Request.Enums.RadioType` is missing the NR radio type.

See official documentation: https://developers.google.com/maps/documentation/geolocation/overview#body

**Comment by vivet** [comment]
I will look into adding it.
Thanks for reporting it 😄

**Comment by vivet** [comment]
I will come in the version 4.3.0 coming this weekend.
