### ISSUE TITLE
Injected objects should favor Transient or Scoped lifetime

### ISSUE THREAD

**Issue by bobbyangers** [vivet/GoogleApi#315]
Please consider using AddTransient[TService, TClient]., `TClient` is a _singleton_ and properly manages the threading and websockets, so the instance being **injected** should avoid singleton.

`GoogleApi/Extensions/ServiceCollectionExtensions.cs`
```csharp
        services
            .AddSingleton<TService, TClient>();
```

Unless there is a strong case for using **Singleton**;  one should favor **Transient** or **Scoped** lifetime.

**Comment by vivet** [comment]
You are right, I am just so fond of Singletons :-)
I have merged your PR, and published updated NuGet.
