### ISSUE TITLE
PlacesAutoCompleteRequest: locationbias

### ISSUE THREAD

**Issue by markszente** [vivet/GoogleApi#318]
Hello,

It is not currently possible to add [`locationbias`](https://developers.google.com/maps/documentation/places/web-service/autocomplete#locationbias) to [`PlacesAutoCompleteRequest`](https://github.com/vivet/GoogleApi/blob/ce312d8d222712522f422ef6521856d72de28082/GoogleApi/Entities/Places/AutoComplete/Request/PlacesAutoCompleteRequest.cs).

> Prefer results in a specified area, by specifying either a radius plus lat/lng, or two lat/lng pairs representing the points of a rectangle. If this parameter is not specified, the API uses IP address biasing by default.
>
> **IP bias**: Instructs the API to use IP address biasing. Pass the string `ipbias` (this option has no additional parameters).
**Point**: A single lat/lng coordinate. Use the following format: `point:lat,lng`.
**Circular**: A string specifying radius in meters, plus lat/lng in decimal degrees. Use the following format: `circle:radius@lat,lng`.
**Rectangular**: A string specifying two lat/lng pairs in decimal degrees, representing the south/west and north/east points of a rectangle. Use the following format: `rectangle:south,west|north,east`. Note that east/west values are wrapped to the range -180, 180, and north/south values are clamped to the range -90, 90.

(emphasis and code highlight by me)

Is there any chance you could add it? It would be much appreciated, especially the point type. Thanks!

**Comment by vivet** [comment]
Hi 
I will add it. Probably within the next couple of days.

**Comment by vivet** [comment]
I have implemented both the location-bias and the location-restriction. 
Something is just strange of how Google implemented this, because there seem to be multiple way of accomplishing the same. Nevertheless, you now have all the options Google supports.

I will deploy an updated NuGet soon

**Comment by markszente** [comment]
Agreed, the docs seem to be  somewhat ambiguous and even contradictory. Anyway, thank you!

**Comment by vivet** [comment]
Yes, I will need to revisit my implementation, so I will need a few more days

**Comment by vivet** [comment]
I completed the implementation.
I can't say that it will work 100%. As mentioned, the documentation is a bit misleading, and seems copied from the Places Search Find api (some texts on the page clearly shows this). I keep getting bad request when trying point:lat/lng for the Bias, and it should be straight forward, possibly returning ZERO_RESULTS. 

New NuGet published v4.4.0, it should be available in 10-15 min.
