### ISSUE TITLE
GoogleApiException: "Could not parse tourist_attraction"

### ISSUE THREAD

**Issue by mfeingol** [vivet/GoogleApi#319]
This is a regression in 4.3.0 and it is still reproducible in 4.3.2. It works in 4.2.6.

The following code results in a GoogleApiException: "Could not parse tourist_attraction":

```c#
LocationGeocodeRequest request = new LocationGeocodeRequest
{
    Key = this.apiKey,
    Location = new(37.139328, -113.605431),
};
GeocodeResponse response = await GoogleMaps.Geocode.LocationGeocode.QueryAsync(request, default);
```

**Comment by vivet** [comment]
I will add the missing enum

**Comment by vivet** [comment]
New Nuget published v4.4.0, it should be available in 10-15 min

**Comment by mfeingol** [comment]
Thanks for this, @vivet. However, with 4.4.0 I'm now seeing a similar issue with `38.1864717,-109.9743631`:


$exception | {"Could not parse campground"} | GoogleApi.Exceptions.GoogleApiException

Do you need to add all the entries in this list?

https://developers.google.com/maps/documentation/places/web-service/supported_types

**Comment by vivet** [comment]
Yes I need to add them all, but it's a but strange. Google's documentation seems incorrect, because the types list your are referring to should not be part of address-component-types for Geocoding, that is the second table from your link. 

Anyhow, I will add them all.

**Comment by vivet** [comment]
I have added all the possible address component types, and also made a fallback to Unknown.

An updated Nuget v4.5.0 should be available in 5-10 min

**Comment by mfeingol** [comment]
Seems to be working. Thank you!!
