### ISSUE TITLE
Geocoding with small numbers results in a 400 bad request

### ISSUE THREAD

**Issue by johnkamau** [vivet/GoogleApi#320]
Hi,
Seems .net automatically converts small numbers into scientific notation so a location such as -0.000004, 34.5259883333333 becomes 4E-05, 34.5259883333333, trying to lookup the double 4e-05 results in the "bad request" error. Might have to change the datatype for the location class' Latitude and Longitude to decimal or format it before sending the request to google?

**Comment by vivet** [comment]
I will implement a fix

**Comment by johnkamau** [comment]
Ok. Thanks for the quick reply.

**Comment by vivet** [comment]
New Nuget published v4.4.0, it should be available in 10-15 min
