### ISSUE TITLE
Google Places Autocomplete API missing region parameter

### ISSUE THREAD

**Issue by dslCarl** [vivet/GoogleApi#323]
Hi

I have just downloaded this nuget package, to use a few of its services, one being the Place Autocomplete.
However, I need to be able to specify a region but this is missing from the PlacesAutoCompleteRequest

Many thanks
Carl Thomas

**Comment by vivet** [comment]
I will add it.
Not sure why i have missed that, maybe it's new

**Comment by vivet** [comment]
I have added it, and published an updated NuGet v4.5.1. 
Should be available in 5-10 min

**Comment by dslCarl** [comment]
That's great thank you for a speedy response.
