### ISSUE TITLE
Question about address geocode query

### ISSUE THREAD

**Issue by robertovaldesperez** [vivet/GoogleApi#328]
Hi @wormerr @tmpreston @mfeingol @vineus  One question, when I send the components locality, province, country, etc. Is it necessary to add them to the address too?

Something like this:

`var response = GoogleMaps.Geocode.AddressGeocode.Query(new GoogleApi.Entities.Maps.Geocoding.Address.Request.AddressGeocodeRequest()
                    {
                        // Street_Address, Street_Number, Postal_Code Locality, Province, Country
                        // eg.: C. Teulada, 12, 03009 Alicante (Alacant), Alicante, Spain
                        Address = string.Format("{0}, {1}{2}, {3}, {4}", address, zipCode?.Concat(" ") ?? string.Empty, locality ?? string.Empty, province ?? string.Empty, country ?? string.Empty)?.Replace(", ,", ",").Trim(new char[] { ' ', ',' })?.RemoveExcessSpaces(),
                        Key = Settings.AppSettings.GoogleAPIKey,
                        Components = components
                    });`

Thanks a lot

**Comment by vivet** [comment]
Hi
I wouldn't think so, but that is more a question for Google.
