### ISSUE TITLE
GeocodingResponse not contained in new assembly

### ISSUE THREAD

**Issue by renhammington** [vivet/GoogleApi#33]
Hi there

Love your work. Really great API. Hey I've just upgraded to the latest nuget package and have a whole bunch of errors related to GeocodingResponse not being contained in the assembly. Is there something I'm doing wrong, or is this a legit bug?

Cheers
Ren.

**Comment by vivet** [comment]
I will take a look.
It's the 4.5 framework ?

**Comment by vivet** [comment]
I have made a new build, and published nuget package.
I couldn't reproduce the problem, so I basically just rebuilt the source. 

Check if it works with latest Nuget, otherwise i will rebuilt the .net45 assembly from scratch

**Comment by vivet** [comment]
I will close the issue.
Soon i will be done with v.3.0, and it shouldn't be a problem then,
Let me know if you still have issues, then I will assist you in fixing it.
