### ISSUE TITLE
`Establishment` missing from `LocationResultType`?

### ISSUE THREAD

**Issue by boyum** [vivet/GoogleApi#330]
Hi!

In version 4.5.2, `LocationGeocodeRequest.ResultTypes` is no longer an `IEnumerable<PlaceLocationType>`, but rather an `IEnumerable<LocationResultType>`. This seems to be fine in most cases, however we were using `PlaceLocationType.Establishment` previously, and it seems not to be part of `LocationResultType`. Is this a bug? I don't know much about Google's APIs, but it seems that `establishment` is still part of theirs: https://developers.google.com/maps/documentation/places/web-service/supported_types#table2

If this is a bug, I'll be happy to create a PR to fix it.

**Comment by vivet** [comment]
Hi

As far as I can see from the Google documentation, ```Establishment``` is not part of the supported types. 
Check the result-type parameter here: https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding.

Let me know if you see different documentation somewhere, and I will gladly change the library.

**Comment by vivet** [comment]
I haven't heard back from you, so I will close the issue.
Feel free to re-open the issue, if you still think there is a bug.
