### ISSUE TITLE
Google Place Api

### ISSUE THREAD

**Issue by ww1123dd** [vivet/GoogleApi#331]
How to use Google Place Api in Unity3D? I want try to use it in my input field. Just like the Uber when user enter their address or destination it will automatically show the whole addrees or destination to the user.

**Comment by vivet** [comment]
I think you need to learn about Google's api's, and then this library should be easy to consume and use.

Start by reading about Google places auto complete.

Otherwise, helping with specific use cases and implementations is out of scope for me, but there should be plenty of help to find on the internet.

Good luck.

**Comment by ww1123dd** [comment]
but on the internet all is JavaScript not c#

**Comment by ww1123dd** [comment]
> I think you need to learn about Google's api's, and then this library should be easy to consume and use.
> 
> Start by reading about Google places auto complete.
> 
> Otherwise, helping with specific use cases and implementations is out of scope for me, but there should be plenty of help to find on the internet.
> 
> Good luck.

But on the internet all is JavaScript not C#

**Comment by vivet** [comment]
Try check out the GoogleApi test project for various examples.

**Comment by ww1123dd** [comment]
The code you posted here can use in Unity?

**Comment by angelru** [comment]
@ww1123dd I have the autocompletion functionality implemented in my .net maui application and this library, I leave you the code:

```
        private async Task SearchPlaceAsync()
        {
            var placesAutoCompleteRequest = new PlacesAutoCompleteRequest
            {
                Key = Settings.GoogleKey,
                Input = "input place search",
                Components = new Dictionary<Component, string>
                {
                    { Component.Country, "es" }
                },
                Language = Language.Spanish
            };

            var placesAutoCompleteResponse = await GooglePlaces.AutoComplete.QueryAsync(placesAutoCompleteRequest);

            SearchResults.ReplaceRange(placesAutoCompleteResponse.Predictions);
        }


private async Task SelectedPredictionPlaceAsync()
        {
            var placesDetailsRequest = new PlacesDetailsRequest
            {
                Key = Settings.GoogleKey,
                PlaceId = _selectedPrediction.PlaceId,
                Language = Language.Spanish
            };

            placesDetailsResponse = await GooglePlaces.Details.QueryAsync(placesDetailsRequest);
        }
```

**Comment by angelru** [comment]
> > @ww1123ddTengo implementada la funcionalidad de autocompletado en mi aplicación .net maui y esta biblioteca, les dejo el código:
> > ```
> >        private Prediction _selectedPrediction;
> >         public Prediction SelectedPrediction
> >         {
> >             get => _selectedPrediction;
> >             set => SetProperty(ref _selectedPrediction, value);
> >         }
> > 
> >         public ObservableRangeCollection<Prediction> SearchResults { get; set; } = new ObservableRangeCollection<Prediction>();
> > 
> >         private async Task SearchPlaceAsync()
> >         {
> >             var placesAutoCompleteRequest = new PlacesAutoCompleteRequest
> >             {
> >                 Key = Settings.GoogleKey,
> >                 Input = "input place search",
> >                 Components = new Dictionary<Component, string>
> >                 {
> >                     { Component.Country, "es" }
> >                 },
> >                 Language = Language.Spanish
> >             };
> > 
> >             var placesAutoCompleteResponse = await GooglePlaces.AutoComplete.QueryAsync(placesAutoCompleteRequest);
> > 
> >             SearchResults.ReplaceRange(placesAutoCompleteResponse.Predictions);
> >         }
> > 
> >         public IAsyncCommand SelectedPredictionAsyncCommand => CommandFactory.Create(SelectedPredictionPlaceAsync, allowsMultipleExecutions: false);
> > private async Task SelectedPredictionPlaceAsync()
> >         {
> >             var placesDetailsRequest = new PlacesDetailsRequest
> >             {
> >                 Key = Settings.GoogleKey,
> >                 PlaceId = _selectedPrediction.PlaceId,
> >                 Language = Language.Spanish
> >             };
> > 
> >             placesDetailsResponse = await GooglePlaces.Details.QueryAsync(placesDetailsRequest);
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adáptalo a la UNIDAD.
> 
> Gracias😊 ¿Mostrará la sugerencia cuando el usuario ingrese la dirección? Justo como esto ![Captura de pantalla_2023-03-15-00-14-36-857-edit_com android cromo](https://user-images.githubusercontent.com/116745457/225069258-6f25c1ae-7f4f-41b1-beaa-fba68b0a9094.jpg)

Yes, you have to do it:

In my application I have a search box and below a list control and in the search event I implement the code that I show you.
