### ISSUE TITLE
Change WayPoint.PartialMatch to boolean

### ISSUE THREAD

**Issue by RobinVangampelaere** [vivet/GoogleApi#333]
In the code this is a string, but the JSON response from Google is a boolean. The JSON parser crashes on the property.

Namespace: GoogleApi.Entities.Maps.Directions.Response.WayPoint
Property: PartialMatch
Error: Cannot get the value of a token type 'True' as a string

Solution: Change type from string to boolean.

**Comment by vivet** [comment]
I will fix it soon
