### ISSUE TITLE
Do you think it's possible to change the Language to string type?

### ISSUE THREAD

**Issue by garryxiao** [vivet/GoogleApi#334]
I think it's a better idea to pass string instead of Language enum to avoid transformations. But it's a break change.
Otherwise, is it possbile to add such cases? (That's also a reason to get rid of such things. :)

"zh-Hans" => Language.ChineseSimplified,
"zh-Hant" => Language.ChineseTraditional,

Thanks.

**Comment by vivet** [comment]
Sorry, i prefer enums
