### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ww1123dd** [vivet/GoogleApi#335]
When I use your code in Unity and I get a lot of errors. How to fix this?
![image](https://user-images.githubusercontent.com/116745457/225688049-da53909e-8742-4c08-be66-f26584eadd50.png)

**Comment by vivet** [comment]
See #326

**Comment by ww1123dd** [comment]
I don't get it a bit confuse

**Comment by vivet** [comment]
Issue #326 is the same problem
