### ISSUE TITLE
'The converter specified on 'GoogleApi.Entities.Common.Enums.Status' does not derive from JsonConverter or have a public parameterless constructor.'

### ISSUE THREAD

**Issue by sion-corn** [vivet/GoogleApi#336]
Hi there,

I am using GoogleApi version 4.5.4

I have an aspnetcore7 Blazor WASM app that calls an aspnetcore7 API. I have no issues getting the endpoint to return a valid `PlacesDetailsResponse`. My issue comes from trying to read the response from Json in the WASM app: `var placeDetails = await result.Content.ReadFromJsonAsync<PlacesDetailsResponse>();`

My endpoint:
```
[ApiExplorerSettings(IgnoreApi = true)]
[HttpGet]
[Route("get-place-details")]
[ProducesResponseType(StatusCodes.Status200OK)]
public async Task<IActionResult> GetPlaceDetails(
    [FromQuery] string placeId, 
    CancellationToken cancellationToken)
{
    _logger.LogInformation($"GetPlaceDetails attempt for {placeId} ");
    if (!ModelState.IsValid)
    {
        _logger.LogError($"Invalid GET attempt in {nameof(GetPlaceDetails)}");
        return BadRequest(ModelState);
    }
    try
    {
        PlacesDetailsRequest placesDetailsRequest = new PlacesDetailsRequest
        {
            Key = _apiKey,
            PlaceId = placeId
        };
        PlacesDetailsResponse? placesDetailsResponse = await _detailsApi.QueryAsync(placesDetailsRequest, cancellationToken);

        return Ok(placesDetailsResponse);
    }
    catch (TaskCanceledException tce)
    {
        return NoContent();
    }
}
```

My request:
```
var result = await LocationService.GetPlaceDetails(Configuration.Application.BaseUrlApi, payload.GoogleResult.PlaceId, base.CancellationTokenSource.Token);
if (result.StatusCode == System.Net.HttpStatusCode.OK)
{                
    try
    {
        var placeDetails = await result.Content.ReadFromJsonAsync<PlacesDetailsResponse>();
    }
    catch (Exception ex)
    {
        var message = ex.Message;
    }
}
```

The error (caught in WASM app's "catch" block above):
`'The converter specified on 'GoogleApi.Entities.Common.Enums.Status' does not derive from JsonConverter or have a public parameterless constructor.'`

**Comment by vivet** [comment]
It looks like you are using the PlaceDetailsResponse directly as model returned from your controller action. GoogleApi is not in control of this, and you should probably use your own model to return.

**Comment by sion-corn** [comment]
Ok, I suppose I will create a DTO for it. Is there a reason why it is not best practice to use PlaceDetailsResponse directly?

**Comment by vivet** [comment]
I would argue that it's never good to use a DTO from a NuGet, you sre not in control of it, and in a database or at REST, that would change your application. Also you should just expose what you need for your use case, which is probably not the entire PlaceDetailsResponse.

**Comment by sion-corn** [comment]
fair enough, will do.
