### ISSUE TITLE
Direction API Polyline Quality

### ISSUE THREAD

**Issue by kadirgedik** [vivet/GoogleApi#339]
I couldn't see a parameter for "**polylineQuality**" in the **DirectionRequest** object. Any chance of adding? I think it is a very important request parameter.

**Comment by vivet** [comment]
Off course

**Comment by kadirgedik** [comment]
You can see it here;
https://developers.google.com/maps/documentation/routes/config_trade_offs?hl=tr#polyline-quality

**Comment by vivet** [comment]
Hi 

I merged your PR to do review on your implementation. 
First you are wrong about the polylineQuality parameter for Directions api, it doesn't exists, so I have reverted your change.

The polylineQuality is part of a newer routes api 
https://developers.google.com/maps/documentation/routes/overview

I have added issues for implementing that api.

**Comment by kadirgedik** [comment]
Hello

After reading the documents better, I realized that it really is. Thank you for your attention.
