### ISSUE TITLE
Use Official BouncyCastle package

### ISSUE THREAD

**Issue by MaxwellDAssistek** [vivet/GoogleApi#343]
Please change to use the official Bouncy Castle .Net Standard package: https://www.nuget.org/packages/BouncyCastle.Cryptography

This should be used instead of the Portable.BouncyCastle package that this currently depends on. You can see that this is the official .Net Standard version here: https://www.bouncycastle.org/csharp/index.html#RELEASES

The issue is that the Portable.BouncyCastle package that GoogleApi depends on has the same namespaces as the official package so the implicit dependency conflicts with the official BouncyCastle.Cryptography.

**Comment by vivet** [comment]
I will take a look at it

**Comment by vivet** [comment]
Actually wait a bit, I forgot to remove the old NuGet, why it built without issues :-)

**Comment by vivet** [comment]
I managed to remove the dependency all together. 
Can you verify that the change works for you?, then I will publish a NuGet update
