### ISSUE TITLE
WASM compatibility?

### ISSUE THREAD

**Issue by pm64** [vivet/GoogleApi#345]
Because this library attempts to set the Proxy property on the BrowserHttpHandler class, it is sadly not compatible with Blazor WebAssembly. I don't personally have a solution to offer. Is WASM support currently under consideration?

**Comment by vivet** [comment]
Hi
I think there was another user that had the same issue. I can't remember how we solved it. Can you find that issue in closed issues, and see if the solution works for you. Otherwise, paste the issue number in this ticket, and I can see if we can come up with a solution

**Comment by vivet** [comment]
I would think this issue is similar: https://github.com/vivet/GoogleApi/issues/291

**Comment by vivet** [comment]
I will close this issue as I think it's a duplicate. Feel free to comment and re-open if you disagree
