### ISSUE TITLE
Add RouteModifiers to RoutesMatrix

### ISSUE THREAD

**Issue by RASK18** [vivet/GoogleApi#352]
Hi! Could you please add the 'routeModifiers' field to the Routes api? (RoutesMatrixRequest)
Thank you very much, I love this repo

https://developers.google.com/maps/documentation/routes/route-modifiers

**Comment by vivet** [comment]
It's already there 
https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Maps/Routes/Matrix/Request/RouteMatrixOrigin.cs#L20

**Comment by RASK18** [comment]
Oh! Sorry, as in DistanceMatrix is a global field and in the documentation of this also comes out like that, being at the same level as origins, I did not think to look for it within each origin. Ok, so I'll make a loop or something to add it to all origins, thank you very much :)

**Comment by vivet** [comment]
It is placed on tve origins, not at root level
