### ISSUE TITLE
Error with Microsoft.Extensions.Http, Version=7.0.0.0 on .net 6 projects

### ISSUE THREAD

**Issue by fabiansanchez18** [vivet/GoogleApi#354]
I use this package on an Azure Function project that runs .net 6 code because is the current LTS version supported by it.
This packages is Multi Framework on its build and nuget package information, but the nuget packages referenced by it are only for .net 7.

you can fix this by adding this to the project file, so it is reflected on the nuget packages downloaded when our apps are building:

	<ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
		<PackageReference Include="System.Text.Json" Version="7.0.2" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' != 'net7.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
		<PackageReference Include="System.Text.Json" Version="6.0.7" />
	</ItemGroup>

**Comment by vivet** [comment]
hmm that's strange cause the 7.0 packages supports net6.0.
Seems something else is the issue, or there is a bug in the 7.0 libraries from MS

**Comment by fabiansanchez18** [comment]
no. the 7.0 packages does support net6.0. but on closed cloud environments like Azure, you have to select the Framework you are running your software. mine is on .net 6.0 because to upgrade it to 7.0 i have to rewrite most of it because they change some core requirements on their side.
this close environment won't load .net 7.0 packages. that happens also with EntityFramework and other libraries.
with the configuration I put before on the .csproj file it builds and runs perfectly

**Comment by fabiansanchez18** [comment]
i have an internal Nuget package on Azure DevOps and this is the configuration I use to make it multiframework, because I have softwares sharing it on .net 7 and 6 at the same time. it uses EntityFramework. 
to the nuget configuration show a package is multiframework, you have to declare the frameworks on the tag hat you have already done. but the dependecies check the tags that I have put hear. when you publish with that, you will notice on Nuget how the dependencies will change and show all those packages. that will make it really multiframework

**Comment by vivet** [comment]
I will look at it.
Though i will probably set the condition equals 6.0

**Comment by vivet** [comment]
I changed the NuGets.
Can you try out this branch and see if it works for you.
https://github.com/vivet/GoogleApi/tree/ISSUE_354

**Comment by fabiansanchez18** [comment]
Yes. It works. Thank you.

**Comment by vivet** [comment]
An updated NuGets is published
