### ISSUE TITLE
Is computeHeading anywhere?

### ISSUE THREAD

**Issue by SykesJohn** [vivet/GoogleApi#357]
I need to call google.maps.geometry.spherical.computeHeading. Is that supported anywhere in the API? If so, where would I find it?

**Comment by vivet** [comment]
Do you have en link for the api

**Comment by SykesJohn** [comment]
Do you mean this:
Geometry Library  |  Maps JavaScript API  |  Google for Developers<https://developers.google.com/maps/documentation/javascript/geometry>
?

**Comment by vivet** [comment]
Yes exactly.
But notice it's Javascript library.

**Comment by SykesJohn** [comment]
So, there is no equivalent in the GoogleApi library?

**Comment by vivet** [comment]
No cause there is no api from Google to support that
