### ISSUE TITLE
Could not parse depart

### ISSUE THREAD

**Issue by csipi94** [vivet/GoogleApi#360]
With 5.0.2 version I got the following error in GoogleMaps.Routes.RoutesDirectionsApi API:
GoogleApi.Exceptions.GoogleApiException: Could not parse depart

Related code:

        var request = new RoutesDirectionsRequest
        {
            Key = GetApiKey(),
            Origin = new LocationEx(new CoordinateEx(origin.Latitude, origin.Longitude)),
            Destination = new LocationEx(new CoordinateEx(destination.Latitude, destination.Longitude))
        };

        var response = await GoogleMaps.Routes.RoutesDirectionsApi.QueryAsync(request); <-- Here

This is a regression bug.

**Comment by vivet** [comment]
Can you send the request you are using

**Comment by csipi94** [comment]
Sure!

Example body: 
{
  "origin": {
    "location":{
      "latLng":{
        "latitude": 37.419734,
        "longitude": -122.0827784
      }
    }
  },
  "destination":{
    "location":{
      "latLng":{
        "latitude": 37.417670,
        "longitude": -122.079595
      }
    }
  }
}

**Comment by vivet** [comment]
Something is odd with your request.
Your request is for maps Directions, but you invoke maps routes directions. This shouldn't even build, not sure how you can make it build.

**Comment by vivet** [comment]
The routes directions api doesn't used the LocationEx, but RoutesWayPoint

**Comment by csipi94** [comment]
Yeah sorry I copied a wrong request.

```
var request = new RoutesDirectionsRequest
{
    Origin = new GoogleApi.Entities.Maps.Routes.Common.RouteWayPoint
    {
        Location = new GoogleApi.Entities.Maps.Routes.Common.RouteLocation
        { LatLng = new GoogleApi.Entities.Maps.Common.LatLng { Latitude = 47.55559845714549, Longitude = 19.090552095733678 } }
    },
    Destination = new GoogleApi.Entities.Maps.Routes.Common.RouteWayPoint
    {
        Location = new GoogleApi.Entities.Maps.Routes.Common.RouteLocation
        { LatLng = new GoogleApi.Entities.Maps.Common.LatLng { Latitude = 47.51028604307189, Longitude = 19.056111483223916 } }
    }
};
request.Key = GetApiKey();

var response = await GoogleMaps.Routes.RoutesDirectionsApi.QueryAsync(request); <-- Here
```

**Comment by vivet** [comment]
Google had added a new maneuver value "DEPART". 
I have fixed it and published an updated NuGet
