### ISSUE TITLE
Please expose CurrentOpeningHours

### ISSUE THREAD

**Issue by jkuek** [vivet/GoogleApi#363]
I'm hoping to get the current_opening_hours instead of opening_hours

see https://developers.google.com/maps/documentation/places/web-service/details#Place-current_opening_hours

**Comment by vivet** [comment]
I will update the response.
Thanks for reporting it.

**Comment by jkuek** [comment]
Hi,

Please also add "date" to PlaceOpeningHoursPeriodDetail https://developers.google.com/maps/documentation/places/web-service/details#PlaceOpeningHoursPeriodDetail-date

I'm trying to find the opening hours for today for the business.

**Comment by vivet** [comment]
There are several new properties on the details response. I will add them all

**Comment by vivet** [comment]
I have published an updated NuGet, where the Place Details and Find response has been aligned with latest additions / changes by Google.

**Comment by jkuek** [comment]
Thanks!
