### ISSUE TITLE
Several RouteDirections unit tests are failing.

### ISSUE THREAD

**Issue by SykesJohn** [vivet/GoogleApi#364]
I see a number of unit tests failing for directions in net7.0. I am specifically looking for ComputeRoute, but there are 12 failures under GoogleApi.Test.Maps.Routes.Directions when I run the net7.0 tests.

Can you reproduce? If so, is there any plan to rectify?

**Comment by vivet** [comment]
Some tests can be a bit unstable as google sometimes changes the result a bit, but it could look like you are missing adding an api-key?

Otherwise try post more details about the asserts that fail

**Comment by SykesJohn** [comment]
I will try. It is not the API key because I am getting valid JSON back from Google but the library can’t parse the result. It can’t parse the enum “depart” at line 91 in EnumJsonConverter of type “Maneuver”. This is from ProcessResponseAsync in HttpEngine line 190.

**Comment by SykesJohn** [comment]
I added this to the Maneuver enum and the tests are not passing:


              /// <summary>
              /// Depart
              /// </summary>
    [EnumMember(Value = "DEPART")]
              Depart

**Comment by vivet** [comment]
When I run the tests, they succeed. 
Have you changed the requests in one or more of the tests? Maybe you are getting a different result, that somehow can't be serialized. If you did, can you send the request, then I can try that out.

**Comment by vivet** [comment]
Not sure how you are using GoogleApi, but it seems lie you are using the models in GoogleApi as you own contracts.
Nevertheless, the library doesn't need the write methods while they are not implemented.

I will close the issue.
