### ISSUE TITLE
Direcions  typo

### ISSUE THREAD

**Issue by CagatayCanK** [vivet/GoogleApi#366]
Hey, 
new Routes API has typo, class is called "Direcions" instead of "Directions".

Example, [file](https://github.com/vivet/GoogleApi/blob/master/.tests/GoogleApi.Test/Maps/Routes/Directions/RouteDirectionsTests.cs):
`GoogleMaps.Routes.Direcions.QueryAsync(request);`

**Comment by vivet** [comment]
Will fix it

**Comment by vivet** [comment]
Updated NuGet v5.1.1 published
