### ISSUE TITLE
Could not parse namE_CHANGE

### ISSUE THREAD

**Issue by csipi94** [vivet/GoogleApi#367]
With 5.1.0 version I got the following error in GoogleMaps.Routes.RoutesDirectionsApi API:
GoogleApi.Exceptions.GoogleApiException: Could not parse namE_CHANGE

Related code:

var request = new RoutesDirectionsRequest
{
    Origin = new GoogleApi.Entities.Maps.Routes.Common.RouteWayPoint
    {
        Location = new GoogleApi.Entities.Maps.Routes.Common.RouteLocation
        { LatLng = new GoogleApi.Entities.Maps.Common.LatLng { Latitude = 47.55559845714549, Longitude = 19.090552095733678 } }
    },
    Destination = new GoogleApi.Entities.Maps.Routes.Common.RouteWayPoint
    {
        Location = new GoogleApi.Entities.Maps.Routes.Common.RouteLocation
        { LatLng = new GoogleApi.Entities.Maps.Common.LatLng { Latitude = 47.51028604307189, Longitude = 19.056111483223916 } }
    }
};
request.Key = GetApiKey();

var response = await GoogleMaps.Routes.RoutesDirectionsApi.QueryAsync(request); <-- Here

This is a regression bug.

**Comment by vivet** [comment]
I have added the missing Enum.
Updated NuGet v5.1.1 published
