### ISSUE TITLE
Property for Waypoint Optimization in RoutesDirectionRequest

### ISSUE THREAD

**Issue by markus-renezeder** [vivet/GoogleApi#368]
Please add a bool proeprty to the RoutesDirectionRequest named optimizeWaypointOrder.

This would enable the feature waypoint optimization.

Further information: https://developers.google.com/maps/documentation/routes/opt-way?hl=de

Btw.: thank's for the API! Great job!

**Comment by vivet** [comment]
I will take a look at it.
Seems it's not the only property Google have added recently, and also the response has some related new properties.

I expect to publish an update it tomorrow.

**Comment by markus-renezeder** [comment]
Thank you very much.

I've tried the query using postman. It's only necessary to set the property to true and include "optimized_intermediate_waypoint_index" into the fieldlist.

The result contains "optimizedIntermediateWaypointIndex". This is an array with the new sort order of the way points.

**Comment by vivet** [comment]
True, but I can see google expanded the response with additional fields. I will add those as well, and also check routes matrix.

**Comment by vivet** [comment]
It will take a few more days to complete

**Comment by vivet** [comment]
It's done.
Version 5.2.0 published.

**Comment by markus-renezeder** [comment]
Great! Thank you very much!
