### ISSUE TITLE
Retry policy

### ISSUE THREAD

**Issue by wilsonneto-dev** [vivet/GoogleApi#372]
Hi, great package! Thanks for that!

Is a retry policy (maybe with Polly), a good call for the package? I didn`t see retry policies, so I would like to check.
How can I deal with retries? Also, are there plans for adding it? (I can try to contribute with a PR on that if there are plans)

Thank you very much!

**Comment by vivet** [comment]
Sorry, I don't think that should be part of the package.
I never had any issues, but if you need retries I suggest you just wrap you calls yourself.

**Comment by wilsonneto-dev** [comment]
Perfect, thanks!
