### ISSUE TITLE
Routing API "GeocodingResults" doesn't seem to be a collection?

### ISSUE THREAD

**Issue by ChairmanMawh** [vivet/GoogleApi#373]
API docs says: 
![image](https://github.com/vivet/GoogleApi/assets/118385137/e261535a-4f49-4125-807c-a1ec6f01d011)
https://developers.google.com/maps/documentation/routes/reference/rest/v2/TopLevel/computeRoutes#response-body

Library code says:
![image](https://github.com/vivet/GoogleApi/assets/118385137/3e4c85e0-cf2f-4037-8e2d-329dc62a10aa)

I get an exception when deser'ing GeocodingResults. Changing the type so it is not enumerable allows deser to succeed:

![image](https://github.com/vivet/GoogleApi/assets/118385137/693dd835-8388-46f1-adac-8700fe47b887)

**Comment by vivet** [comment]
Will take a look at it

**Comment by vivet** [comment]
It's fixed, and updated NuGet published.
