### ISSUE TITLE
.NET 7.0 - iOS - Operation is not supported on this platform.

### ISSUE THREAD

**Issue by Nguyenthanhtoa** [vivet/GoogleApi#376]
Hi @vivet ,

I'm facing an issue when using GoogleApi v5.2.4 that cannot query data from GooglePlaces Auto Complete on .NET 7.0

**Steps to reproduce:**
1. Create .NET MAUI app (or .NET iOS app) and add package GoogleApi v5.2.4
2. Create a function to query data from GooglePlaces.

Actual result: 
Got exception "Operation is not supported on this platform." when querying data.
Expected result: 
Query data successfully on .NET 7.0
Sample source code:
[GoogleApiMAUI.zip](https://github.com/vivet/GoogleApi/files/13246452/GoogleApiMAUI.zip)

**Last version that worked well**
It's work well on Xamarin.Forms (.NET standard)

**Affected platforms**
iOS only, Android is working properly.

Can you please to take a look and give me an advice.

Thank you
Toa

**Comment by vivet** [comment]
You can try to specify ```false``` for the ```useHttpClientHandler``` parameter when registering ```AddGoogleApiClients()```.
 
Otherwise, I am not sure what you can do. I don't work with frontends, sorry

**Comment by Nguyenthanhtoa** [comment]
Many thanks for your quick response.
I will try on this and take further investigating on the source code library.

**Comment by PontusHolmberg** [comment]
@Nguyenthanhtoa How did you fix this?

**Comment by Nguyenthanhtoa** [comment]
Hi @PontusHolmberg,
I used the REST api to fetch the places data instead of library.
Reference: https://developers.google.com/maps/documentation/places/web-service/autocomplete
Feel free to ping me if you have any trouble when intergrating the REST api, I can share the sample code in .NET MAUI.

**Comment by remi-appsolu** [comment]
> @Nguyenthanhtoa Oh, okey. I actually solved the issue it self. Turns out that SetProxy is not supported by Maui even in .net8. So i changed the HttpClientFactory and removed the Proxy argument when creating a new HttpClientHandler.

Can you explain a little more ? I am facing the same issue in maui but in GoogleMaps.Geocode.LocationGeocode and i never created a HttpClientHandler. Thanks.

**Comment by PontusHolmberg** [comment]
@remi-appsolu I downloaded/cloned the github project and added it to my VS project, so I could modify the library.
Then inside **HttpClientFactory** you will find the function **GetDefaultHttpClientHandler**.
In there, I just changed
```
var httpClientHandler = new HttpClientHandler
        {
            Proxy = webProxy
        };
```

To
`var httpClientHandler = new HttpClientHandler();`

That way it will never call SetProxy.

**Comment by Nguyenthanhtoa** [comment]
Hi @remi-appsolu ,

As you can see in my issue description, the GoogleApi works properly on Android, but not on iOS. So, my workaround on iOS is using HttpClient to send an request to https://maps.googleapis.com/maps/api/place/autocomplete/json and get the places result like this:
using (var client = new HttpClient())
{
    var path = "https://maps.googleapis.com/maps/api/place/autocomplete/json?input=SEARCH_STRING&key=YOUR_API_KEY&types=(cities)&components=country:YOUR_COUNTRY_CODE";

    HttpResponseMessage response = await client.GetAsync(path);

    if (response.IsSuccessStatusCode)
    {
        var json = await response.Content.ReadAsStringAsync();
        var predictionResponse = JsonConvert.DeserializeObject<PlacePredictionResponse>(json);
        return predictionResponse.Predictions
            .Select(p => new CityOfResidence { Name = p.Description, PlaceId = p.PlaceId })
            .OrderBy(c => c.Name).Take(10).ToList();
    }
}
Do not forget to add Newton.Json & handle exception
Ref: https://developers.google.com/maps/documentation/places/web-service/autocomplete

**Comment by bodeg** [comment]
I tried setting `useHttpClientHandler ` to `false` 
but still getting `PlatformNotSupportedException` on iOS

What am I doing wrong? 

```
builder.Services
  .AddGoogleApiClients(useHttpClientHandler: false);
```

**Comment by Nguyenthanhtoa** [comment]
Hi @bodeg,
On iOS platform, please use HttpClient instead of the library code(see my comment detail in Apr 16)

**Comment by bodeg** [comment]
@Nguyenthanhtoa , thanks for your reply.
I prefer not to maintain my GoogleApi code

I successfully resolved the issue by calling `AddGoogleApiClients` and injecting the api's as dependencies
