### ISSUE TITLE
Calling .Result from QueryAsync either hangs or causes a hard crash

### ISSUE THREAD

**Issue by johnkamau** [vivet/GoogleApi#377]
Hi,
I suspect my issue is related to [this one](https://github.com/vivet/GoogleApi/issues/128) from 2020. Like them, I'm upgrading from an older version that had both .Query() and .QueryAsync(). Most of my code is synchronous so was built like that, modifying it to use await would be quite the task, so I tried just using .QueryAsync().Result, and in asp.net in causes the thread to crash, while in windows forms just freezes the app.

You can try it yourself, create a blank windows forms project, add a button and paste this.

```
Dim Lat =  -6.7813433
            Dim Lng = 39.1853717

            Dim Req As New LocationGeocodeRequest()
            Dim Loc As New Coordinate(Lat, Lng)
            
            With Req
                .Key = "123"
                .Location = Loc
            End With

            
            RetVal = GoogleApi.GoogleMaps.Geocode.LocationGeocode.QueryAsync(req).Result

            If RetVal.Status = Status.Ok Then
                MessageBox.Show(RetVal.Results.Count())
            else
                messagebox.show(retval.errormessage)
            End If
```
Is there something I'm doing wrong I wonder? I presume calling .result should work. My real question is how can this library be used in a synchronous manner?

**Comment by vivet** [comment]
You should just be able to add ```.ConfigureAwait(false)``` after ```QueryAsync(...)```. 
If that doesn't work, I suggest looking into sync over async for .NET

**Comment by vivet** [comment]
Though it's a bad approach, so I would suggest to get on the async train

**Comment by johnkamau** [comment]
In windows forms using async it works, on asp.net however the thread crashes, even when using async. 

The thread 0xbbc4 has exited with code 0 (0x0).

Guess I'll just rollback to the older version for now.

**Comment by vivet** [comment]
Okay, not sure what's causing that.
