### ISSUE TITLE
Getting list of adresses when searching a street

### ISSUE THREAD

**Issue by KeldJ** [vivet/GoogleApi#378]
When using Places endpoint I would like to get a list of adresses within a street. The 

When the input i by example "Odensevej 5750 Ringe" i would get only 1 prediction return instead of a list of adresses on the street which is desired

     var request = new PlacesAutoCompleteRequest
     {
         Key = "",
         Input = mapSearch.StreetName + " " + mapSearch.City + " " + mapSearch.ZipCode,
     };
     var response = await GooglePlaces.AutoComplete.QueryAsync(request);
     return response.Predictions.ToList();

**Comment by vivet** [comment]
Not sure what is too be expecting, but this is more a question for Google.

**Comment by vivet** [comment]
You can inspect the raw json and see what Google returns, in case you think there is a problem with the library.

**Comment by KeldJ** [comment]
Your right its a Google thing
