### ISSUE TITLE
API Key required when Client ID alone should be sufficient

### ISSUE THREAD

**Issue by dbushmanpss** [vivet/GoogleApi#383]
Several of the Google API's accept a client id with request signing, without needing to supply an API key (Geocoding for example).
However, the library currently throws the exception "'Api Key' is required" if you specify client id without an API key. Also, Google states that we should not pass **both** an API key and client id, although it looks like the library would allow that scenario.

Refer to this article from Google:
https://developers.google.com/maps/premium/authentication/overview#available_authentication_methods
The Geocoding API is found on the **Places** tab.

A separate article says it a little differently:
https://developers.google.com/maps/premium/overview
On that page, it states:
> Instead of an API key, you can use your client ID to make requests to any of the APIs except the following: Places API, Geolocation API, Roads API, Maps SDK for Android, and Maps SDK for iOS.

This page mentions that you should not use both an API key and a client id:
https://developers.google.com/maps/premium/faq#developing-your-application_1

It's worth noting that API keys are preferred by Google going forward, making this a low priority issue. I'm only raising the issue because I was given a client id by a co-worker who told me to use it instead of an API key.

**Comment by vivet** [comment]
There are some apis that are accessible without authentication, but as you mention it's best practice to use the apikey, why this library enforces it.

You can also use the clientId, but you should then also use a signed key for the key parameter.

I don't think I will change this, as I think it follows the best practice. Normally, when you want to use the apis without key, it's the Javascript apis.
