### ISSUE TITLE
injecting own functionality

### ISSUE THREAD

**Issue by johnyNeb** [vivet/GoogleApi#384]
Hello,

I am not very experienced with api calls. I am trying to use the injection of one's own logic. What I try to do is compare a regular call of google maps like this:
```
var request = new DirectionsRequest
{
    Key = apiKey,
    Origin = new GoogleApi.Entities.Maps.Common.LocationEx(new CoordinateEx(48.8584, 2.2945)),
    Destination = new GoogleApi.Entities.Maps.Common.LocationEx(new CoordinateEx(48.8529, 2.3499)),
    Language = Language.English,
    Units = GoogleApi.Entities.Maps.Common.Enums.Units.Metric
};

// Send the request and get the response
var response =  await GoogleApi.GoogleMaps.Directions.QueryAsync(request);
```

to a call of a custom api that computes routes and distances, let's call it myRoute

. I tried to search in the unitests if this is checked, so I could imitate it, but didnt find any. Could you help me with this?

**Comment by vivet** [comment]
I am not sure what you are trying to accomplish? What do you mean by "injecting own functionality"? If you want to compare the Google directions result with something else, just invoke both and compare.

**Comment by vivet** [comment]
Check here https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Extensions/ServiceCollectionExtensions.cs#L38
You can see that the ```IDirectionsApi``` is registered and ready for injection in your contructors. 

If you want you can also just use it as it is in the tests, that's fine as well. Just static accessors in facede pattern.

**Comment by vivet** [comment]
I updated the readme for using dependency injection. It was a bit unclear as you experienced.
You just need to inject ```IDrectionsApi``` into your constructor.

Let me know if it makes sense now?

**Comment by johnyNeb** [comment]
i will check it the soonest and let you know. thanks for the fast reply.

**Comment by johnyNeb** [comment]
yes, it is clearer now.
