### ISSUE TITLE
Error when trying to translate a HTML-Text

### ISSUE THREAD

**Issue by markus-renezeder** [vivet/GoogleApi#385]
If I send a HTML string to the google translate API I get the following error message:

GoogleApi.Exceptions.GoogleApiException: "'<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0."

This is the code I use:

```
public async Task<string?> Translate(string? text, GoogleApi.Entities.Translate.Common.Enums.Language language)
{
    try
    {
        if (string.IsNullOrEmpty(text))
            return null;

        TranslateRequest request = new TranslateRequest();

        request.Key = APISettings.APIKey;

        request.Target = language;
        request.Qs = new List<string> { text };
        request.Format = GoogleApi.Entities.Translate.Translate.Request.Enums.Format.Html;

        var result = await TranslateApi.QueryAsync(request);

        var translated = result.Data.Translations?.FirstOrDefault()?.TranslatedText;

        return translated;
    }
    catch(Exception ex)
    {
        string msg = ex.Message;
        return text;
    }
    

}
```

**Comment by vivet** [comment]
But why are sending html? Don't. Html can't be translated.

**Comment by markus-renezeder** [comment]
I wanted to translate a html page. Google supports translating HTML at least the text between the html tags. And the TranslateRequest.Format property mention, that it should be possible.

**Comment by vivet** [comment]
Sorry I see that you are right.
I will see if I can modify the serialization to work

**Comment by markus-renezeder** [comment]
Thank you very much!

**Comment by vivet** [comment]
I tried with a simple html example: <html>Hello World</html>, and that worked. 
Could you send me the html you are using, so I can try and reproduce it?
