### ISSUE TITLE
Issue with language code "bg-Latn"

### ISSUE THREAD

**Issue by jkuczek15** [vivet/GoogleApi#387]
Hi,

We're running into an issue when trying to parse 'bg-Latn' as a language code using the Address Validation API.

This example we use the string "Ste 109" for address line 2, this is the response from the Google API demo for one of the address components (demo [here](https://developers.google.com/maps/documentation/address-validation/demo), try with address: 123 Main St Ste 109, Mesa, AZ): 

```json
{
  "componentName": {
    "text": "Ste 109",
    "languageCode": "bg-Latn"
  },
  "componentType": "subpremise",
  "confirmationLevel": "CONFIRMED"
},
```

We run into a **JsonException** with message: "Could not parse bg-Latn".

After doing a bit of digging, I think this is related to a preview feature [here](https://developers.google.com/maps/documentation/address-validation/convert-addresses-english)

I'm proposing a fix to have this language code be parsed as **Language.Unsupported** since this is a breaking change.

**EDIT:** I didn't realize this Language class is not using the `[JsonConverter(typeof(LanguageEnumJsonConverter))]` attribute. It is in a different namespace: `GoogleApi.Entities.Common.Enums.Language` instead of `GoogleApi.Entities.Translate.Common.Enums`. 

Maybe the converter attribute needs to be added here? 

Thanks,
Joe

**Comment by vivet** [comment]
I will take a look at it.
It should handle languages as unknown, but I will need to check

**Comment by vivet** [comment]
I have pushed a fix, by adding the missing Language. 
Also, you were right about the missing JsonConverter, but somehow it doesn't work. Same goes for the other enum json converters. They all hit the default one, which doesn't handle JsonExceptions as Unsupported. I will create a different issue for that.

I also added some missing request and response parameters.
