### ISSUE TITLE
Enum JsonConverters are not applied

### ISSUE THREAD

**Issue by vivet** [vivet/GoogleApi#388]
The enum converters, e.g. Language enums doesn't hit the default where JsonExceptions are caught returning Unsupported.

**Comment by markus-renezeder** [comment]
Is there any update acoording this topic? I ran into this problem today. 

Thank you very much for sharing your project!

**Comment by vivet** [comment]
Hi

How did you experience the problem?
It should only cause problems if Google adds new languages. Can you see what language it fails on, then I will add that.

I don't have much time at the moment, so I won't get to fix the converters any time soon.

**Comment by markus-renezeder** [comment]
I try to serialize the values (e.g. Language or any other enum) for sending it over a rest api. 

I get the error message The converter specified on 'GoogleApi.Entities.Common.Enums.AddressComponentType' does not derive from JsonConverter or have a public parameterless constructor..

I will try to find the reason for the problem and maybe I can give you some further information or provide a fix to you.

**Comment by vivet** [comment]
Try send me the code that gives issues

**Comment by markus-renezeder** [comment]
I tried to reproduce the issue in a new project using the minimal API. It works.
In my project I'm using REFIT - seems the problem occurs there.

Sorry!

**Comment by markus-renezeder** [comment]
I created a new .NET Core API project and added just a minimal API method:

```
app.MapGet("/placeresult", (string id) =>
{
    PlaceResult result = new();

    return result;
})
.WithName("PlaceResult")
.WithOpenApi();

```

**Comment by vivet** [comment]
But there is no code for GoogleApi... I need to see GoogleApi.
It seems your .NET core api is trying to serialize the `PlaceResult`, which might or might not work. At least you control the serialization of you Api, not GoogleApi.

So basically your issue has nothing to do with GoogleApi, it's wihtin your code. 
Generally, you shouldn't expose models from external code directly in your code. After invoking GoogleApi, map the part of the response to your own model that your want to use with the response in your api

**Comment by markus-renezeder** [comment]
You're right. I just want to return the GoogleAPI model and I know I should provide my own model. But that is a lot of work and I wanted to save myself that.

I was able to solve the problem using the following code:

```
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
```

Thank you for your support and sorry for wasting your time.

**Comment by vivet** [comment]
No Problem

The converters with default enum values fixed.
