### ISSUE TITLE
v3.1 - Include Additional Fields in Place Details Review Data

### ISSUE THREAD

**Issue by bcunnien** [vivet/GoogleApi#39]
Two fields should be added to the response data:

profile_photo_url
relative_time_description

**Comment by vivet** [comment]
Hi.
Will look into it. 
Working on v3.1 right now, and hopefully i will deploy a package tonight.

**Comment by vivet** [comment]
Funny, its not mentioned in the documentation, but only in their example. 
Its added now, and when i finish v3.1 later today, i will publish a new package

**Comment by bcunnien** [comment]
You are amazing!  Thanks a ton!!

**Comment by vivet** [comment]
No problem.
I will close the issue. 
Let me know if you have further issues.

**Comment by vivet** [comment]
Nuget published.
