### ISSUE TITLE
Method summary for AutoComplete and QueryAutoComplete wrong?

### ISSUE THREAD

**Issue by co-dax** [vivet/GoogleApi#390]
Summary for the property `AutoComplete` property refers to [https://developers.google.com/places/web-service/query](https://developers.google.com/places/web-service/query) and the summary for property `QueryAutoComplete ` refers to [https://developers.google.com/places/web-service/autocomplete](https://developers.google.com/places/web-service/autocomplete) while it should be the way around.

![image](https://github.com/vivet/GoogleApi/assets/7594292/ab683c30-4407-4c21-b5fa-597e9f34e666)

**Comment by vivet** [comment]
Fixed :-)
Though, I didn't publish a new NuGet package. It will come with next release.

**Comment by co-dax** [comment]
Great, thanks! :-)
