### ISSUE TITLE
maneuver is always None

### ISSUE THREAD

**Issue by MoeHamdan** [vivet/GoogleApi#393]
Using GoogleMaps.Directions.QueryAsync
The library is failing to parse the maneuver, the value is always none. 
![image](https://github.com/vivet/GoogleApi/assets/12870330/dc17b253-1b8b-4651-a359-b62796345ceb)

**Comment by MoeHamdan** [comment]
![image](https://github.com/vivet/GoogleApi/assets/12870330/b9528753-dfd2-4bb2-a255-349209701c42)
This is wrong it should just be maneuver

**Comment by vivet** [comment]
Will take a look at it

**Comment by vivet** [comment]
Fixed
