### ISSUE TITLE
Enum Status is missing DATA_NOT_AVAILABE status

### ISSUE THREAD

**Issue by luca-benvegnu-quanticdigit** [vivet/GoogleApi#394]
In Elevation API google can insert into response DATA_NOT_AVAILABE as response status.
Enum Status is missing DATA_NOT_AVAILABE status and API make exception during deserialization.
Did you plan to add this status?

**Comment by vivet** [comment]
I have added the enum value, and pushed an updated NuGet

**Comment by luca-benvegnu-quanticdigit** [comment]
Thanks a lot.
