### ISSUE TITLE
Missing values in enum GoogleApi.Entities.Places.Common.Enums.OpeningHoursType

### ISSUE THREAD

**Issue by Jay424** [vivet/GoogleApi#395]
According to https://developers.google.com/maps/documentation/places/web-service/reference/rest/v1/places#secondaryhourstype there are some values missing in enum GoogleApi.Entities.Places.Common.Enums.OpeningHoursType.

Missing enum Values are:
SECONDARY_HOURS_TYPE_UNSPECIFIED
ACCESS
ONLINE_SERVICE_HOURS

**Comment by vivet** [comment]
Merged and new NuGet version published
