### ISSUE TITLE
5.4.9 - 403 Forbidden: the client returns an empty response instead of throwing an error

### ISSUE THREAD

**Issue by marco-merola-ef** [vivet/GoogleApi#397]
```
HTTP/1.1 403 Forbidden

[{
  "error": {
    "code": 403,
    "message": "Routes API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/routes.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/routes.googleapis.com/overview?project=XXX"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "routes.googleapis.com",
          "consumer": "projects/XXX"
        }
      }
    ]
  }
}
]
```

When gmaps api returns this error, the client IRoutesMatrixApi doesn't throw any exception and simply returns an empty RoutesMatrixResponse instance. 
Is there a way to instrument the client to fail when the response is not 200?
How do I retrieve the list of errors?

**Comment by vivet** [comment]
As far as I can see in the code, it does throw exception on Status PERMISSION_DENIED. I tested it and for me it throws.
Can you send post the code you are using?

**Comment by vivet** [comment]
I am not sure what I can do then. To me it seems GoogleApi works as it should. no?

**Comment by marco-merola-ef** [comment]
It doesn't throw exception. I am wondering what's the reason behind this decision
https://github.com/vivet/GoogleApi/blob/f1dfb8977115ac8f0a6f228dfa9167a4d4315f76/GoogleApi/HttpEngine.cs#L199

**Comment by vivet** [comment]
Yes I looked at that myself. Honestly, it's many years ago that was added, and I can't fully remember why. I do think it's because in most cases Google doesn't return and error, but 200 with an error message, and i wanted to align it.

**Comment by vivet** [comment]
I have decided to remove the check and forward the 403 error directly.
