### ISSUE TITLE
Include all fields in PlaceSearchText

### ISSUE THREAD

**Issue by KamilUlianowski** [vivet/GoogleApi#45]
Hi vivet, first of all, great job!

I am just wondering, why in place text search there are only 3 fields in response

![result1](https://user-images.githubusercontent.com/15038630/29949069-969a89d4-8eb2-11e7-8c9c-13eb1d441c2d.png)

When i manually do this request in e.g. postman i have also other informations about place

![result2](https://user-images.githubusercontent.com/15038630/29949159-28a8b594-8eb3-11e7-9e7f-4e4a2132e9c5.png)

**Comment by vivet** [comment]
Hi
Will take a look. 
Sometimes Google doesn't document all the fields. Or they expanded and i missed it

**Comment by vivet** [comment]
Try see this 
https://github.com/vivet/GoogleApi/pull/46/files

**Comment by vivet** [comment]
Will finalize one of the next days, need to align with google doc

**Comment by vivet** [comment]
Its done, i will just fix another unrelated issue and then publish a nuget package.

**Comment by vivet** [comment]
Will close the issue, nuget package is published.
Let me know if you have further issues.
