### ISSUE TITLE
Place types

### ISSUE THREAD

**Issue by kbalint** [vivet/GoogleApi#48]
Hi, I'm using your component for extensive GeoCoding, and found that some of the places listed at https://developers.google.com/places/supported_types are not available in GoogleApi.Entities.Common.Enums.LocationType, and it gives an exception when trying to parse the whole response, so the response.Results are always null.

**Comment by vivet** [comment]
Hi.
I just took a quick look, and unless i am wrong geocoding use maps api location types, and what you are referring to is for place searches and additions. A while ago I noticed that the support is different for the two api, or Google documentation is a bit confusing.

If you can try post your request data, i can try reproduce your case.

**Comment by kbalint** [comment]
hi, thanks for the quick answer. 
The request url is: `maps.google.com/maps/api/geocode/json ?key=AIza...&language=hu&address=Budapest%20karin&region=hu`

The response is: 
```
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "75",
               "short_name" : "75",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Fóti út",
               "short_name" : "Fóti út",
               "types" : [ "route" ]
            },
            {
               "long_name" : "IV. kerület",
               "short_name" : "IV. kerület",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
            {
               "long_name" : "Budapest",
               "short_name" : "Budapest",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Magyarország",
               "short_name" : "HU",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "1047",
               "short_name" : "1047",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "Budapest, Fóti út 75, 1047 Magyarország",
         "geometry" : {
            "location" : {
               "lat" : 47.5775859,
               "lng" : 19.092553
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 47.5789348802915,
                  "lng" : 19.0939019802915
               },
               "southwest" : {
                  "lat" : 47.5762369197085,
                  "lng" : 19.0912040197085
               }
            }
         },
         "place_id" : "ChIJSR65OBfaQUcR_GZAMfB2tfQ",
         "types" : [ "establishment", "lodging", "point_of_interest" ]
      }
   ],
   "status" : "OK"
}

```

where the type is "lodging", which is valid according to the documentation, but lacking in the Enum.
If the seachstring is "Budapest Karinthy", the type "school" comes up.

I've recently encountered the following values: food, department_store, home_goods_store, lodging, university, school, cafe, bar, church, hospital.

**Comment by vivet** [comment]
Ok thanks for the data.
Will look into it soon

**Comment by vivet** [comment]
Hi 
I have made a fix. I will release a Nuget package soon, but you can try the branch if you like.

**Comment by vivet** [comment]
The issue has been fixed, PR merged and nuget package published.

**Comment by kbalint** [comment]
thanks! I'll test it and get back to you if needed

**Comment by vivet** [comment]
Cool.
I did perform some integration tests, and determined that 'unknown' is now returned when no enum value exists for a string location type.
Let me know how it works out.
