### ISSUE TITLE
No PlaceId in GeocodingRequest

### ISSUE THREAD

**Issue by robertamontefusco** [vivet/GoogleApi#52]
Hi, I saw that there's no parameter place_id in GeocodingRequest in order to execute this request on Maps:
https://developers.google.com/maps/documentation/geocoding/intro#place-id

Thanks.

**Comment by vivet** [comment]
Hi, looks like you are right. I will fix within a few days.

If i remember correctly, the api used to accept the placeId in the address field. Try that if its urgent.

**Comment by vivet** [comment]
The issue is fixed, and I am deploying nuget package now.
