### ISSUE TITLE
DistanceMatrixRequest,  Index was outside the bounds of the array

### ISSUE THREAD

**Issue by bayzter** [vivet/GoogleApi#56]
Hi, 

When adding enum AvoidWay to Avoid property i get "Index was outside the bounds of the array" on calling DistanceMatrix.Query(matrixRequest) . If Avoid property is not given any value, everything works like a charm.

Thanks

**Comment by vivet** [comment]
Ok thanks for reporting it will look into it and should have a fix in a few days.

**Comment by vivet** [comment]
Issue has been resolved.
I confirmed by implementing a test for Avoid property for distance matrix.
Nuget should be there shortly.

**Comment by vivet** [comment]
Closing issue.

**Comment by bayzter** [comment]
Hi again, thanks for the quick reply!

I just updated NuGet package to 3.2.9 to get distancematrix bug fix.

But now i get error on all properties in DistanceMatrixRequest as if they are no longer there.

Has these been moved else where?

**Comment by bayzter** [comment]
Hi again, again... :-)

False alarm!, reboot of visual studio did the trick.

Tanks for the good work!
