### ISSUE TITLE
How-to : Usage of Snap to Roads with more than 100 GPS waypoints

### ISSUE THREAD

**Issue by ericbrunner** [vivet/GoogleApi#60]
Hi,

Could you provide a sample on how to use the Snap to Road functionality with your .Net port when having more than 100 waypoints. Do you care about that google limitation? 
Best
Eric

**Comment by vivet** [comment]
Hi
Have you tried with 100+ points and it fails or?

**Comment by vivet** [comment]
ah i see now.
I probably didn't see the limitation in the Google api docs.
I will add the validation.

**Comment by ericbrunner** [comment]
Haven't tried it at all. Could you be so kind and point me to a sample code that uses your Google Webservice C# nuget? Thx

**Comment by ericbrunner** [comment]
Take a look at the snapToRoads function in that Android Java sample. They do a overlapping test
https://github.com/googlemaps/roads-api-samples/blob/master/app/src/main/java/com/google/example/maps/roadsapi/MainActivity.java

**Comment by ericbrunner** [comment]
Here the Google doc for processing long path
https://developers.google.com/maps/documentation/roads/advanced?hl=en#processing_long_paths

**Comment by vivet** [comment]
I am mapping the api directly after Google, so for now at least, you need to handle long paths in your own code, as Google describes. I might consider to implement a Function for it, but i wont include it directly, as it would result in possible unintended use of quota.

**Comment by vivet** [comment]
In regards of using the library, then its actually really simple. 
Here is a very tiny example: https://github.com/vivet/GoogleApi/wiki

Otherwise try check the tests.

**Comment by vivet** [comment]
SnapToRoad example in test here:
https://github.com/vivet/GoogleApi/blob/master/GoogleApi.Test/Maps/Roads/SnapToRoad/SnapToRoadTests.cs#L17

**Comment by ericbrunner** [comment]
Thanks a lot!

**Comment by vivet** [comment]
Sure, no problem :-)
Please star the library if you like it.
...and let me know if you need further assistance.

**Comment by ericbrunner** [comment]
I found that wrapper https://github.com/maximn/google-maps/ 
, too. What would you suggest me to use? thanks for your support

**Comment by vivet** [comment]
Haha
Well you are asking if you should use mine or another, I would say mine :-)
The other one seems to cover less of the Google Api's and also only works with .net framework and not the latest net standard from Microsoft.

**Comment by vivet** [comment]
Also i know that i am way faster i responding and fixing issues.
The validation issue you created earlier to day (well this issue), is already fixed and Nuget published.

**Comment by ericbrunner** [comment]
Thanks. I thought that they cloned your code becasue their API looks very similar. Thanks, will use yours :-)

**Comment by vivet** [comment]
Your are welcome
Feel free to poke me if you have further questions or issues

**Comment by ericbrunner** [comment]
I attached the Testrum log I get in R# Testrunner. 108 tests fail. Hope is helpful
[AllTestsFromGoogleApi.Test.zip](https://github.com/vivet/GoogleApi/files/1490768/AllTestsFromGoogleApi.Test.zip)

**Comment by vivet** [comment]
you can't just run the tests. 
Check this https://github.com/vivet/GoogleApi/wiki/Test-Suite

**Comment by ericbrunner** [comment]
I checked that and added my API key. It's the language. Your tests assert text literals in english and I have a german desktop system. that's all.

**Comment by vivet** [comment]
Ah okay, yes i see.
I don't think i will change that as i am the only one developing and running the tests.

**Comment by vivet** [comment]
Feel free to make a PR if you like

**Comment by ericbrunner** [comment]
No thanks. Its easier to change my desktop language setting ;-)

**Comment by vivet** [comment]
Yes :-)
Besides in my opinion development should always be in English.
I am from Denmark myself, never code in that language.

**Comment by ericbrunner** [comment]
ha, ha.. yeah absolutly. No I code in english (of course) only my desktop is set to german language.
