### ISSUE TITLE
Roads API speed limits are not always ints

### ISSUE THREAD

**Issue by siegeon** [vivet/GoogleApi#63]
![image](https://user-images.githubusercontent.com/5737831/33154750-dc4a3200-cfa7-11e7-9e98-088491c4dadf.png)

**Comment by vivet** [comment]
Hi
Will take a look at it. 
Though strange that the speed limit somewhere is a fractional number :-)

**Comment by vivet** [comment]
I have made the fix and merged it.
Will publish a Nuget soon.

**Comment by vivet** [comment]
New package published.

**Comment by vivet** [comment]
Will close the issue

**Comment by siegeon** [comment]
No joke, given the stupid result all I'm doing is truncating the number
anyway. I tried to fix it in the framework but did not want to mess with
the json serialize. I can look through my data to get the placeId if you
need it.

**Comment by vivet** [comment]
Its fixed the issue, and nuget updated earlier today :-)

**Comment by vivet** [comment]
Or do you still have issues?

**Comment by siegeon** [comment]
I will get the latest tonight and test it out. But I'm sure that fixes the
issue. Thank you.

**Comment by siegeon** [comment]
Nope, all is well.
