### ISSUE TITLE
GoogleApi.Exceptions.GoogleApiException: Error converting value \"light_rail_station\" to type 'GoogleApi.Entities.Common.Enums.PlaceLocationType

### ISSUE THREAD

**Issue by vineus** [vivet/GoogleApi#69]
Same issue as: https://github.com/vivet/GoogleApi/issues/50

Wouldn't it be better to use a custom deserializer for Google enums to fallback on `unknown` in case of new/not-yet-known type ? (or add an option to deserialize as a string for enum values)

I'm under the impression that Google modifies the list quite often...

**Comment by vivet** [comment]
I did implement it exactly like that, but might be missing to use it for done request / response properties.
I will look I to it. 
From which endpoint did you experience it?

**Comment by vineus** [comment]
Yes, I just bumped on the code using your `StringEnumOrDefaultConverter` :-)

I used the `PlacesDetailsRequest` endpoint

**Comment by vineus** [comment]
And I'm using an old version... 3.2.10. My bad, will upgrade

**Comment by vineus** [comment]
It's not the fallback converter here: https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Places/Common/Prediction.cs#L44

and here: https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Places/Add/Request/PlacesAddRequest.cs#L80

want a PR ?

**Comment by vivet** [comment]
Sure make a PR.
I can make nugget sometime later today

**Comment by vivet** [comment]
New Nuget package v3.2.13 published.

**Comment by vivet** [comment]
I hope the issue is resolved in latest release. 
Otherwise let me know.
And if you like the library, please give it a star

**Comment by vineus** [comment]
It's resolved! Thanks a lot for your reactivity.
