### ISSUE TITLE
Google Places API - Filter by multiple countries

### ISSUE THREAD

**Issue by vecalion** [vivet/GoogleApi#75]
It looks to me that the current implementation doesn't allow to filter by multiple countries, since Dictionary<> doesn't allow to have non-unique keys. I wonder if I'm missing something?

> components — A grouping of places to which you would like to restrict your results. Currently, you can use components to filter by up to 5 countries. Countries must be passed as a two character, ISO 3166-1 Alpha-2 compatible country code. For example: components=country:fr would restrict your results to places within France. Multiple countries must be passed as multiple country:XX filters, with the pipe character (|) as a separator. For example: components=country:us|country:pr|country:vi|country:gu|country:mp would restrict your results to places within the United States and its unincorporated organized territories.

https://github.com/vivet/GoogleApi/blob/dab89ddefe066f3d5d3256d92ab8599845a734ef/GoogleApi/Entities/Places/AutoComplete/Request/PlacesAutoCompleteRequest.cs#L113

**Comment by vivet** [comment]
Hi
Thanks for reporting it.
I will take a look and implement a different collection.

**Comment by vivet** [comment]
The issue is solved, and I will publish an updated Nuget package soon

**Comment by vecalion** [comment]
That was fast, thanks!

**Comment by vivet** [comment]
Was an easy fix :-)

**Comment by vivet** [comment]
The package is published, (currently validating), but should be visible in about 10 min.
Let me know if you still experience the issue.
