### ISSUE TITLE
Missing underscores in SearchPlaceType enum

### ISSUE THREAD

**Issue by karimElJed** [vivet/GoogleApi#81]
Hi,

first of all thank you for providing this library. It is very neat.

There is a problem with your enum SearchPlaceType. According to the Google place types reference (https://developers.google.com/places/supported_types?hl=en) there are a few place types that contain an underscore. For example "amusement_park" and "meal_delivery".

When using the SearchPlaceType enum these underscores are missing. Therefore requests using these enum values return wrong results with any kind of place types (point_of_interest).

1.   Please Add the underscores in the enum values

2.  It would be great if the request class would support an additonal free definable string property for the place type. The enum value could be the fallback value if the string is empty. in result there would be no need to update the library when Google adds a new place type.

Thanks,
Karim

**Comment by vivet** [comment]
Hi
Thanks for the compliment.

I have been trying to align the different types used by google, but must have missed this enum type.
Basically what needs to be done, is just to add EnumMember attributes to all members of the SearchPlaceType ( https://github.com/vivet/GoogleApi/blob/master/GoogleApi/Entities/Places/Search/Common/Enums/SearchPlaceType.cs).

If you have the time, feel free to make a PR, otherwise i will fix it within the next couple of days.

**Comment by karimElJed** [comment]
Just created a pull request. 
I started with the implementation right after writing the issue and before reading your comment. I took another approach than the EnumMember solution. Hope you like it.

**Comment by vivet** [comment]
Seems nice enough the solution.
Problem is that Google doesn't always name the different types in their api's with integrity. The solution will break in case Google adds a camel-case type without underscores.

**Comment by vivet** [comment]
But don't worry I will make the fix and publish a new Nuget within a few hours

**Comment by karimElJed** [comment]
That's a good point, I didn't thought about that.
Thanks!

**Comment by vivet** [comment]
No matter normally i love conventions and C# extension methods  :-)
I am testing the fix now

**Comment by karimElJed** [comment]
Please note that some of the place types are deprecated. I added an ObsoleteAttribute to them.

**Comment by vivet** [comment]
Yes i saw, I just removed it. People can handle that easily.

**Comment by vivet** [comment]
I have published a new Nuget package.

**Comment by vivet** [comment]
The issue should be fixed.
Please star the library if you like it.

**Comment by vivet** [comment]
Hmmm.
Yes you are right, i didn't see that. I thought it was the response.
Then i guess we will need your convention afterall

**Comment by vivet** [comment]
I fixed this one.

**Comment by karimElJed** [comment]
Thanks! I will test and close the issue on tuesday.

**Comment by karimElJed** [comment]
Hi, the solution doesn't work. 

Your code is searching for the EnumMember attribute on the enum definition and not on the enum values. I just fixed it on my fork and will create a pull request now.

**Comment by vivet** [comment]
Hi
Sorry, I might have been too fast in the implementation. 
I will check, merge and publish it tomorrow. 
Thank for your patience.

**Comment by karimElJed** [comment]
Thanks!
