### ISSUE TITLE
Portable package without dependency to Xamarin.Forms

### ISSUE THREAD

**Issue by karimElJed** [vivet/GoogleApi#84]
Would be nice to have a version for use in a portable class library without the dependency to Xamarin.Forms. I'm using the library in a Xamarin native project and removed the Xamarin.Forms references without any problem.

**Comment by vivet** [comment]
Hi again :-)
I dont have much knowledge about Xamarin, I just added the portable build for a user of the library.
But i will look into it. Or if you could make a PR it would be awseome.

**Comment by karimElJed** [comment]
Yes, I can do a PR in the next couple of days.

**Comment by vivet** [comment]
Seems they could just be removed.
You don't need to make a PR, i fixed it

**Comment by vivet** [comment]
Fixed and Nuget published.
