### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by fariskarcic** [vivet/GoogleApi#87]
Hey Vivet,

thanks for you libraries, they are huge help especially for us nublet devs.
As I said since I'm nublet dev, and I have just recently figured out what generics are for, and I'm not quite used to those, so would you mind updating your example with some actual one. Like e.g. for Distance Matrix.

I figured out this part

`DistanceMatrixRequest request = new DistanceMatrixRequest(); `
`DistanceMatrixResponse response = await GoogleMaps.DistanceMatrix.QueryAsync(request);`

But how do I pass parameters at
`new DistanceMatrixRequest(); `

And is there some config for api key?

Thanks in advance

**Comment by fariskarcic** [comment]
Aight after a bit of exploration of your classes I figured it out.
`DistanceMatrixRequest request = new DistanceMatrixRequest();`
`request.OriginsRaw = startLat + "," + startLong;`
`request.DestinationsRaw = endLat + "," + endLong;`
` DistanceMatrixResponse response = await GoogleMaps.DistanceMatrix.QueryAsync(request);`
`var distance = response.Rows.ElementAt(0).Elements.ElementAt(0).Distance.Text;`

But now I wonder where is api key located and how does it work without it?
Do I just add?
`request.Key = "xxxxx"`

**Comment by vivet** [comment]
Hi
Good that you figured it out. It should be fairly easy to use the different api's. 
Check the distance matrix tests, https://github.com/vivet/GoogleApi/blob/master/GoogleApi.Test/Maps/DistanceMatrix/DistanceMatrixTests.cs#L17 for details.

The key is something you need to generate using Google Console. https://developers.google.com/maps/documentation/directions/get-api-key
Some Api's requires a key, whereas others doesn't. Most of them can be used with a limited amount of daily requests with a free key.

**Comment by fariskarcic** [comment]
Oh yeah, just like I thought.
And also I have that key, I have full client side of google maps api made.
However distance matrix on my backend works without a key, thats what I'm thinking off.

**Comment by vivet** [comment]
Yes some Api's doesn't require a key, but its recommended to supply one, as the quota and features are different. For example distance matrix doesn't support traffic when not specifying a key.

By the way, if you like mu library, please give it a star.

**Comment by vivet** [comment]
Hi
I will close the issue.
I hope you figured everything out, otherwise feel free to re-open the issue, or open another one.
