### ISSUE TITLE
Question regarding price_level in Places

### ISSUE THREAD

**Issue by Michael-Kyriacou** [vivet/GoogleApi#89]
Hello Vivet,

I would like to ask you, why if I use min and max price level in my query, I still get results but if I try the query in my browser, it does not bring me results? 

Query by your API:
![screenshot 2018-03-10 11 27 22](https://user-images.githubusercontent.com/5446409/37240812-f8203eb0-2458-11e8-8170-766e32da1bf3.png)

Response by your API:
![screenshot 2018-03-10 11 32 39](https://user-images.githubusercontent.com/5446409/37240816-06d4b292-2459-11e8-8ca6-5da0c2b324f9.png)

Query with url in browser:
https://maps.googleapis.com/maps/api/place/textsearch/xml?minprice=0&maxprice=5&query=nightlife+near+Nicosia+Cyprus&key=[MY_API_KEY]

Response by url:
<PlaceSearchResponse><status>ZERO_RESULTS</status></PlaceSearchResponse>

While writing this question, I think I found the issue. Check the screenshot with the result in .net. minprice has a string value, not an int as documentation says (0-4). Same for maxprice probably.

I tried it with text, and google returns results. I beileve it cannot parse the string value to int and it ignores these parameters and it works. Not sure.

Query with url in browser:
https://maps.googleapis.com/maps/api/place/textsearch/xml?query=cinemas+near+Nicosia+Cyprus&minprice=expensive&maxprice=veryexpensive&key=[MY_API_KEY]

I get results with this query

Thank you for your time and for this API, is really good.

**Comment by vivet** [comment]
Hi
I will take a look. The min/max price is enum, and maybe the conversion is wrong.
I will get back shortly

**Comment by vivet** [comment]
Hi
I have implemented a fix. 
If you can check the PR, and maybe test it works as expected, then I will publish a Nuget update afterwards.

**Comment by vivet** [comment]
Nevermind i implemented the missing tests and it works.

**Comment by vivet** [comment]
Nuget version 3.2.20 published.
Let me know if you have further issues, otherwise close the issue.

**Comment by Michael-Kyriacou** [comment]
Yes it works now! Thanks
