### ISSUE TITLE
transit implementation

### ISSUE THREAD

**Issue by stec76** [vivet/GoogleApi#95]
Hello,
I really appreciate your work , the library works very well. 
Have you any plane to implement transit API?

Thank you

Stefano

**Comment by vivet** [comment]
Hi
Sure i can implement it, though I am not familiar with that it's an API. Could you link me to the API docs (not the page explaining about the API, but the actual API docs)

**Comment by stec76** [comment]
Hi,
thank you here a link to google docs:
https://developers.google.com/transit/gtfs/#how-do-i-start
https://developers.google.com/maps/documentation/javascript/trafficlayer#transit_layer

Thank you

Stafno

**Comment by vivet** [comment]
Hi 
I checked once more, and a transit api doesn't exists as web-service. Its a JavaScript tool. 
What is your objective, or what are you trying to archive. Maybe i can point you in the right direction.

**Comment by vivet** [comment]
I will close the issue. 
Let me know if I can assist you with more.
